<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.1 Basic R Programming | Landscape Genetic Data Analysis with R</title>
  <meta name="description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics’. The output format is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="2.1 Basic R Programming | Landscape Genetic Data Analysis with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics’. The output format is bookdown::gitbook." />
  <meta name="github-repo" content="hhwagner1/LandGenCourse_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.1 Basic R Programming | Landscape Genetic Data Analysis with R" />
  
  <meta name="twitter:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics’. The output format is bookdown::gitbook." />
  

<meta name="author" content="Editor: Helene Wagner (University of Toronto)" />


<meta name="date" content="2024-01-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="review-of-r-skills.html"/>
<link rel="next" href="r-graphics.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.1/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.1/leaflet-providers-plugin.js"></script>
<script src="libs/d3-3.5.6/d3.min.js"></script>
<link href="libs/profvis-0.3.6.9000/profvis.css" rel="stylesheet" />
<script src="libs/profvis-0.3.6.9000/profvis.js"></script>
<script src="libs/profvis-0.3.6.9000/scroll.js"></script>
<link href="libs/highlight-6.2.0/textmate.css" rel="stylesheet" />
<script src="libs/highlight-6.2.0/highlight.js"></script>
<script src="libs/profvis-binding-0.3.8/profvis.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Landscape Genetic Data Analysis with R</a></li>

<li class="divider"></li>
<li class="part"><span><b>Getting Started</b></span></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i><b>1.1</b> How to use this Book</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#book-structure"><i class="fa fa-check"></i>1. Book Structure</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#find-what-is-relevant-for-you"><i class="fa fa-check"></i>2. Find what is relevant for you</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#course-r-package-landgencourse"><i class="fa fa-check"></i>3. Course R package ‘LandGenCourse’</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="list-of-packages.html"><a href="list-of-packages.html"><i class="fa fa-check"></i><b>1.2</b> List of R Packages by Vignette</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html"><i class="fa fa-check"></i><b>2</b> Review of R Skills</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-r.html"><a href="basic-r.html"><i class="fa fa-check"></i><b>2.1</b> Basic R Programming</a>
<ul>
<li class="chapter" data-level="" data-path="basic-r.html"><a href="basic-r.html#overview"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="basic-r.html"><a href="basic-r.html#data-types"><i class="fa fa-check"></i>2. Data Types</a></li>
<li class="chapter" data-level="" data-path="basic-r.html"><a href="basic-r.html#data-containers"><i class="fa fa-check"></i>3. Data Containers</a></li>
<li class="chapter" data-level="" data-path="basic-r.html"><a href="basic-r.html#programming"><i class="fa fa-check"></i>4. Programming</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-graphics.html"><a href="r-graphics.html"><i class="fa fa-check"></i><b>2.2</b> R Graphics</a>
<ul>
<li class="chapter" data-level="" data-path="r-graphics.html"><a href="r-graphics.html#overview-1"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="r-graphics.html"><a href="r-graphics.html#univariate-plots"><i class="fa fa-check"></i>2. Univariate plots</a></li>
<li class="chapter" data-level="" data-path="r-graphics.html"><a href="r-graphics.html#bivariate-plots"><i class="fa fa-check"></i>3. Bivariate plots</a></li>
<li class="chapter" data-level="" data-path="r-graphics.html"><a href="r-graphics.html#advanced-plotting"><i class="fa fa-check"></i>4. Advanced plotting</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i><b>2.3</b> Further R resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="github-for-group-projects.html"><a href="github-for-group-projects.html"><i class="fa fa-check"></i><b>3</b> GitHub for Group Projects</a>
<ul>
<li class="chapter" data-level="3.1" data-path="github.html"><a href="github.html"><i class="fa fa-check"></i><b>3.1</b> Why use GitHub?</a>
<ul>
<li class="chapter" data-level="" data-path="github.html"><a href="github.html#goals"><i class="fa fa-check"></i>1. Goals</a></li>
<li class="chapter" data-level="" data-path="github.html"><a href="github.html#version"><i class="fa fa-check"></i>2. Watch course video: Version Control 101</a></li>
<li class="chapter" data-level="" data-path="github.html"><a href="github.html#slides"><i class="fa fa-check"></i>3. Preview slides</a></li>
<li class="chapter" data-level="" data-path="github.html"><a href="github.html#next-steps"><i class="fa fa-check"></i>4. Next steps</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>3.2</b> Installation</a>
<ul>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#goals-1"><i class="fa fa-check"></i>1. Goals</a></li>
<li class="chapter" data-level="3.2.1" data-path="install.html"><a href="install.html#how-to-get-github-and-gitkraken-for-free"><i class="fa fa-check"></i><b>3.2.1</b> 2. How to get GitHub and GitKraken for free</a></li>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#happygit"><i class="fa fa-check"></i>3. Happy Git with R</a></li>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#gitvideos"><i class="fa fa-check"></i>4. Video tutorials: installation</a></li>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#join"><i class="fa fa-check"></i>5. Joining your group’s project on GitHub</a></li>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#repo"><i class="fa fa-check"></i>6. Setting up a group repo</a></li>
<li class="chapter" data-level="" data-path="install.html"><a href="install.html#next-steps-1"><i class="fa fa-check"></i>7. Next steps</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="workflow.html"><a href="workflow.html"><i class="fa fa-check"></i><b>3.3</b> Workflows</a>
<ul>
<li class="chapter" data-level="" data-path="workflow.html"><a href="workflow.html#goals-2"><i class="fa fa-check"></i>1. Goals</a></li>
<li class="chapter" data-level="" data-path="workflow.html"><a href="workflow.html#step-by-step-tutorials"><i class="fa fa-check"></i>2. Step-by-step tutorials</a></li>
<li class="chapter" data-level="" data-path="workflow.html"><a href="workflow.html#further-resources"><i class="fa fa-check"></i>3. Further resources</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Basic Topics</b></span></li>
<li class="chapter" data-level="4" data-path="Week1.html"><a href="Week1.html"><i class="fa fa-check"></i><b>4</b> Week 1: Importing Genetic Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="video_1.html"><a href="video_1.html"><i class="fa fa-check"></i><b>4.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_1.html"><a href="video_1.html#embedded-video"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_1.html"><a href="video_1.html#preview-slides"><i class="fa fa-check"></i>2. Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tutorial_1.html"><a href="tutorial_1.html"><i class="fa fa-check"></i><b>4.2</b> Interactive Tutorial 1</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_1.html"><a href="tutorial_1.html#list-of-r-commands-covered-this-week"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_1.html"><a href="tutorial_1.html#general-instructions"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="WE_1.html"><a href="WE_1.html"><i class="fa fa-check"></i><b>4.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#overview-of-worked-example"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#import-data-from-.csv-file"><i class="fa fa-check"></i>2. Import data from .csv file</a></li>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#create-genind-object"><i class="fa fa-check"></i>3. Create ‘genind’ Object</a></li>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#view-information-stored-in-genind-object"><i class="fa fa-check"></i>4. View information stored in ‘genind’ object</a></li>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#import-data-with-gstudio-package"><i class="fa fa-check"></i>5. Import data with ‘gstudio’ package</a></li>
<li class="chapter" data-level="" data-path="WE_1.html"><a href="WE_1.html#importing-snp-data"><i class="fa fa-check"></i>6. Importing SNP data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-1.html"><a href="r-exercise-week-1.html"><i class="fa fa-check"></i>R exercise Week 1</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="Week2.html"><a href="Week2.html"><i class="fa fa-check"></i><b>5</b> Week 2: Spatial Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="video_2.html"><a href="video_2.html"><i class="fa fa-check"></i><b>5.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_2.html"><a href="video_2.html#embedded-video-1"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_2.html"><a href="video_2.html#preview-slides-1"><i class="fa fa-check"></i>2. Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="tutorial_2.html"><a href="tutorial_2.html"><i class="fa fa-check"></i><b>5.2</b> Interactive Tutorial 2</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_2.html"><a href="tutorial_2.html#list-of-r-commands-covered-this-week-1"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_2.html"><a href="tutorial_2.html#general-instructions-1"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="WE_2.html"><a href="WE_2.html"><i class="fa fa-check"></i><b>5.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_2.html"><a href="WE_2.html#overview-of-worked-example-1"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_2.html"><a href="WE_2.html#import-site-data-from-.csv-file"><i class="fa fa-check"></i>2. Import site data from .csv file</a></li>
<li class="chapter" data-level="" data-path="WE_2.html"><a href="WE_2.html#display-raster-data-and-overlay-sampling-locations-extract-data"><i class="fa fa-check"></i>3. Display raster data and overlay sampling locations, extract data</a></li>
<li class="chapter" data-level="" data-path="WE_2.html"><a href="WE_2.html#calculate-landscape-metrics"><i class="fa fa-check"></i>4. Calculate landscape metrics</a></li>
<li class="chapter" data-level="" data-path="WE_2.html"><a href="WE_2.html#sample-landscape-metrics-within-buffer-around-sampling-locations"><i class="fa fa-check"></i>5. Sample landscape metrics within buffer around sampling locations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-2.html"><a href="r-exercise-week-2.html"><i class="fa fa-check"></i>R Exercise Week 2</a></li>
<li class="chapter" data-level="5.4" data-path="bonus_2a.html"><a href="bonus_2a.html"><i class="fa fa-check"></i><b>5.4</b> Bonus: ‘sf’ and ‘terra’</a>
<ul>
<li class="chapter" data-level="" data-path="bonus_2a.html"><a href="bonus_2a.html#overview-2"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="bonus_2a.html"><a href="bonus_2a.html#import-and-export-esri-shapefiles"><i class="fa fa-check"></i>2. Import and export ESRI shapefiles</a></li>
<li class="chapter" data-level="" data-path="bonus_2a.html"><a href="bonus_2a.html#compatibility-with-sp-and-raster-objects"><i class="fa fa-check"></i>3. Compatibility with <code>sp</code> and <code>raster</code> objects</a></li>
<li class="chapter" data-level="" data-path="bonus_2a.html"><a href="bonus_2a.html#plotting-spatial-data-with-tmap"><i class="fa fa-check"></i>4. Plotting spatial data with <code>tmap</code></a></li>
<li class="chapter" data-level="" data-path="bonus_2a.html"><a href="bonus_2a.html#plot-a-categorical-map-with-predefined-color-scheme"><i class="fa fa-check"></i>5. Plot a categorical map with predefined color scheme</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Week3.html"><a href="Week3.html"><i class="fa fa-check"></i><b>6</b> Week 3: Genetic Diversity</a>
<ul>
<li class="chapter" data-level="6.1" data-path="video_3.html"><a href="video_3.html"><i class="fa fa-check"></i><b>6.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_3.html"><a href="video_3.html#embedded-video-2"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_3.html"><a href="video_3.html#video-part-1"><i class="fa fa-check"></i>Video, Part 1</a></li>
<li class="chapter" data-level="" data-path="video_3.html"><a href="video_3.html#video-part-2"><i class="fa fa-check"></i>Video, Part 2</a></li>
<li class="chapter" data-level="" data-path="video_3.html"><a href="video_3.html#preview-slides-2"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="tutorial_3.html"><a href="tutorial_3.html"><i class="fa fa-check"></i><b>6.2</b> Interactive Tutorial 3</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_3.html"><a href="tutorial_3.html#list-of-r-commands-covered-this-week-2"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_3.html"><a href="tutorial_3.html#general-instructions-2"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="WE_3.html"><a href="WE_3.html"><i class="fa fa-check"></i><b>6.3</b> Worked Example</a></li>
<li class="chapter" data-level="6.4" data-path="r-exercise-week-3.html"><a href="r-exercise-week-3.html"><i class="fa fa-check"></i><b>6.4</b> R Exercise Week 3</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Week4.html"><a href="Week4.html"><i class="fa fa-check"></i><b>7</b> Week 4: Metapopulations</a>
<ul>
<li class="chapter" data-level="7.1" data-path="video_4.html"><a href="video_4.html"><i class="fa fa-check"></i><b>7.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_4.html"><a href="video_4.html#embedded-video-3"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_4.html"><a href="video_4.html#video-part-1-1"><i class="fa fa-check"></i>Video, Part 1</a></li>
<li class="chapter" data-level="" data-path="video_4.html"><a href="video_4.html#video-part-2-1"><i class="fa fa-check"></i>Video, Part 2</a></li>
<li class="chapter" data-level="" data-path="video_4.html"><a href="video_4.html#preview-slides-3"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="tutorial_4.html"><a href="tutorial_4.html"><i class="fa fa-check"></i><b>7.2</b> Interactive Tutorial 4</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_4.html"><a href="tutorial_4.html#list-of-r-commands-covered-this-week-3"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_4.html"><a href="tutorial_4.html#general-instructions-3"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="WE_4.html"><a href="WE_4.html"><i class="fa fa-check"></i><b>7.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#overview-of-worked-example-3"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#spatial-distribution-of-genetic-structure"><i class="fa fa-check"></i>2. Spatial distribution of genetic structure</a></li>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#what-determines-genetic-differentiation-among-sites"><i class="fa fa-check"></i>3. What determines genetic differentiation among sites?</a></li>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#what-determines-genetic-diversity"><i class="fa fa-check"></i>4. What determines genetic diversity?</a></li>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#are-genetic-differentiation-and-diversity-related"><i class="fa fa-check"></i>5. Are genetic differentiation and diversity related?</a></li>
<li class="chapter" data-level="" data-path="WE_4.html"><a href="WE_4.html#effect-of-recent-extinction-events"><i class="fa fa-check"></i>6. Effect of recent extinction events</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-4.html"><a href="r-exercise-week-4.html"><i class="fa fa-check"></i>R Exercise Week 4</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="Week5.html"><a href="Week5.html"><i class="fa fa-check"></i><b>8</b> Week 5: Spatial Statistics</a>
<ul>
<li class="chapter" data-level="8.1" data-path="video_5.html"><a href="video_5.html"><i class="fa fa-check"></i><b>8.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_5.html"><a href="video_5.html#embedded-video-4"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_5.html"><a href="video_5.html#preview-slides-4"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tutorial_5.html"><a href="tutorial_5.html"><i class="fa fa-check"></i><b>8.2</b> Interactive Tutorial 5</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_5.html"><a href="tutorial_5.html#list-of-r-commands-covered-this-week-4"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_5.html"><a href="tutorial_5.html#general-instructions-4"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="WE_5.html"><a href="WE_5.html"><i class="fa fa-check"></i><b>8.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#overview-of-worked-example-4"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#data-import-and-manipulation"><i class="fa fa-check"></i>2. Data import and manipulation</a></li>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#calculate-genetic-distances"><i class="fa fa-check"></i>3. Calculate genetic distances</a></li>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#perform-a-mantel-test-to-test-for-ibd"><i class="fa fa-check"></i>4. Perform a Mantel test to test for IBD</a></li>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#create-mantel-correlogram-for-genetic-data"><i class="fa fa-check"></i>5. Create Mantel correlogram for genetic data</a></li>
<li class="chapter" data-level="" data-path="WE_5.html"><a href="WE_5.html#specify-spatial-weights-and-calculate-morans-i"><i class="fa fa-check"></i>6. Specify spatial weights and calculate Moran’s I</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-5.html"><a href="r-exercise-week-5.html"><i class="fa fa-check"></i>R Exercise Week 5</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="Week6.html"><a href="Week6.html"><i class="fa fa-check"></i><b>9</b> Week 6: Quantitative Genetics</a>
<ul>
<li class="chapter" data-level="9.1" data-path="video_6.html"><a href="video_6.html"><i class="fa fa-check"></i><b>9.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_6.html"><a href="video_6.html#embedded-video-5"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_6.html"><a href="video_6.html#video-part-1-2"><i class="fa fa-check"></i>Video, Part 1</a></li>
<li class="chapter" data-level="" data-path="video_6.html"><a href="video_6.html#video-part-2-2"><i class="fa fa-check"></i>Video, Part 2</a></li>
<li class="chapter" data-level="" data-path="video_6.html"><a href="video_6.html#preview-slides-5"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="tutorial_6.html"><a href="tutorial_6.html"><i class="fa fa-check"></i><b>9.2</b> Interactive Tutorial 6</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_6.html"><a href="tutorial_6.html#list-of-r-commands-covered-this-week-5"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_6.html"><a href="tutorial_6.html#general-instructions-5"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="WE_6.html"><a href="WE_6.html"><i class="fa fa-check"></i><b>9.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_6.html"><a href="WE_6.html#overview-of-worked-example-5"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_6.html"><a href="WE_6.html#estimate-genetic-and-non-genetic-variance-components-from-a-common-garden-experiment"><i class="fa fa-check"></i>2. Estimate genetic and non-genetic variance components from a common garden experiment</a></li>
<li class="chapter" data-level="" data-path="WE_6.html"><a href="WE_6.html#estimate-trait-heritability"><i class="fa fa-check"></i>3. Estimate trait heritability</a></li>
<li class="chapter" data-level="" data-path="WE_6.html"><a href="WE_6.html#compare-q_st-to-f_st-measured-from-snp-data"><i class="fa fa-check"></i>4. Compare <span class="math inline">\(Q_{st}\)</span> to <span class="math inline">\(F_{st}\)</span> measured from SNP data</a></li>
<li class="chapter" data-level="" data-path="WE_6.html"><a href="WE_6.html#assess-correlation-between-trait-and-environment"><i class="fa fa-check"></i>5. Assess correlation between trait and environment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-6.html"><a href="r-exercise-week-6.html"><i class="fa fa-check"></i>R Exercise Week 6</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Week7.html"><a href="Week7.html"><i class="fa fa-check"></i><b>10</b> Week 7: Spatial Linear Models</a>
<ul>
<li class="chapter" data-level="10.1" data-path="video_7.html"><a href="video_7.html"><i class="fa fa-check"></i><b>10.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_7.html"><a href="video_7.html#embedded-video-6"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_7.html"><a href="video_7.html#video-part-1-3"><i class="fa fa-check"></i>Video, Part 1</a></li>
<li class="chapter" data-level="" data-path="video_7.html"><a href="video_7.html#video-part-2-3"><i class="fa fa-check"></i>Video, Part 2</a></li>
<li class="chapter" data-level="" data-path="video_7.html"><a href="video_7.html#preview-slides-6"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="tutorial_7.html"><a href="tutorial_7.html"><i class="fa fa-check"></i><b>10.2</b> Interactive Tutorial 7</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_7.html"><a href="tutorial_7.html#list-of-r-commands-covered-this-week-6"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_7.html"><a href="tutorial_7.html#general-instructions-6"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="WE_7.html"><a href="WE_7.html"><i class="fa fa-check"></i><b>10.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#overview-of-worked-example-6"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#explore-data-set"><i class="fa fa-check"></i>2. Explore data set</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#test-regression-residuals-for-spatial-autocorrelation"><i class="fa fa-check"></i>3. Test regression residuals for spatial autocorrelation</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#fit-models-with-spatially-correlated-error-gls-with-package-nlme"><i class="fa fa-check"></i>4. Fit models with spatially correlated error (GLS) with package ‘nlme’</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#fit-spatial-simultaneous-autoregressive-error-models-sar"><i class="fa fa-check"></i>5. Fit spatial simultaneous autoregressive error models (SAR)</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#spatial-filtering-with-mem-using-package-spmoran"><i class="fa fa-check"></i>6. Spatial filtering with MEM using package ‘spmoran’</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#fit-spatially-varying-coefficients-model-with-package-spmoran"><i class="fa fa-check"></i>7. Fit spatially varying coefficients model with package ‘spmoran’</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#model-with-patchsize-and-ibr"><i class="fa fa-check"></i>Model with PatchSize and IBR</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#model-with-ibr-only"><i class="fa fa-check"></i>Model with IBR only</a></li>
<li class="chapter" data-level="" data-path="WE_7.html"><a href="WE_7.html#conclusions"><i class="fa fa-check"></i>8. Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-7.html"><a href="r-exercise-week-7.html"><i class="fa fa-check"></i>R Exercise Week 7</a></li>
<li class="chapter" data-level="10.4" data-path="bonus_7a.html"><a href="bonus_7a.html"><i class="fa fa-check"></i><b>10.4</b> Bonus: Si index</a>
<ul>
<li class="chapter" data-level="" data-path="bonus_7a.html"><a href="bonus_7a.html#overview-of-bonus-materials"><i class="fa fa-check"></i>1. Overview of Bonus Materials</a></li>
<li class="chapter" data-level="" data-path="bonus_7a.html"><a href="bonus_7a.html#import-ecological-distance-matrices"><i class="fa fa-check"></i>2. Import ecological distance matrices</a></li>
<li class="chapter" data-level="" data-path="bonus_7a.html"><a href="bonus_7a.html#optimize-the-scaling-parameter-alpha"><i class="fa fa-check"></i>3. Optimize the scaling parameter alpha</a></li>
<li class="chapter" data-level="" data-path="bonus_7a.html"><a href="bonus_7a.html#calculate-hanskis-index-si-with-source-patch-parameters"><i class="fa fa-check"></i>4. Calculate Hanski’s index Si with source patch parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Week8.html"><a href="Week8.html"><i class="fa fa-check"></i><b>11</b> Week 8: Simulation Experiments</a>
<ul>
<li class="chapter" data-level="11.1" data-path="video_8.html"><a href="video_8.html"><i class="fa fa-check"></i><b>11.1</b> View Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video_8.html"><a href="video_8.html#embedded-video-7"><i class="fa fa-check"></i>1. Embedded Video</a></li>
<li class="chapter" data-level="" data-path="video_8.html"><a href="video_8.html#video-part-1-4"><i class="fa fa-check"></i>Video, Part 1</a></li>
<li class="chapter" data-level="" data-path="video_8.html"><a href="video_8.html#video-part-2-4"><i class="fa fa-check"></i>Video, Part 2</a></li>
<li class="chapter" data-level="" data-path="video_8.html"><a href="video_8.html#preview-slides-7"><i class="fa fa-check"></i>Preview Slides</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="tutorial_8.html"><a href="tutorial_8.html"><i class="fa fa-check"></i><b>11.2</b> Interactive Tutorial 8</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial_8.html"><a href="tutorial_8.html#list-of-r-commands-covered-this-week-7"><i class="fa fa-check"></i>1. List of R commands covered this week</a></li>
<li class="chapter" data-level="" data-path="tutorial_8.html"><a href="tutorial_8.html#general-instructions-7"><i class="fa fa-check"></i>2. General Instructions</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="WE_8.html"><a href="WE_8.html"><i class="fa fa-check"></i><b>11.3</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_8.html"><a href="WE_8.html#overview-of-worked-example-7"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_8.html"><a href="WE_8.html#initialize-a-landscape"><i class="fa fa-check"></i>2. Initialize a landscape</a></li>
<li class="chapter" data-level="" data-path="WE_8.html"><a href="WE_8.html#define-simulation-parameters"><i class="fa fa-check"></i>3. Define simulation parameters</a></li>
<li class="chapter" data-level="" data-path="WE_8.html"><a href="WE_8.html#run-simulations-and-analyze-results"><i class="fa fa-check"></i>4. Run simulations and analyze results</a></li>
<li class="chapter" data-level="" data-path="WE_8.html"><a href="WE_8.html#run-simulator-using-a-previously-defined-parameter-set"><i class="fa fa-check"></i>5. Run simulator using a previously defined parameter set</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-8.html"><a href="r-exercise-week-8.html"><i class="fa fa-check"></i>R Exercise Week 8</a></li>
<li class="chapter" data-level="11.4" data-path="bonus_8a.html"><a href="bonus_8a.html"><i class="fa fa-check"></i><b>11.4</b> Bonus: Efficient R</a></li>
</ul></li>
<li class="part"><span><b>Advanced Topics</b></span></li>
<li class="chapter" data-level="12" data-path="Week9.html"><a href="Week9.html"><i class="fa fa-check"></i><b>12</b> Week 9: Population Structure</a>
<ul>
<li class="chapter" data-level="12.1" data-path="WE_9.html"><a href="WE_9.html"><i class="fa fa-check"></i><b>12.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_9.html"><a href="WE_9.html#overview-of-worked-example-8"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_9.html"><a href="WE_9.html#simulated-data-2-island-model"><i class="fa fa-check"></i>2. Simulated data: 2-island model</a></li>
<li class="chapter" data-level="" data-path="WE_9.html"><a href="WE_9.html#simulated-data-2-island-model-with-admixture"><i class="fa fa-check"></i>3. Simulated data: 2-island model with admixture</a></li>
<li class="chapter" data-level="" data-path="WE_9.html"><a href="WE_9.html#empirical-data-threespine-sticklebacks"><i class="fa fa-check"></i>4. Empirical data: Threespine sticklebacks</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Week10.html"><a href="Week10.html"><i class="fa fa-check"></i><b>13</b> Week 10: Landscape Resistance</a>
<ul>
<li class="chapter" data-level="13.1" data-path="WE_10.html"><a href="WE_10.html"><i class="fa fa-check"></i><b>13.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#overview-of-worked-example-9"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#explore-the-data-set"><i class="fa fa-check"></i>2. Explore the data set</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#setting-cost-values-and-calculating-conductance"><i class="fa fa-check"></i>3. Setting cost values and calculating conductance</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#convert-conductance-into-effective-distance"><i class="fa fa-check"></i>4. Convert conductance into effective distance</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#create-cost-distance-matrices"><i class="fa fa-check"></i>5. Create cost-distance matrices</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#how-does-changing-resolution-affect-these-metrics"><i class="fa fa-check"></i>6. How does changing resolution affect these metrics?</a></li>
<li class="chapter" data-level="" data-path="WE_10.html"><a href="WE_10.html#references"><i class="fa fa-check"></i>7. References</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="bonus-10a.html"><a href="bonus-10a.html"><i class="fa fa-check"></i><b>13.2</b> Bonus: ‘radish’ tutorial</a>
<ul>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#overview-of-bonus-materials-1"><i class="fa fa-check"></i>1. Overview of Bonus Materials</a></li>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#import-data"><i class="fa fa-check"></i>2. Import data</a></li>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#basic-model-fitting"><i class="fa fa-check"></i>3. Basic model fitting</a></li>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#advanced-modeling-topics"><i class="fa fa-check"></i>4. Advanced modeling topics</a></li>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#summary"><i class="fa fa-check"></i>5. Summary</a></li>
<li class="chapter" data-level="" data-path="bonus-10a.html"><a href="bonus-10a.html#references-1"><i class="fa fa-check"></i>6. References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="Week11.html"><a href="Week11.html"><i class="fa fa-check"></i><b>14</b> Week 11: Detecting Adaptation</a>
<ul>
<li class="chapter" data-level="14.1" data-path="WE_11.html"><a href="WE_11.html"><i class="fa fa-check"></i><b>14.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#overview-of-worked-example-10"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#import-and-prepare-the-data"><i class="fa fa-check"></i>2. Import and prepare the data</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#latent-factor-mixed-models-lfmm-a-univariate-gea"><i class="fa fa-check"></i>3. Latent Factor Mixed Models (LFMM): a univariate GEA</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#redundancy-analysis-rda-a-multivariate-gea"><i class="fa fa-check"></i>4. Redundancy Analysis (RDA): a multivariate GEA</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#compare-lfmm-and-rda-candidates"><i class="fa fa-check"></i>5. Compare LFMM and RDA candidates</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#a-quick-note-on-controlling-for-population-structure-in-rda"><i class="fa fa-check"></i>6. A quick note on controlling for population structure in RDA</a></li>
<li class="chapter" data-level="" data-path="WE_11.html"><a href="WE_11.html#references-2"><i class="fa fa-check"></i>7. References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="Week12.html"><a href="Week12.html"><i class="fa fa-check"></i><b>15</b> Week 12: Model Selection</a>
<ul>
<li class="chapter" data-level="15.1" data-path="WE_12.html"><a href="WE_12.html"><i class="fa fa-check"></i><b>15.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_12.html"><a href="WE_12.html#overview-of-worked-example-11"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_12.html"><a href="WE_12.html#fitting-candidate-models"><i class="fa fa-check"></i>2. Fitting candidate models</a></li>
<li class="chapter" data-level="" data-path="WE_12.html"><a href="WE_12.html#your-turn-to-test-additional-hypotheses"><i class="fa fa-check"></i>3. Your turn to test additional hypotheses!</a></li>
<li class="chapter" data-level="" data-path="WE_12.html"><a href="WE_12.html#nested-model-nmlpe-for-hierarchical-sampling-designs"><i class="fa fa-check"></i>4. Nested model (NMLPE) for hierarchical sampling designs</a></li>
<li class="chapter" data-level="" data-path="WE_12.html"><a href="WE_12.html#references-3"><i class="fa fa-check"></i>5. References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="Week13.html"><a href="Week13.html"><i class="fa fa-check"></i><b>16</b> Week 13: Gravity Models</a>
<ul>
<li class="chapter" data-level="16.1" data-path="WE_13.html"><a href="WE_13.html"><i class="fa fa-check"></i><b>16.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#overview-of-worked-example-12"><i class="fa fa-check"></i>1. Overview of Worked Example</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#setup"><i class="fa fa-check"></i>2. Setup</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#wetland-complex-data-preparation"><i class="fa fa-check"></i>3. Wetland complex data preparation</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#wetland-field-data-preparation"><i class="fa fa-check"></i>4. Wetland field-data preparation</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#saturated-graph"><i class="fa fa-check"></i>5. Saturated Graph</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#spatial-model-data-prepration"><i class="fa fa-check"></i>6. Spatial model data prepration</a></li>
<li class="chapter" data-level="" data-path="WE_13.html"><a href="WE_13.html#gravity-model"><i class="fa fa-check"></i>7. Gravity model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="Week14.html"><a href="Week14.html"><i class="fa fa-check"></i><b>17</b> Week 14: Contemporary Gene Flow</a>
<ul>
<li class="chapter" data-level="17.1" data-path="WE_14.html"><a href="WE_14.html"><i class="fa fa-check"></i><b>17.1</b> Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#overview-3"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#import-genotypes"><i class="fa fa-check"></i>2. Import Genotypes</a></li>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#pollen-pool-genetic-structure"><i class="fa fa-check"></i>3. Pollen pool genetic structure</a></li>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#paternity-analysis"><i class="fa fa-check"></i>4. Paternity analysis</a></li>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#linking-paternity-to-ecological-variables"><i class="fa fa-check"></i>5. Linking paternity to ecological variables</a></li>
<li class="chapter" data-level="" data-path="WE_14.html"><a href="WE_14.html#references-4"><i class="fa fa-check"></i>6. References</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Landscape Genetic Data Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-r" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Basic R Programming<a href="basic-r.html#basic-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Rodney Dyer (worked example) and Helene Wagner (adaptation)</p>
<div id="overview" class="section level3 unnumbered hasAnchor">
<h3>1. Overview<a href="basic-r.html#overview" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This worked example is adapted from “Applied Population Genetics” by Rodney Dyer. The entire book is available here: <a href="http://dyerlab.github.io/applied_population_genetics/index.html" class="uri">http://dyerlab.github.io/applied_population_genetics/index.html</a></p>
<p>R is a statistical programming language, and it thus requires users to work with code. This can be intimidating at first. Working through this document will help you get up to speed with basic R concepts and notation. Whether you are new to R or need a refresher, this worked example will get you to the level expected for the ‘Landscape Genetics with R’ lab course. The main topics covered here are:</p>
<ul>
<li>R data types (how data are stored in R: numeric, character, etc.)</li>
<li>R containers (how data are organized: vectors, data frames, etc.)</li>
<li>R functions (how to tell R what to do)</li>
</ul>
<p>See also video “Week 0: Intro to R Notebooks” for options how to work this this document as .html or .Rmd.</p>
<p>Install packages needed for this worked example. Note: <code>popgraph</code> needs to be installed before installing <code>gstudio</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="basic-r.html#cb2-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;popgraph&quot;</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>))</span>
<span id="cb2-2"><a href="basic-r.html#cb2-2" tabindex="-1"></a>{</span>
<span id="cb2-3"><a href="basic-r.html#cb2-3" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">&quot;RgoogleMaps&quot;</span>, <span class="st">&quot;geosphere&quot;</span>, <span class="st">&quot;proto&quot;</span>, <span class="st">&quot;sampling&quot;</span>, </span>
<span id="cb2-4"><a href="basic-r.html#cb2-4" tabindex="-1"></a>                      <span class="st">&quot;seqinr&quot;</span>, <span class="st">&quot;spacetime&quot;</span>, <span class="st">&quot;spdep&quot;</span>), <span class="at">dependencies=</span><span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="basic-r.html#cb2-5" tabindex="-1"></a>  remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;dyerlab/popgraph&quot;</span>)</span>
<span id="cb2-6"><a href="basic-r.html#cb2-6" tabindex="-1"></a>}</span>
<span id="cb2-7"><a href="basic-r.html#cb2-7" tabindex="-1"></a>  </span>
<span id="cb2-8"><a href="basic-r.html#cb2-8" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;gstudio&quot;</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;dyerlab/gstudio&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: replacing previous import &#39;dplyr::union&#39; by &#39;raster::union&#39; when
## loading &#39;gstudio&#39;</code></pre>
<pre><code>## Warning: replacing previous import &#39;dplyr::intersect&#39; by &#39;raster::intersect&#39;
## when loading &#39;gstudio&#39;</code></pre>
<pre><code>## Warning: replacing previous import &#39;dplyr::select&#39; by &#39;raster::select&#39; when
## loading &#39;gstudio&#39;</code></pre>
</div>
<div id="data-types" class="section level3 unnumbered hasAnchor">
<h3>2. Data Types<a href="basic-r.html#data-types" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data we work with comes in many forms—integers, stratum, categories, genotypes, etc.—all of which we need to be able to work with in our analyses. In this chapter, the basic data types we will commonly use in population genetic analyses. This section covers some of the basic types of data we will use in R. These include numbers, character, factors, and logical data types. We will also introduce the locus object from the gstudio library and see how it is just another data type that we can manipulate in R.</p>
<p>The very first hurdle you need to get over is the oddness in the way in which R assigns values to variables.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="basic-r.html#cb6-1" tabindex="-1"></a>variable <span class="ot">&lt;-</span> value</span></code></pre></div>
<p>Yes that is a less-than and dash character. This is the assignment operator that historically has been used and it is the one that I will stick with. In some cases you can use the ‘=’ to assign variables instead but then it takes away the R-ness of R itself. For decision making, the equality operator (e.g., is this equal to that) is the double equals sign ‘==’. We will get into that below where we talk about logical types and later in decision making.</p>
<p>If you are unaware of what type a particular variable may be, you can always use the <code>type()</code> function and R will tell you.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="basic-r.html#cb7-1" tabindex="-1"></a><span class="fu">class</span>( variable )</span></code></pre></div>
<p>R also has a pretty good help system built into itself. You can get help for any function by typing a question mark in front of the function name. This is a particularly awesome features because at the end of the help file, there is often examples of its usage, which are priceless. Here is the documentation for the ‘help’ function as given by:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="basic-r.html#cb8-1" tabindex="-1"></a>?help</span></code></pre></div>
<p>There are also package vignettes available (for most packages you download) that provide additional information on the routines, data sets, and other items included in these packages. You can get a list of vignettes currently installed on your machine by:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="basic-r.html#cb9-1" tabindex="-1"></a><span class="fu">vignette</span>()</span></code></pre></div>
<p>and vignettes for a particular package by passing the package name as an argument to the function itself.</p>
<div id="numeric-data-types" class="section level4 unnumbered hasAnchor">
<h4>2.1. Numeric Data Types<a href="basic-r.html#numeric-data-types" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="a.-numeric-data" class="section level5 unnumbered hasAnchor">
<h5>a. Numeric data<a href="basic-r.html#a.-numeric-data" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The quantitative measurements we make are often numeric, in that they can be represented as as a number with a decimal component (think weight, height, latitude, soil moisture, ear wax viscosity, etc.). The most basic type of data in R, is the numeric type and represents both integers and floating point numbers (n.b., there is a strict integer data type but it is often only needed when interfacing with other C libraries and can for what we are doing be disregarded).</p>
<p>Assigning a value to a variable is easy</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="basic-r.html#cb10-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb10-2"><a href="basic-r.html#cb10-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>By default, R automatically outputs whole numbers numbers within decimal values appropriately.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="basic-r.html#cb12-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">22</span><span class="sc">/</span><span class="dv">7</span></span>
<span id="cb12-2"><a href="basic-r.html#cb12-2" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] 3.142857</code></pre>
<p>If there is a mix of whole numbers and numbers with decimals together in a container such as</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="basic-r.html#cb14-1" tabindex="-1"></a><span class="fu">c</span>(x,y)</span></code></pre></div>
<pre><code>## [1] 3.000000 3.142857</code></pre>
<p>then both are shown with decimals. The <code>c()</code> part here is a function that combines several data objects together into a vector and is very useful. In fact, the use of vectors are are central to working in R and functions almost all the functions we use on individual variables can also be applied to vectors.</p>
<p>A word of caution should be made about numeric data types on any computer. Consider the following example.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="basic-r.html#cb16-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> .<span class="dv">3</span> <span class="sc">/</span> <span class="dv">3</span></span>
<span id="cb16-2"><a href="basic-r.html#cb16-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 0.1</code></pre>
<p>which is exactly what we’d expect. However, the way in which computers store decimal numbers plays off our notion of significant digits pretty well. Look what happens when I print out x but carry out the number of decimal places.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="basic-r.html#cb18-1" tabindex="-1"></a><span class="fu">print</span>(x, <span class="at">digits=</span><span class="dv">20</span>)</span></code></pre></div>
<pre><code>## [1] 0.099999999999999991673</code></pre>
<p>Not quite 0.1 is it? Not that far away from it but not exact. That is a general problem, not one that R has any more claim to than any other language and/or implementation. Does this matter much, probably not in the realm of the kinds of things we do in population genetics, it is just something that you should be aware of.
You can make random sets of numeric data by using using functions describing various distributions. For example, some random numbers from the normal distribution are:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="basic-r.html#cb20-1" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] -1.4536045  0.8214666  0.8180848 -0.4739079  0.4793438 -0.4942676
##  [7]  1.2114168 -0.2578364 -0.5980222  0.2196772</code></pre>
<p>from the normal distribution with designated mean and standard deviation:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="basic-r.html#cb22-1" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="at">mean=</span><span class="dv">42</span>,<span class="at">sd=</span><span class="dv">12</span>)</span></code></pre></div>
<pre><code>##  [1] 45.12538 49.60240 36.00652 30.63791 29.60983 42.27913 33.96392 41.09913
##  [9] 49.76500 45.32885</code></pre>
<p>A poisson distribution with mean 2:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="basic-r.html#cb24-1" tabindex="-1"></a><span class="fu">rpois</span>(<span class="dv">10</span>,<span class="at">lambda =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1] 3 2 3 4 2 1 3 3 2 3</code></pre>
<p>and the <span class="math inline">\(\chi^2\)</span> distribution with 1 degree of freedom:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="basic-r.html#cb26-1" tabindex="-1"></a><span class="fu">rchisq</span>(<span class="dv">10</span>, <span class="at">df=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>##  [1] 0.005732619 0.313665841 0.177228279 2.642739027 3.724465188 0.912656404
##  [7] 3.006614943 0.145557780 1.308283382 0.146935513</code></pre>
<p>There are several more distributions that if you need to access random numbers, quantiles, probability densities, and cumulative density values are available.</p>
</div>
<div id="b.-coercion-to-numeric" class="section level5 unnumbered hasAnchor">
<h5>b. Coercion to Numeric<a href="basic-r.html#b.-coercion-to-numeric" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>All data types have the potential ability to take another variable and coerce it into their type. Some combinations make sense, and some do not. For example, if you load in a CSV data file using read_csv(), and at some point a stray non-numeric character was inserted into one of the cells on your spreadsheet, R will interpret the entire column as a character type rather than as a numeric type. This can be a very frustrating thing, spreadsheets should generally be considered evil as they do all kinds of stuff behind the scenes and make your life less awesome.</p>
<p>Here is an example of coercion of some data that is initially defined as a set of characters</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="basic-r.html#cb28-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;42&quot;</span>,<span class="st">&quot;99&quot;</span>)</span>
<span id="cb28-2"><a href="basic-r.html#cb28-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] &quot;42&quot; &quot;99&quot;</code></pre>
<p>and is coerced into a numeric type using the as.numeric() function.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="basic-r.html#cb30-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>( x )</span>
<span id="cb30-2"><a href="basic-r.html#cb30-2" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] 42 99</code></pre>
<p>It is a built-in feature of the data types in R that they all have (or should have if someone is producing a new data type and is being courteous to their users) an <code>as.X()</code> function. This is where the data type decides if the values asked to be coerced are reasonable or if you need to be reminded that what you are asking is not possible. Here is an example where I try to coerce a non-numeric variable into a number.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="basic-r.html#cb32-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">&quot;The night is dark and full of terrors...&quot;</span></span>
<span id="cb32-2"><a href="basic-r.html#cb32-2" tabindex="-1"></a><span class="fu">as.numeric</span>( x )</span></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre><code>## [1] NA</code></pre>
<p>By default, the result should be NA (missing data/non-applicable) if you ask for things that are not possible.</p>
</div>
</div>
<div id="characters" class="section level4 unnumbered hasAnchor">
<h4>2.2. Characters<a href="basic-r.html#characters" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="a.-character-data" class="section level5 unnumbered hasAnchor">
<h5>a. Character data<a href="basic-r.html#a.-character-data" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>A collection of letters, number, and or punctuation is represented as a character data type. These are enclosed in either single or double quotes and are considered a single entity. For example, my name can be represented as:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="basic-r.html#cb35-1" tabindex="-1"></a>prof <span class="ot">&lt;-</span> <span class="st">&quot;Rodney J. Dyer&quot;</span></span>
<span id="cb35-2"><a href="basic-r.html#cb35-2" tabindex="-1"></a>prof</span></code></pre></div>
<pre><code>## [1] &quot;Rodney J. Dyer&quot;</code></pre>
<p>In R, character variables are considered to be a single entity, that is the entire prof variable is a single unit, not a collection of characters. This is in part due to the way in which vectors of variables are constructed in the language. For example, if you are looking at the length of the variable I assigned my name to you see</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="basic-r.html#cb37-1" tabindex="-1"></a><span class="fu">length</span>(prof)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>which shows that there is only one ‘character’ variable. If, as is often the case, you are interested in knowing how many characters are in the variable prof, then you use the</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="basic-r.html#cb39-1" tabindex="-1"></a><span class="fu">nchar</span>(prof)</span></code></pre></div>
<pre><code>## [1] 14</code></pre>
<p>function instead. This returns the number of characters (even the non-printing ones like tabs and spaces.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="basic-r.html#cb41-1" tabindex="-1"></a><span class="fu">nchar</span>(<span class="st">&quot; </span><span class="sc">\t</span><span class="st"> &quot;</span>)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>As all other data types, you can define a vector of character values using the <code>c()</code> function.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="basic-r.html#cb43-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">&quot;I am&quot;</span></span>
<span id="cb43-2"><a href="basic-r.html#cb43-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="st">&quot;not&quot;</span></span>
<span id="cb43-3"><a href="basic-r.html#cb43-3" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="st">&#39;a looser&#39;</span></span>
<span id="cb43-4"><a href="basic-r.html#cb43-4" tabindex="-1"></a>terms <span class="ot">&lt;-</span> <span class="fu">c</span>(x,y,z)</span>
<span id="cb43-5"><a href="basic-r.html#cb43-5" tabindex="-1"></a>terms</span></code></pre></div>
<pre><code>## [1] &quot;I am&quot;     &quot;not&quot;      &quot;a looser&quot;</code></pre>
<p>And looking at the <code>length()</code> and <code>nchar()</code> of this you can see how these operations differ.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="basic-r.html#cb45-1" tabindex="-1"></a><span class="fu">length</span>(terms)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="basic-r.html#cb47-1" tabindex="-1"></a><span class="fu">nchar</span>(terms)</span></code></pre></div>
<pre><code>## [1] 4 3 8</code></pre>
</div>
<div id="b.-concatenation-of-characters" class="section level5 unnumbered hasAnchor">
<h5>b. Concatenation of Characters<a href="basic-r.html#b.-concatenation-of-characters" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Another common use of characters is concatenating them into single sequences. Here we use the function <code>paste()</code> and can set the separators (or characters that are inserted between entities when we collapse vectors). Here is an example, entirely fictional and only provided for instructional purposes only.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="basic-r.html#cb49-1" tabindex="-1"></a><span class="fu">paste</span>(terms, <span class="at">collapse=</span><span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="basic-r.html#cb51-1" tabindex="-1"></a><span class="fu">paste</span>(x,z)</span></code></pre></div>
<pre><code>## [1] &quot;I am a looser&quot;</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="basic-r.html#cb53-1" tabindex="-1"></a><span class="fu">paste</span>(x,z,<span class="at">sep=</span><span class="st">&quot; not &quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
</div>
<div id="c.-coercion-to-characters" class="section level5 unnumbered hasAnchor">
<h5>c. Coercion to Characters<a href="basic-r.html#c.-coercion-to-characters" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>A character data type is often the most basal type of data you can work with. For example, consider the case where you have named sample locations. These can be kept as a character data type or as a factor (see below). There are benefits and drawbacks to each representation of the same data (see below). By default (as of the version of R I am currently using when writing this book), if you use a function like read_table() to load in an external file, columns of character data will be treated as factors. This can be good behavior if all you are doing is loading in data and running an analysis, or it can be a total pain in the backside if you are doing more manipulative analyses.</p>
<p>Here is an example of coercing a numeric type into a character type using the <code>as.character()</code> function.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="basic-r.html#cb55-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb55-2"><a href="basic-r.html#cb55-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="basic-r.html#cb57-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">as.character</span>(x)</span>
<span id="cb57-2"><a href="basic-r.html#cb57-2" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] &quot;42&quot;</code></pre>
</div>
</div>
<div id="factors" class="section level4 unnumbered hasAnchor">
<h4>2.3. Factors<a href="basic-r.html#factors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="a.-factor-vs.-character" class="section level5 unnumbered hasAnchor">
<h5>a. Factor vs. Character<a href="basic-r.html#a.-factor-vs.-character" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>A factor is a categorical data type. If you are coming from SAS, these are class variables. If you are not, then perhaps you can think of them as mutually exclusive classifications. For example, an sample may be assigned to one particular locale, one particular region, and one particular species. Across all the data you may have several species, regions, and locales. These are finite, and defined, sets of categories. One of the more common headaches encountered by people new to R is working with factor types and trying to add categories that are not already defined.</p>
<p>Since factors are categorical, it is in your best interest to make sure you label them in as descriptive as a fashion as possible. You are not saving space or cutting down on computational time to take shortcuts and label the locale for Rancho Santa Maria as RSN or pop3d or 5. Our computers are fast and large enough, and our programmers are cleaver enough, to not have to rename our populations in numeric format to make them work (hello STRUCTURE I’m calling you out here). The only thing you have to loose by adopting a reasonable naming scheme is confusion in your output.</p>
<p>To define a factor type, you use the function <code>factor()</code> and pass it a vector of values.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="basic-r.html#cb59-1" tabindex="-1"></a>region <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;North&quot;</span>,<span class="st">&quot;North&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;West&quot;</span>)</span>
<span id="cb59-2"><a href="basic-r.html#cb59-2" tabindex="-1"></a>region <span class="ot">&lt;-</span> <span class="fu">factor</span>( region )</span>
<span id="cb59-3"><a href="basic-r.html#cb59-3" tabindex="-1"></a>region</span></code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: East North South West</code></pre>
<p>When you print out the values, it shows you all the levels present for the factor. If you have levels that are not present in your data set, when you define it, you can tell R to consider additional levels of this factor by passing the optional levels= argument as:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="basic-r.html#cb61-1" tabindex="-1"></a>region <span class="ot">&lt;-</span> <span class="fu">factor</span>( region, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;North&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;Central&quot;</span>))</span>
<span id="cb61-2"><a href="basic-r.html#cb61-2" tabindex="-1"></a>region</span></code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: North South East West Central</code></pre>
<p>If you try to add a data point to a factor list that does not have the factor that you are adding, it will give you an error (or ‘barf’ as I like to say).</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="basic-r.html#cb63-1" tabindex="-1"></a>region[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Bob&quot;</span></span></code></pre></div>
<pre><code>## Warning in `[&lt;-.factor`(`*tmp*`, 1, value = &quot;Bob&quot;): invalid factor level, NA
## generated</code></pre>
<p>Now, I have to admit that the Error message in its entirety, with its <code>“[&lt;-.factor</code>(<code>*tmp*</code>, 1, value = “Bob”)“` part is, perhaps, not the most informative. Agreed. However, the “invalid factor level” does tell you something useful. Unfortunately, the programmers that put in the error handling system in R did not quite adhere to the spirit of the “fail loudly” mantra. It is something you will have to get good at. Google is your friend, and if you post a questions to (<a href="http://stackoverflow.org" class="uri">http://stackoverflow.org</a>) or the R user list without doing serious homework, put on your asbestos shorts!</p>
<p>Unfortunately, the error above changed the first element of the region vector to NA (missing data). I’ll turn it back before we move too much further.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="basic-r.html#cb65-1" tabindex="-1"></a>region[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">&quot;North&quot;</span></span></code></pre></div>
<p>Factors in R can be either unordered (as say locale may be since locale A is not <code>&gt;</code>, <code>=</code>, or <code>&lt;</code> locale B) or they may be ordered categories as in <code>Small &lt; Medium &lt; Large &lt; X-Large</code>. When you create the factor, you need to indicate if it is an ordered type (by default it is not). If the factors are ordered in some way, you can also create an ordination on the data. If you do not pass a levels= option to the <code>factors()</code> function, it will take the order in which they occur in data you pass to it. If you want to specify an order for the factors specifically, pass the optional <code>levels=</code> and they will be ordinated in the order given there.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="basic-r.html#cb66-1" tabindex="-1"></a>region <span class="ot">&lt;-</span> <span class="fu">factor</span>( region, <span class="at">ordered=</span><span class="cn">TRUE</span>, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;West&quot;</span>, <span class="st">&quot;North&quot;</span>, <span class="st">&quot;South&quot;</span>, <span class="st">&quot;East&quot;</span>) )</span>
<span id="cb66-2"><a href="basic-r.html#cb66-2" tabindex="-1"></a>region</span></code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
</div>
<div id="b.-missing-levels-in-factors" class="section level5 unnumbered hasAnchor">
<h5>b. Missing Levels in Factors<a href="basic-r.html#b.-missing-levels-in-factors" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>There are times when you have a subset of data that do not have all the potential categories.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="basic-r.html#cb68-1" tabindex="-1"></a>subregion <span class="ot">&lt;-</span> region[ <span class="dv">3</span><span class="sc">:</span><span class="dv">9</span> ]</span>
<span id="cb68-2"><a href="basic-r.html#cb68-2" tabindex="-1"></a>subregion</span></code></pre></div>
<pre><code>## [1] South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="basic-r.html#cb70-1" tabindex="-1"></a><span class="fu">table</span>( subregion )</span></code></pre></div>
<pre><code>## subregion
##  West North South  East 
##     3     0     2     2</code></pre>
</div>
</div>
<div id="logical-types" class="section level4 unnumbered hasAnchor">
<h4>2.4. Logical Types<a href="basic-r.html#logical-types" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A logical type is either TRUE or FALSE, there is no in-between. It is common to use these types in making decisions (see if-else decisions) to check a specific condition being satisfied. To define logical variables you can either use the TRUE or FALSE directly</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="basic-r.html#cb72-1" tabindex="-1"></a>canThrow <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb72-2"><a href="basic-r.html#cb72-2" tabindex="-1"></a>canThrow</span></code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE FALSE FALSE</code></pre>
<p>or can implement some logical condition</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="basic-r.html#cb74-1" tabindex="-1"></a>stable <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">&quot;RGIII&quot;</span> <span class="sc">==</span> <span class="dv">0</span>, <span class="fu">nchar</span>(<span class="st">&quot;Marshawn&quot;</span>) <span class="sc">==</span> <span class="dv">8</span>)</span>
<span id="cb74-2"><a href="basic-r.html#cb74-2" tabindex="-1"></a>stable</span></code></pre></div>
<pre><code>## [1] FALSE  TRUE</code></pre>
<p>on the variables. Notice here how each of the items is actually evaluated as to determine the truth of each expression. In the first case, the character is not equal to zero and in the second, the number of characters (what <code>nchar()</code> does) is indeed equal to 8 for the character string “Marshawn”.</p>
<p>It is common to use logical types to serve as indices for vectors. Say for example, you have a vector of data that you want to select some subset from.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="basic-r.html#cb76-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">20</span>)</span>
<span id="cb76-2"><a href="basic-r.html#cb76-2" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##  [1] -1.24817464  1.41759325 -1.55245434 -0.76435741 -0.21367202  0.80792427
##  [7] -0.16317123 -2.51914574  0.45488117  0.65176826  1.26707634 -1.28207154
## [13] -0.84972286  1.21481639  0.80761489 -0.07055671  0.11816398  0.86460699
## [19]  0.70392130  0.65619901</code></pre>
<p>Perhaps you are on interested in the non-negative values</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="basic-r.html#cb78-1" tabindex="-1"></a>data[ data <span class="sc">&gt;</span> <span class="dv">0</span> ]</span></code></pre></div>
<pre><code>##  [1] 1.4175932 0.8079243 0.4548812 0.6517683 1.2670763 1.2148164 0.8076149
##  [8] 0.1181640 0.8646070 0.7039213 0.6561990</code></pre>
<p>If you look at the condition being passed to as the index</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="basic-r.html#cb80-1" tabindex="-1"></a>data <span class="sc">&gt;</span> <span class="dv">0</span></span></code></pre></div>
<pre><code>##  [1] FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE
## [13] FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE</code></pre>
<p>you see that individually, each value in the data vector is being evaluated as a logical value, satisfying the condition that it is strictly greater than zero. When you pass that as indices to a vector it only shows the indices that are <code>TRUE</code>.</p>
<p>You can coerce a value into a logical if you understand the rules. Numeric types that equal 0 (zero) are <code>FALSE</code>, always. Any non-zero value is considered <code>TRUE</code>. Here I use the modulus operator, <code>%%</code>, which provides the remainder of a division.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="basic-r.html#cb82-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">:</span><span class="dv">20</span> <span class="sc">%%</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0</code></pre>
<p>which used as indices give us</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="basic-r.html#cb84-1" tabindex="-1"></a>data[ (<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span> <span class="sc">%%</span> <span class="dv">2</span>) <span class="sc">&gt;</span> <span class="dv">0</span> ]</span></code></pre></div>
<pre><code>##  [1] -1.2481746 -1.5524543 -0.2136720 -0.1631712  0.4548812  1.2670763
##  [7] -0.8497229  0.8076149  0.1181640  0.7039213</code></pre>
<p>You can get as complicated in the creation of indices as you like, even using logical operators such as OR and AND. I leave that as an example for you to play with.</p>
</div>
</div>
<div id="data-containers" class="section level3 unnumbered hasAnchor">
<h3>3. Data Containers<a href="basic-r.html#data-containers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We almost never work with a single datum<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>, rather we keep lots of data. Moreover, the kinds of data are often heterogeneous, including categorical (Populations, Regions), continuous (coordinates, rainfall, elevation), imagry (hyperspectral, LiDAR), and perhaps even genetic. R has a very rich set of containers into which we can stuff our data as we work with it. Here these container types are examined and the restrictions and benefits associated with each type are explained.</p>
<div id="vectors" class="section level4 unnumbered hasAnchor">
<h4>3.1. Vectors<a href="basic-r.html#vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have already seen several examples of several vectors in action (see the introduction to Numeric data types for example). A vector of objects is simply a collection of them, often created using the <code>c()</code> function (<em>c</em> for combine). Vectorized data is restricted to having homogeneous data types—you cannot mix character and numeric types in the same vector. If you try to mix types, R will either coerce your data into a reasonable type</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="basic-r.html#cb86-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb86-2"><a href="basic-r.html#cb86-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="basic-r.html#cb88-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>,<span class="cn">TRUE</span>,<span class="cn">FALSE</span>)</span>
<span id="cb88-2"><a href="basic-r.html#cb88-2" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="basic-r.html#cb90-1" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;I&quot;</span>,<span class="st">&quot;am&quot;</span>,<span class="st">&quot;not&quot;</span>,<span class="st">&quot;a&quot;</span>,<span class="st">&quot;looser&quot;</span>)</span>
<span id="cb90-2"><a href="basic-r.html#cb90-2" tabindex="-1"></a>z</span></code></pre></div>
<pre><code>## [1] &quot;I&quot;      &quot;am&quot;     &quot;not&quot;    &quot;a&quot;      &quot;looser&quot;</code></pre>
<p>or coearce them into one type that is amenable to all the types of data that you have given it. In this example, a Logical, Character, Constant, and Function are combined resulting in a vector output of type Character.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="basic-r.html#cb92-1" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="st">&quot;1&quot;</span>, pi, <span class="fu">ls</span>())</span>
<span id="cb92-2"><a href="basic-r.html#cb92-2" tabindex="-1"></a>w</span></code></pre></div>
<pre><code>##  [1] &quot;TRUE&quot;             &quot;1&quot;                &quot;3.14159265358979&quot; &quot;canThrow&quot;        
##  [5] &quot;data&quot;             &quot;prof&quot;             &quot;region&quot;           &quot;rmd_file&quot;        
##  [9] &quot;stable&quot;           &quot;subregion&quot;        &quot;terms&quot;            &quot;x&quot;               
## [13] &quot;y&quot;                &quot;yml_metadata&quot;     &quot;z&quot;</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="basic-r.html#cb94-1" tabindex="-1"></a><span class="fu">class</span>(w)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Accessing elements within a vector are done using the square bracket <code>[]</code> notation. All indices (for vectors and matrices) start at 1 (not zero as is the case for some languages). Getting and setting the components within a vector are accomplished using numeric indices with the assignment operators just like we do for variables containing a single value.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="basic-r.html#cb96-1" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="basic-r.html#cb98-1" tabindex="-1"></a>x[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb98-2"><a href="basic-r.html#cb98-2" tabindex="-1"></a>x[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb98-3"><a href="basic-r.html#cb98-3" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 2 2 1</code></pre>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="basic-r.html#cb100-1" tabindex="-1"></a>x[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>A common type of vector is that of a sequences. We use sequences all the time, to iterate through a list, to counting generations, etc. There are a few ways to generate sequences, depending upon the step sequence. For a sequence of whole numbers, the easiest is through the use of the colon operator.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="basic-r.html#cb102-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span></span>
<span id="cb102-2"><a href="basic-r.html#cb102-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>This provides a nice shorthand for getting the values X:Y from X to Y, inclusive. It is also possible to go backwards using this operator, counting down from X to Y as in:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="basic-r.html#cb104-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">:</span><span class="dv">2</span></span>
<span id="cb104-2"><a href="basic-r.html#cb104-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 5 4 3 2</code></pre>
<p>The only constraint here is that we are limited to a step size of 1.0. It is possible to use non-integers as the bounds, it will just count up by 1.0 each time.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="basic-r.html#cb106-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fl">3.2</span><span class="sc">:</span><span class="fl">8.4</span></span>
<span id="cb106-2"><a href="basic-r.html#cb106-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 3.2 4.2 5.2 6.2 7.2 8.2</code></pre>
<p>If you are interested in making a sequence with a step other than 1.0, you can use the <code>seq()</code> function. If you do not provide a step value, it defaults to 1.0.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="basic-r.html#cb108-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">6</span>)</span>
<span id="cb108-2"><a href="basic-r.html#cb108-2" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>But if you do, it will use that instead.</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="basic-r.html#cb110-1" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="at">by=</span><span class="dv">2</span>)</span>
<span id="cb110-2"><a href="basic-r.html#cb110-2" tabindex="-1"></a>z</span></code></pre></div>
<pre><code>##  [1]  1  3  5  7  9 11 13 15 17 19</code></pre>
<p>It is also possible to create a vector of objects as repetitions using the <code>rep()</code> (for repeat) function.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="basic-r.html#cb112-1" tabindex="-1"></a><span class="fu">rep</span>(<span class="st">&quot;Beetlejuice&quot;</span>,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Beetlejuice&quot; &quot;Beetlejuice&quot; &quot;Beetlejuice&quot;</code></pre>
<p>If you pass a vector of items to <code>rep()</code>, it can repeat these as either a vector being repeated (the default value)</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="basic-r.html#cb114-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>,<span class="st">&quot;Free&quot;</span>,<span class="st">&quot;Lunch&quot;</span>)</span>
<span id="cb114-2"><a href="basic-r.html#cb114-2" tabindex="-1"></a><span class="fu">rep</span>(x,<span class="at">time=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot;</code></pre>
<p>or as each item in the vector repeated.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="basic-r.html#cb116-1" tabindex="-1"></a><span class="fu">rep</span>(x,<span class="at">each=</span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] &quot;No&quot;    &quot;No&quot;    &quot;No&quot;    &quot;Free&quot;  &quot;Free&quot;  &quot;Free&quot;  &quot;Lunch&quot; &quot;Lunch&quot; &quot;Lunch&quot;</code></pre>
</div>
<div id="matrices" class="section level4 unnumbered hasAnchor">
<h4>3.2. Matrices<a href="basic-r.html#matrices" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A matrix is a 2- or higher dimensional container, most commonly used to store numeric data types. There are some libraries that use matrices in more than two dimensions (rows and columns and sheets), though you will not run across them too often. Here I restrict myself to only 2-dimensional matrices.</p>
<p>You can define a matrix by giving it a set of values and an indication of the number of rows and columns you want. The easiest matrix to try is one with empty values:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="basic-r.html#cb118-1" tabindex="-1"></a><span class="fu">matrix</span>(<span class="at">nrow=</span><span class="dv">2</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   NA   NA
## [2,]   NA   NA</code></pre>
<p>Perhaps more useful is one that is pre-populated with values.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="basic-r.html#cb120-1" tabindex="-1"></a><span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">nrow=</span><span class="dv">2</span> )</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4</code></pre>
<p>Notice that here, there were four entries and I only specified the number of rows required. By default the ‘filling-in’ of the matrix will proceed down column (<em>by-column</em>). In this example, we have the first column with the first two entries and the last two entries down the second column. If you want it to fill by row, you can pass the optional argument</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="basic-r.html#cb122-1" tabindex="-1"></a><span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4</code></pre>
<p>and it will fill <em>by-row</em>.</p>
<p>When filling matrices, the default size and the size of the data being added to the matrix are critical. For example, I can create a matrix as:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="basic-r.html#cb124-1" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="at">ncol=</span><span class="dv">2</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb124-2"><a href="basic-r.html#cb124-2" tabindex="-1"></a>Y</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4
## [3,]    5    6</code></pre>
<p>or</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="basic-r.html#cb126-1" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="at">nrow=</span><span class="dv">2</span>)</span>
<span id="cb126-2"><a href="basic-r.html#cb126-2" tabindex="-1"></a>X</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<p>and both produce a similar matrix, only transposed.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="basic-r.html#cb128-1" tabindex="-1"></a>X <span class="sc">==</span> <span class="fu">t</span>(Y)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,] TRUE TRUE TRUE
## [2,] TRUE TRUE TRUE</code></pre>
<p>In the example above, the number of rows (or columns) was a clean multiple of the number of entries. However, if it is not, R will fill in values.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="basic-r.html#cb130-1" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="at">ncol=</span><span class="dv">4</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning in matrix(c(1, 2, 3, 4, 5, 6), ncol = 4, byrow = TRUE): data length [6]
## is not a sub-multiple or multiple of the number of columns [4]</code></pre>
<p>Notice how you get a warning from the interpreter. But that does not stop it from filling in the remaining slots by starting over in the sequence of numbers you passed to it.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="basic-r.html#cb132-1" tabindex="-1"></a>X</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    1    2</code></pre>
<p>The dimensionality of a matrix (and <code>data.frame</code> as we will see shortly) is returned by the <code>dim()</code> function. This will provide the number of rows and columns as a vector.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="basic-r.html#cb134-1" tabindex="-1"></a><span class="fu">dim</span>(X)</span></code></pre></div>
<pre><code>## [1] 2 4</code></pre>
<p>Accessing elements to retrieve or set their values within a matrix is done using the square brackets just like for a vector but you need to give <code>[row,col]</code> indices. Again, these are 1-based so that</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="basic-r.html#cb136-1" tabindex="-1"></a>X[<span class="dv">1</span>,<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>is the entry in the 1st row and 3rd column.</p>
<p>You can also use ‘slices’ through a matrix to get the rows</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="basic-r.html#cb138-1" tabindex="-1"></a>X[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>## [1] 1 2 3 4</code></pre>
<p>or columns</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="basic-r.html#cb140-1" tabindex="-1"></a>X[,<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 3 1</code></pre>
<p>of data. Here you just omit the index for the entity you want to span. Notice that when you grab a slice, even if it is a column, is given as a vector.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="basic-r.html#cb142-1" tabindex="-1"></a><span class="fu">length</span>(X[,<span class="dv">3</span>])</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>You can grab a sub-matrix using slices if you give a range (or sequence) of indices.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="basic-r.html#cb144-1" tabindex="-1"></a>X[,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    2    3
## [2,]    6    1</code></pre>
<p>If you ask for values from a matrix that exceed its dimensions, R will give you an error.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="basic-r.html#cb146-1" tabindex="-1"></a>X[<span class="dv">1</span>,<span class="dv">8</span>]</span></code></pre></div>
<pre><code>## Error in X[1, 8] : subscript out of bounds
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>There are a few cool extensions of the <code>rep()</code> function that can be used to create matrices as well. They are optional values that can be passed to the function.</p>
<ul>
<li><code>times=x</code>: This is the default option that was occupied by the ‘3’ in the example above and represents the number of times that first argument will be repeated.<br />
</li>
<li><code>each=x</code> This will take each element in the first argument are repeat them <code>each</code> times.<br />
</li>
<li><code>length.out=x</code>: This make the result equal in length to <code>x</code>.</li>
</ul>
<p>In combination, these can be quite helpful. Here is an example using numeric sequences in which it is necessary to find the index of all entries in a 3x2 matrix. To make the indices, I bind two columns together using <code>cbind()</code>. There is a matching row binding function, denoted as <code>rbind()</code> (perhaps not so surprisingly). What is returned is a matrix</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="basic-r.html#cb148-1" tabindex="-1"></a>indices <span class="ot">&lt;-</span> <span class="fu">cbind</span>( <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">each=</span><span class="dv">3</span>), <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="at">times=</span><span class="dv">2</span>), <span class="fu">rep</span>(<span class="dv">5</span>,<span class="at">length.out=</span><span class="dv">6</span>)  )</span>
<span id="cb148-2"><a href="basic-r.html#cb148-2" tabindex="-1"></a>indices</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1    5
## [2,]    1    2    5
## [3,]    1    3    5
## [4,]    2    1    5
## [5,]    2    2    5
## [6,]    2    3    5</code></pre>
</div>
<div id="lists" class="section level4 unnumbered hasAnchor">
<h4>3.3. Lists<a href="basic-r.html#lists" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A list is a type of vector but is indexed by ‘keys’ rather than by numeric indices. Moreover, lists can contain heterogeneous types of data (e.g., values of different <code>class</code>), which is not possible in a vector type. For example, consider the list</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="basic-r.html#cb150-1" tabindex="-1"></a>theList <span class="ot">&lt;-</span> <span class="fu">list</span>( <span class="at">x=</span><span class="fu">seq</span>(<span class="dv">2</span>,<span class="dv">40</span>, <span class="at">by=</span><span class="dv">2</span>), <span class="at">dog=</span>LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">hasStyle=</span><span class="fu">logical</span>(<span class="dv">5</span>) )</span>
<span id="cb150-2"><a href="basic-r.html#cb150-2" tabindex="-1"></a><span class="fu">summary</span>(theList)</span></code></pre></div>
<pre><code>##          Length Class  Mode     
## x        20     -none- numeric  
## dog       5     -none- character
## hasStyle  5     -none- logical</code></pre>
<p>which is defined with a numeric, a character, and a logical component. Each of these entries can be different in length as well as type. Once defined, the entries may be observed as:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="basic-r.html#cb152-1" tabindex="-1"></a>theList</span></code></pre></div>
<pre><code>## $x
##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40
## 
## $dog
## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;
## 
## $hasStyle
## [1] FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Once created, you can add variables to the list using the $-operator followed by the name of the key for the new entry.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="basic-r.html#cb154-1" tabindex="-1"></a>theList<span class="sc">$</span>my_favoriate_number <span class="ot">&lt;-</span> <span class="fl">2.9</span> <span class="sc">+</span> 3i</span></code></pre></div>
<p>or use double brackets and the name of the variable as a character string.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="basic-r.html#cb155-1" tabindex="-1"></a>theList[[<span class="st">&quot;lotto numbers&quot;</span>]] <span class="ot">&lt;-</span> <span class="fu">rpois</span>(<span class="dv">7</span>,<span class="at">lambda=</span><span class="dv">42</span>)</span></code></pre></div>
<p>The keys currently in the list are given by the <code>names()</code> function</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="basic-r.html#cb156-1" tabindex="-1"></a><span class="fu">names</span>(theList)</span></code></pre></div>
<pre><code>## [1] &quot;x&quot;                   &quot;dog&quot;                 &quot;hasStyle&quot;           
## [4] &quot;my_favoriate_number&quot; &quot;lotto numbers&quot;</code></pre>
<p>Getting and setting values within a list are done the same way using either the <code>$</code>-operator</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="basic-r.html#cb158-1" tabindex="-1"></a>theList<span class="sc">$</span>x</span></code></pre></div>
<pre><code>##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="basic-r.html#cb160-1" tabindex="-1"></a>theList<span class="sc">$</span>x[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb160-2"><a href="basic-r.html#cb160-2" tabindex="-1"></a>theList<span class="sc">$</span>x</span></code></pre></div>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or the double brackets</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="basic-r.html#cb162-1" tabindex="-1"></a>theList[[<span class="st">&quot;x&quot;</span>]]</span></code></pre></div>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or using a numeric index, but that numeric index is looks to the results of <code>names()</code> to figure out which key to use.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="basic-r.html#cb164-1" tabindex="-1"></a>theList[[<span class="dv">2</span>]]</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;</code></pre>
<p>The use of the double brackets in essence provides a direct link to the variable in the list whose name is second in the <code>names()</code> function (<em>dog</em> in this case). If you want to access elements within that variable, then you add a second set of brackets on after the double ones.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="basic-r.html#cb166-1" tabindex="-1"></a>theList[[<span class="dv">1</span>]][<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>This deviates from the matrix approach as well as from how we access entries in a <code>data.frame</code> (described next). It is not a single square bracket with two indices, that gives you an error:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="basic-r.html#cb168-1" tabindex="-1"></a>theList[<span class="dv">1</span>,<span class="dv">3</span>] </span></code></pre></div>
<pre><code>## Error in theList[1, 3] : incorrect number of dimensions
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>List are rather robust objects that allow you to store a wide variety of data types (including nested lists). Once you get the indexing scheme down, it they will provide nice solutions for many of your computational needs.</p>
</div>
<div id="data-frames" class="section level4 unnumbered hasAnchor">
<h4>3.4. Data Frames<a href="basic-r.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="a.-data-frames-as-spreadsheets" class="section level5 unnumbered hasAnchor">
<h5>a. Data Frames as spreadsheets<a href="basic-r.html#a.-data-frames-as-spreadsheets" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The <code>data.frame</code> is the default data container in R. It is analogous to both a spreadsheet, at least in the way that I have used spreadsheets in the past, as well as a database. If you consider a single spreadsheet containing measurements and observations from your research, you may have many columns of data, each of which may be a different kind of data. There may be <code>factors</code> representing designations such as species, regions, populations, sex, flower color, etc. Other columns may contain numeric data types for items such as latitude, longitude, dbh, and nectar sugar content. You may also have specialized columns such as dates collected, genetic loci, and any other information you may be collecting.</p>
<p>On a spreadsheet, each column has a unified data type, either quantified with a value or as a missing value, <code>NA</code>, in each row. Rows typically represent the sampling unit, perhaps individual or site, along which all of these various items have been measured or determined. A <code>data.frame</code> is similar to this, at least conceptually. You define a <code>data.frame</code> by designating the columns of data to be used. You do not need to define all of them, more can be added later. The values passed can be sequences, collections of values, or computed parameters. For example:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="basic-r.html#cb170-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>( <span class="at">ID=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="at">Names=</span><span class="fu">c</span>(<span class="st">&quot;Bob&quot;</span>,<span class="st">&quot;Alice&quot;</span>,<span class="st">&quot;Vicki&quot;</span>,<span class="st">&quot;John&quot;</span>,<span class="st">&quot;Sarah&quot;</span>), <span class="at">Score=</span><span class="dv">100</span> <span class="sc">-</span> <span class="fu">rpois</span>(<span class="dv">5</span>,<span class="at">lambda=</span><span class="dv">10</span>))</span>
<span id="cb170-2"><a href="basic-r.html#cb170-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>##   ID Names Score
## 1  1   Bob    94
## 2  2 Alice    90
## 3  3 Vicki    90
## 4  4  John    87
## 5  5 Sarah    92</code></pre>
<p>You can see that each column is a unified type of data and each row is equivalent to a record. Additional data columns may be added to an existing data.frame as:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="basic-r.html#cb172-1" tabindex="-1"></a>df<span class="sc">$</span>Passed_Class <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>,<span class="cn">TRUE</span>,<span class="cn">TRUE</span>,<span class="cn">FALSE</span>,<span class="cn">TRUE</span>)</span></code></pre></div>
<p>Since we may have many (thousands?) of rows of observations, a <code>summary()</code> of the data.frame can provide a more compact description.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="basic-r.html#cb173-1" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div>
<pre><code>##        ID       Names               Score      Passed_Class   
##  Min.   :1   Length:5           Min.   :87.0   Mode :logical  
##  1st Qu.:2   Class :character   1st Qu.:90.0   FALSE:1        
##  Median :3   Mode  :character   Median :90.0   TRUE :4        
##  Mean   :3                      Mean   :90.6                  
##  3rd Qu.:4                      3rd Qu.:92.0                  
##  Max.   :5                      Max.   :94.0</code></pre>
<p>We can add columns of data to the data.frame after the fact using the <code>$</code>-operator to indicate the column name. Depending upon the data type, the summary will provide an overview of what is there.</p>
</div>
<div id="b.-indexing-data-frames" class="section level5 unnumbered hasAnchor">
<h5>b. Indexing Data Frames<a href="basic-r.html#b.-indexing-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>You can access individual items within a <code>data.frame</code> by numeric index such as:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="basic-r.html#cb175-1" tabindex="-1"></a>df[<span class="dv">1</span>,<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 94</code></pre>
<p>You can slide indices along rows (which return a new <code>data.frame</code> for you)</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="basic-r.html#cb177-1" tabindex="-1"></a>df[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    94         TRUE</code></pre>
<p>or along columns (which give you a vector of data)</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="basic-r.html#cb179-1" tabindex="-1"></a>df[,<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] 94 90 90 87 92</code></pre>
<p>or use the <code>$</code>-operator as you did for the list data type to get direct access to a either all the data or a specific subset therein.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="basic-r.html#cb181-1" tabindex="-1"></a>df<span class="sc">$</span>Names[<span class="dv">3</span>]</span></code></pre></div>
<pre><code>## [1] &quot;Vicki&quot;</code></pre>
<p>Indices are ordered just like for matrices, rows first then columns. You can also pass a set of indices such as:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="basic-r.html#cb183-1" tabindex="-1"></a>df[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,]</span></code></pre></div>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    94         TRUE
## 2  2 Alice    90         TRUE
## 3  3 Vicki    90         TRUE</code></pre>
<p>It is also possible to use logical operators as indices. Here I select only those names in the data.frame whose score was &gt;90 and they passed popgen.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="basic-r.html#cb185-1" tabindex="-1"></a>df<span class="sc">$</span>Names[df<span class="sc">$</span>Score <span class="sc">&gt;</span> <span class="dv">90</span> <span class="sc">&amp;</span> df<span class="sc">$</span>Passed_Class<span class="sc">==</span><span class="cn">TRUE</span>]</span></code></pre></div>
<pre><code>## [1] &quot;Bob&quot;   &quot;Sarah&quot;</code></pre>
<p>This is why <code>data.frame</code> objects are very database like. They can contain lots of data and you can extract from them subsets that you need to work on. This is a VERY important feature, one that is vital for reproducible research. Keep you data in one and only one place.</p>
</div>
</div>
</div>
<div id="programming" class="section level3 unnumbered hasAnchor">
<h3>4. Programming<a href="basic-r.html#programming" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the strengths of R as an analysis platform is that it is a language rather than a program. With programs, such as SPSS &amp; JMP, you are limited by the functionality that the designers thought would be necessary to meet the broadest audience. In R, you can rely upon simple functions or you can create entire analysis and simulation programs de novo. To do this, we need to dig into flow control and decision making processes, both of which you need for doing more in-depth programming.</p>
<div id="function-writing" class="section level4 unnumbered hasAnchor">
<h4>4.1. Function Writing<a href="basic-r.html#function-writing" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Here we look at how to create an R function. Writing small functions like this is a huge benefit to you as an analyst and this is a great place to start. A function in R is defined as:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="basic-r.html#cb187-1" tabindex="-1"></a>function_name <span class="ot">&lt;-</span> <span class="cf">function</span>( arguments ) { Stuff you want the <span class="cf">function</span> to do }</span></code></pre></div>
<p>You define a function name for whatever you like and assign it the stuff to the right. In R, the function named <code>function()</code> is a special one, it tells R that you are about to create a little routine and you want that set of code to be available to you for later use under the name of whatever you named it. This allows a tremendous amount of flexibility as you develop your own set of routines and analyses for your work. The part that actually does stuff is after the function call. It may be that the function that you create does need some data (those are the arguments) or you may not need any input in to the function (in which you pass no arguments). It all depends upon what you are creating.</p>
<p>The key to understanding functions is that they are encapsulations of code—a shortcut for a sequence of instructions if you will not have to type over and over again. The less typing you do, the lower the probability that you will have errors (and all code has errors).</p>
<p>Here is an example of some code that I’m going to develop into a function. This function will allow me to determine if one genotype could possibly be the offspring of the other genotype.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="basic-r.html#cb188-1" tabindex="-1"></a><span class="fu">library</span>(gstudio)</span>
<span id="cb188-2"><a href="basic-r.html#cb188-2" tabindex="-1"></a>loc1 <span class="ot">&lt;-</span> <span class="fu">locus</span>( <span class="fu">c</span>(<span class="dv">128</span>,<span class="dv">130</span>) )</span>
<span id="cb188-3"><a href="basic-r.html#cb188-3" tabindex="-1"></a>loc2 <span class="ot">&lt;-</span> <span class="fu">locus</span>( <span class="fu">c</span>(<span class="dv">128</span>,<span class="dv">128</span>) )</span>
<span id="cb188-4"><a href="basic-r.html#cb188-4" tabindex="-1"></a><span class="fu">cat</span>( loc1, loc2 )</span></code></pre></div>
<pre><code>## 128:130 128:128</code></pre>
<p>We start out with two loci, a <code>128:130</code> heterozygote and a <code>128:128</code> homozygote. These may represent repeat motifs at a microsatellite locus or some other co-dominant genotype. First, I’ll break the locus into a vector of genotypes.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="basic-r.html#cb190-1" tabindex="-1"></a>off.alleles <span class="ot">&lt;-</span> <span class="fu">alleles</span>( loc1 )</span>
<span id="cb190-2"><a href="basic-r.html#cb190-2" tabindex="-1"></a>off.alleles</span></code></pre></div>
<pre><code>## [1] &quot;128&quot; &quot;130&quot;</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="basic-r.html#cb192-1" tabindex="-1"></a>mom.alleles <span class="ot">&lt;-</span> <span class="fu">alleles</span>( loc2 )</span>
<span id="cb192-2"><a href="basic-r.html#cb192-2" tabindex="-1"></a>mom.alleles</span></code></pre></div>
<pre><code>## [1] &quot;128&quot; &quot;128&quot;</code></pre>
<p>To be a valid potential offspring there should be at least one of the alleles in the parent that matches the allele in the offspring. The <code>intersect()</code> function returns the set of values common to both vectors.</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="basic-r.html#cb194-1" tabindex="-1"></a>shared <span class="ot">&lt;-</span> <span class="fu">intersect</span>( off.alleles, mom.alleles )</span>
<span id="cb194-2"><a href="basic-r.html#cb194-2" tabindex="-1"></a>shared</span></code></pre></div>
<pre><code>## [1] &quot;128&quot;</code></pre>
<p>If it has at least one of the alleles present (it could have both if parent and offspring are both the same heterozygote) then you cannot exclude this individual as a potential offspring. If there are no alleles in common, then the value returned is an empty vector.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="basic-r.html#cb196-1" tabindex="-1"></a>loc3 <span class="ot">&lt;-</span> <span class="fu">locus</span>( <span class="fu">c</span>(<span class="dv">132</span>,<span class="dv">132</span>))</span>
<span id="cb196-2"><a href="basic-r.html#cb196-2" tabindex="-1"></a>dad.alleles <span class="ot">&lt;-</span> <span class="fu">alleles</span>( loc3 )</span>
<span id="cb196-3"><a href="basic-r.html#cb196-3" tabindex="-1"></a><span class="fu">intersect</span>( mom.alleles, dad.alleles )</span></code></pre></div>
<pre><code>## character(0)</code></pre>
<p>This logic can be shoved into a function. You have to wrap it into a set of curly brackets. I use the length of the result from the intersect() to return from the function. Potential values for</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="basic-r.html#cb198-1" tabindex="-1"></a>potential_offspring <span class="ot">&lt;-</span> <span class="cf">function</span>( parent, offspring ) {</span>
<span id="cb198-2"><a href="basic-r.html#cb198-2" tabindex="-1"></a>  off <span class="ot">&lt;-</span> <span class="fu">alleles</span>( offspring )</span>
<span id="cb198-3"><a href="basic-r.html#cb198-3" tabindex="-1"></a>  par <span class="ot">&lt;-</span> <span class="fu">alleles</span>( loc2 )</span>
<span id="cb198-4"><a href="basic-r.html#cb198-4" tabindex="-1"></a>  shared <span class="ot">&lt;-</span> <span class="fu">intersect</span>( off, par )</span>
<span id="cb198-5"><a href="basic-r.html#cb198-5" tabindex="-1"></a>  <span class="fu">return</span>( <span class="fu">length</span>( shared ) <span class="sc">&gt;</span> <span class="dv">0</span> )</span>
<span id="cb198-6"><a href="basic-r.html#cb198-6" tabindex="-1"></a>}</span></code></pre></div>
<p>Now, you can call this function anytime you need, just passing it two genotypes. If they can be offspring it returns TRUE, as in the comparison between 128:130 and 128:128 genotypes.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="basic-r.html#cb199-1" tabindex="-1"></a><span class="fu">potential_offspring</span>(loc1, loc2)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>And it returns FALSE for the comparison between 128:128 and 132:132.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="basic-r.html#cb201-1" tabindex="-1"></a><span class="fu">potential_offspring</span>(loc2, loc3)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="variable-scope" class="section level4 unnumbered hasAnchor">
<h4>4.2. Variable Scope<a href="basic-r.html#variable-scope" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There is a lot more information on writing functions and we will get into that as we progress through the text. However, it is important that I bring this up now. The value assigned to a variable is defined by its scope. Consider the following code</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="basic-r.html#cb203-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">10</span></span></code></pre></div>
<p>and the function defined as</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="basic-r.html#cb204-1" tabindex="-1"></a>do_it <span class="ot">&lt;-</span> <span class="cf">function</span>( x ) {</span>
<span id="cb204-2"><a href="basic-r.html#cb204-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> x <span class="sc">+</span> <span class="dv">10</span></span>
<span id="cb204-3"><a href="basic-r.html#cb204-3" tabindex="-1"></a>  <span class="fu">return</span>( x )</span>
<span id="cb204-4"><a href="basic-r.html#cb204-4" tabindex="-1"></a>}</span></code></pre></div>
<p>When I call the function, the variable x that is the argument of the function is not the same variable that is in the environment that I assigned a value of 10. The x in the function argument is what we call “local to that function” in that within the curly brackets that follow (and any number of curly brackets nested within those, the value of x is given whatever was passed to the function.</p>
</div>
<div id="decision-making" class="section level4 unnumbered hasAnchor">
<h4>4.3. Decision Making<a href="basic-r.html#decision-making" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We interact with our data in many ways and introspection of the values we have in the variables we are working with are of prime importance. Decision making in your code is where you evaluate your data and make a choice of outcomes based upon some criteria. Here is some example data that we can use as we explore the basics of <code>if()</code>, <code>if(){} else{}</code>, and <code>if(){} elif(){} else{}</code> coding patterns.</p>
<div id="a.-the-if-pattern" class="section level5 unnumbered hasAnchor">
<h5>a. The if Pattern<a href="basic-r.html#a.-the-if-pattern" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>The most basic version of decision making is asking a single question and if the answer is TRUE then do something. The <code>if(){}</code> function does this and has the form</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="basic-r.html#cb205-1" tabindex="-1"></a><span class="cf">if</span>( CRITERIA ) {</span>
<span id="cb205-2"><a href="basic-r.html#cb205-2" tabindex="-1"></a>    DO_SOMETHING</span>
<span id="cb205-3"><a href="basic-r.html#cb205-3" tabindex="-1"></a>}</span></code></pre></div>
<p>You pass a logical statement (or something that can be coerced into a logical type) to the function as the CRITERIA and if it evaluates to <code>TRUE</code>, then the contents of the <code>DO_SOMETHING</code> are executed. If the value of <code>CRITERIA</code> is not <code>TRUE</code> the <code>DO_SOMETHING</code> is skipped entirely—it is not even seen by the interpreter.</p>
<p>Here we can test this out using the loci defined above along with the is_heterozygote() function. This function takes one or more locus objects and returns TRUE/FALSE if they are or are not a heterozygote.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="basic-r.html#cb206-1" tabindex="-1"></a><span class="fu">is_heterozygote</span>( <span class="fu">c</span>(loc1, loc2) )</span></code></pre></div>
<pre><code>## [1]  TRUE FALSE</code></pre>
<p>If we shove that function into the <code>if()</code> parameters we can use its evaluation of the heterozygous state of the locus to do something interesting, say tell us it is a heterozygote—it is admittedly a contrived example, but hey you try to make easy examples, it is not easy.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="basic-r.html#cb208-1" tabindex="-1"></a><span class="cf">if</span>( <span class="fu">is_heterozygote</span>(loc1) ){</span>
<span id="cb208-2"><a href="basic-r.html#cb208-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;It&#39;s a het!&quot;</span>)</span>
<span id="cb208-3"><a href="basic-r.html#cb208-3" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;It&#39;s a het!&quot;</code></pre>
<p>If the <code>is_heterozygote()</code> function returns a value of FALSE, then the contents of the <code>if()</code> function (the stuff within the curly brackets is skipped entirely.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="basic-r.html#cb210-1" tabindex="-1"></a><span class="cf">if</span>( <span class="fu">is_heterozygote</span>(loc2) ){</span>
<span id="cb210-2"><a href="basic-r.html#cb210-2" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;It&#39;s a het!&quot;</span>)</span>
<span id="cb210-3"><a href="basic-r.html#cb210-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Notice, there was no indication of any of that code inside the curly brackets.
The if-else Pattern
If there are more than on thing you want to potentially do when making a decision, you can add an else clause after the if pattern. Here if is_heterozygote() returns FALSE, the contents of the else{} clause will be executed. Here is the heterozygote example</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="basic-r.html#cb211-1" tabindex="-1"></a><span class="cf">if</span>( <span class="fu">is_heterozygote</span>(loc1) ) {</span>
<span id="cb211-2"><a href="basic-r.html#cb211-2" tabindex="-1"></a>  <span class="fu">cat</span>(loc1, <span class="st">&quot;is a heterozygote&quot;</span>)</span>
<span id="cb211-3"><a href="basic-r.html#cb211-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb211-4"><a href="basic-r.html#cb211-4" tabindex="-1"></a>  <span class="fu">cat</span>(loc1, <span class="st">&quot;is a homozygote&quot;</span>)</span>
<span id="cb211-5"><a href="basic-r.html#cb211-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## 128:130 is a heterozygote</code></pre>
<p>and the homozygote one</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="basic-r.html#cb213-1" tabindex="-1"></a><span class="cf">if</span>( <span class="fu">is_heterozygote</span>(loc2) ) {</span>
<span id="cb213-2"><a href="basic-r.html#cb213-2" tabindex="-1"></a>  <span class="fu">cat</span>(loc2, <span class="st">&quot;is a heterozygote&quot;</span>)</span>
<span id="cb213-3"><a href="basic-r.html#cb213-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb213-4"><a href="basic-r.html#cb213-4" tabindex="-1"></a>  <span class="fu">cat</span>(loc2, <span class="st">&quot;is a homozygote&quot;</span>)</span>
<span id="cb213-5"><a href="basic-r.html#cb213-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## 128:128 is a homozygote</code></pre>
<p>There is a slightly shorter version of this that is available for the lazy programmer and lets be honest, all programmers are lazy and the more you can accomplish with fewer strokes on the keyboard the better (this is how we got emacs and vim). I generally don’t teach the shortcuts up front, but this one is short and readily apparent so it may be more helpful than confusing. The <code>ifelse()</code> function has three parts, the condition, the result if <code>TRUE</code>, and the result if <code>FALSE</code>.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="basic-r.html#cb215-1" tabindex="-1"></a>ans <span class="ot">&lt;-</span> <span class="fu">ifelse</span>( <span class="fu">is_heterozygote</span>( <span class="fu">c</span>(loc1, loc2)) , <span class="st">&quot;heterozygote&quot;</span>, <span class="st">&quot;Not&quot;</span>)</span>
<span id="cb215-2"><a href="basic-r.html#cb215-2" tabindex="-1"></a>ans</span></code></pre></div>
<pre><code>## [1] &quot;heterozygote&quot; &quot;Not&quot;</code></pre>
<p>So iterating through the x vector, the condition <code>x&gt;0</code> is evaluated and if TRUE the sqrt() of the value is returned, else the NA is given. It is compact and easy to use so you may run into it often.</p>
</div>
<div id="b.-the-if-else-pattern" class="section level5 unnumbered hasAnchor">
<h5>b. The <code>if-else</code> Pattern<a href="basic-r.html#b.-the-if-else-pattern" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>It is possible to test many conditions in a single sequence by stringing together else-if conditions. The point that is important here is that the first condition that evaluates to TRUE will be executed and all remaining ones will be skipped, even if they also are logically TRUE. This means that it is important to figure out the proper order of asking your conditions. Here is an example function that determines if none, one, or both of the genotypes passed to it are heterozygotes. By default, I step through every one of the potential options of available on this comparison.<br />
1. The first is a heterozygote and the second one isn’t
2. The first one isn’t and the second one is
3. Both are heterozygotes
4. The last state (both are not)</p>
<p>Here is the function.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="basic-r.html#cb217-1" tabindex="-1"></a>which_is_het <span class="ot">&lt;-</span> <span class="cf">function</span>( A, B) {</span>
<span id="cb217-2"><a href="basic-r.html#cb217-2" tabindex="-1"></a>  <span class="cf">if</span>( <span class="fu">is_heterozygote</span>(A) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is_heterozygote</span>(B) ) {</span>
<span id="cb217-3"><a href="basic-r.html#cb217-3" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;First is heterozygote&quot;</span>)</span>
<span id="cb217-4"><a href="basic-r.html#cb217-4" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>( <span class="sc">!</span><span class="fu">is_heterozygote</span>(A) <span class="sc">&amp;</span> <span class="fu">is_heterozygote</span>(B) ){</span>
<span id="cb217-5"><a href="basic-r.html#cb217-5" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;Second is heterozygote&quot;</span>)</span>
<span id="cb217-6"><a href="basic-r.html#cb217-6" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span>( <span class="fu">is_heterozygote</span>(A) <span class="sc">&amp;</span> <span class="fu">is_heterozygote</span>(B) ){</span>
<span id="cb217-7"><a href="basic-r.html#cb217-7" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;Both are heterozygotes&quot;</span>)</span>
<span id="cb217-8"><a href="basic-r.html#cb217-8" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb217-9"><a href="basic-r.html#cb217-9" tabindex="-1"></a>    <span class="fu">print</span>( <span class="st">&quot;Neither are heterozygotes&quot;</span>)</span>
<span id="cb217-10"><a href="basic-r.html#cb217-10" tabindex="-1"></a>  }</span>
<span id="cb217-11"><a href="basic-r.html#cb217-11" tabindex="-1"></a>}</span></code></pre></div>
<p>It is possible that the order of these CRITERIA could be changed, the important thing to remember is that the sequence of if - else if - else if etc. will terminate the very first time one of the CRITERIA is evaluated to be <code>TRUE</code>.</p>
</div>
</div>
<div id="flow-control" class="section level4 unnumbered hasAnchor">
<h4>4.4. Flow Control<a href="basic-r.html#flow-control" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Flow control is the process of iterating across objects and perhaps doing operations on those objects. The R language has several mechanisms that you can use to control the flow of a script or bit of code.</p>
<div id="a.-the-for-loop" class="section level5 unnumbered hasAnchor">
<h5>a. The <code>for()</code> Loop<a href="basic-r.html#a.-the-for-loop" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="basic-r.html#cb218-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">6</span>)</span>
<span id="cb218-2"><a href="basic-r.html#cb218-2" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>## [1] 3 8 5 4 6</code></pre>
<p>You can iterate through this vector using a for() loop. This is a simple function that has the form:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="basic-r.html#cb220-1" tabindex="-1"></a><span class="cf">for</span>( SOME_SEQUENCE ){</span>
<span id="cb220-2"><a href="basic-r.html#cb220-2" tabindex="-1"></a>  DO_SOMETHING</span>
<span id="cb220-3"><a href="basic-r.html#cb220-3" tabindex="-1"></a>}</span></code></pre></div>
<p>Where the <code>SOME_SEQUENCE</code> component is a sequence of values either specified OR calculated and the <code>DO_SOMETHING</code> is the thing you want to do with each of the values in the sequence. Usually, there is a variable defined in the <code>SOME_SEQUENCE</code> component and the value of that variable is used. Here are a few examples. The first goes through the existing vector directly and assigns (in sequential order) the entries of ‘x’ to the variable val. We can then do whatever we want with the value in val (though if we change it, nothing happens to the original x vector).</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="basic-r.html#cb221-1" tabindex="-1"></a><span class="cf">for</span>( val <span class="cf">in</span> x ){</span>
<span id="cb221-2"><a href="basic-r.html#cb221-2" tabindex="-1"></a>  <span class="fu">print</span>(val)</span>
<span id="cb221-3"><a href="basic-r.html#cb221-3" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>We can also specify a sequence directly and then use it as an index. Here I use an index variable named i to take on the integer seqeunce equal in length to the length of the original <code>x</code> variable. Then I can iterate through the original vector and use that index variable to grab the value I want.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="basic-r.html#cb223-1" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(x)){</span>
<span id="cb223-2"><a href="basic-r.html#cb223-2" tabindex="-1"></a>  <span class="fu">print</span>( x[i] )</span>
<span id="cb223-3"><a href="basic-r.html#cb223-3" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>Both give us the same output, namely a way to go through the variable <code>x</code>. However, there may be a need to use the latter approach in your calculations. For example, perhaps I want to do some other operation on the values. In this very contrived example that follows, I want to perform operations on the values in <code>x</code> depending on if they are even or odd. For the odd ones, I add the corresponding value in <code>y</code> and if not I subtract it. Sure, this is totally contrived and I cannot think of a reason why I would be doing this, but if I need to know what index (row, column or whatever) an entry is during the iteration process, then I need to use this approach over the <code>for( val in x)</code> approach.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="basic-r.html#cb225-1" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb225-2"><a href="basic-r.html#cb225-2" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(x)){</span>
<span id="cb225-3"><a href="basic-r.html#cb225-3" tabindex="-1"></a>  <span class="cf">if</span>( x[i] <span class="sc">%%</span> <span class="dv">2</span>)</span>
<span id="cb225-4"><a href="basic-r.html#cb225-4" tabindex="-1"></a>    <span class="fu">print</span>( x[i] <span class="sc">+</span> y[i])</span>
<span id="cb225-5"><a href="basic-r.html#cb225-5" tabindex="-1"></a>  <span class="cf">else</span></span>
<span id="cb225-6"><a href="basic-r.html#cb225-6" tabindex="-1"></a>    <span class="fu">print</span>( x[i] <span class="sc">-</span> y[i] )</span>
<span id="cb225-7"><a href="basic-r.html#cb225-7" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 4
## [1] 6
## [1] 8
## [1] 0
## [1] 1</code></pre>
</div>
<div id="b.-short-circuiting-the-loop" class="section level5 unnumbered hasAnchor">
<h5>b. Short Circuiting the Loop<a href="basic-r.html#b.-short-circuiting-the-loop" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>It is possible to short circuit the looping process using the keywords next and break, though in my programming style, I consider their use in my source files as evidence of inelegant code. That said, you may need them on occasion.</p>
<p>The next keyword basically stops all commands after that during the current iteration of the loop. It does not terminate the loop itself, it just stops the commands that follow it this time through. Here is an example that uses the modulus operator, <code>%%</code> (e.g., the remainder after division), to print out only those numbers that are divisible by three.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="basic-r.html#cb227-1" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span> ){</span>
<span id="cb227-2"><a href="basic-r.html#cb227-2" tabindex="-1"></a>  <span class="cf">if</span>( i <span class="sc">%%</span> <span class="dv">3</span> )</span>
<span id="cb227-3"><a href="basic-r.html#cb227-3" tabindex="-1"></a>    <span class="cf">next</span></span>
<span id="cb227-4"><a href="basic-r.html#cb227-4" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;The value of i =&quot;</span>,i,<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb227-5"><a href="basic-r.html#cb227-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## The value of i = 3 
## The value of i = 6 
## The value of i = 9 
## The value of i = 12 
## The value of i = 15 
## The value of i = 18</code></pre>
<p>The use of break to exit the loop entirely is perhaps more commonly encountered. When this keyword is encountered, the loop terminates immediately, as if it reached the send of the sequence.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="basic-r.html#cb229-1" tabindex="-1"></a><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>){</span>
<span id="cb229-2"><a href="basic-r.html#cb229-2" tabindex="-1"></a>  <span class="cf">if</span>( i <span class="sc">&gt;</span> <span class="dv">2</span> )</span>
<span id="cb229-3"><a href="basic-r.html#cb229-3" tabindex="-1"></a>    <span class="cf">break</span></span>
<span id="cb229-4"><a href="basic-r.html#cb229-4" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;The value of i=&quot;</span>,i,<span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb229-5"><a href="basic-r.html#cb229-5" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## The value of i= 1 
## The value of i= 2</code></pre>
</div>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The word <em>data</em> is plural, datum is singular<a href="basic-r.html#fnref1" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="review-of-r-skills.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="r-graphics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
