<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Review of R Skills | Landscape Genetic Data Analysis with R</title>
  <meta name="description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.18.3 and GitBook 2.6.7" />

  <meta property="og:title" content="Review of R Skills | Landscape Genetic Data Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  <meta name="github-repo" content="hhwagner1/LandGenCourse_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Review of R Skills | Landscape Genetic Data Analysis with R" />
  
  <meta name="twitter:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  

<meta name="author" content="Editor: Helene Wagner (University of Toronto)" />


<meta name="date" content="2021-04-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="further-r-resources.html"/>
<link rel="next" href="further-r-resources-1.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Landscape Genetic Data Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i>How to use this book</a></li>
</ul></li>
<li class="part"><span><b>Getting Started</b></span></li>
<li><a href="Week001.html#Week001">The <code>LandGenCourse</code> package</a>
<ul>
<li class="chapter" data-level="" data-path="Week001.html"><a href="Week001.html"><i class="fa fa-check"></i>Installation</a></li>
<li class="chapter" data-level="" data-path="Week001.html"><a href="Week001.html#list-of-packages-by-vignette"><i class="fa fa-check"></i>List of Packages by Vignette</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html"><i class="fa fa-check"></i>Review of R Skills</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#basic-r-programming"><i class="fa fa-check"></i>Basic R Programming</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#overview"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#data-types"><i class="fa fa-check"></i>2. Data Types</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#numeric-data-types"><i class="fa fa-check"></i>2.1. Numeric Data Types</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#characters"><i class="fa fa-check"></i>2.2. Characters</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#factors"><i class="fa fa-check"></i>2.3. Factors</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#logical-types"><i class="fa fa-check"></i>2.4. Logical Types</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#data-containers"><i class="fa fa-check"></i>3. Data Containers</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#vectors"><i class="fa fa-check"></i>3.1. Vectors</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#matrices"><i class="fa fa-check"></i>3.2. Matrices</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#lists"><i class="fa fa-check"></i>3.3. Lists</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#data-frames"><i class="fa fa-check"></i>3.4. Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#programming"><i class="fa fa-check"></i>4. Programming</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#function-writing"><i class="fa fa-check"></i>4.1. Function Writing</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#variable-scope"><i class="fa fa-check"></i>4.2. Variable Scope</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#decision-making"><i class="fa fa-check"></i>4.3. Decision Making</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#flow-control"><i class="fa fa-check"></i>4.4. Flow Control</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#r-graphics"><i class="fa fa-check"></i>R Graphics</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#overview-1"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#univariate-plots"><i class="fa fa-check"></i>2. Univariate plots</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#barplots-and-histograms"><i class="fa fa-check"></i>2.1. Barplots and histograms</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#plotting-parameters"><i class="fa fa-check"></i>2.2. Plotting Parameters</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#density-plots"><i class="fa fa-check"></i>2.3. Density Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#bivariate-plots"><i class="fa fa-check"></i>3. Bivariate plots</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#overlaying-plots-by-grouping"><i class="fa fa-check"></i>3.1. Overlaying Plots by grouping</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#boxplots"><i class="fa fa-check"></i>3.2. Boxplots</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#scatter-plots"><i class="fa fa-check"></i>3.3. Scatter Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#advanced-plotting"><i class="fa fa-check"></i>4. Advanced plotting</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#multiple-plots"><i class="fa fa-check"></i>4.1. Multiple Plots</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#color-palettes"><i class="fa fa-check"></i>4.2. Color Palettes</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#rcolorbrewer"><i class="fa fa-check"></i>4.3. RColorBrewer</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#saving-imagery"><i class="fa fa-check"></i>4.4. Saving Imagery</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html#interactive-graphics"><i class="fa fa-check"></i>4.5. Interactive Graphics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="further-r-resources.html"><a href="further-r-resources.html"><i class="fa fa-check"></i>Further R Resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html"><i class="fa fa-check"></i>Review of R Skills</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#basic-r-programming-1"><i class="fa fa-check"></i>Basic R Programming</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#overview-2"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#data-types-1"><i class="fa fa-check"></i>2. Data Types</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#numeric-data-types-1"><i class="fa fa-check"></i>2.1. Numeric Data Types</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#characters-1"><i class="fa fa-check"></i>2.2. Characters</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#factors-1"><i class="fa fa-check"></i>2.3. Factors</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#logical-types-1"><i class="fa fa-check"></i>2.4. Logical Types</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#data-containers-1"><i class="fa fa-check"></i>3. Data Containers</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#vectors-1"><i class="fa fa-check"></i>3.1. Vectors</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#matrices-1"><i class="fa fa-check"></i>3.2. Matrices</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#lists-1"><i class="fa fa-check"></i>3.3. Lists</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#data-frames-1"><i class="fa fa-check"></i>3.4. Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#programming-1"><i class="fa fa-check"></i>4. Programming</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#function-writing-1"><i class="fa fa-check"></i>4.1. Function Writing</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#variable-scope-1"><i class="fa fa-check"></i>4.2. Variable Scope</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#decision-making-1"><i class="fa fa-check"></i>4.3. Decision Making</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#flow-control-1"><i class="fa fa-check"></i>4.4. Flow Control</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#r-graphics-1"><i class="fa fa-check"></i>R Graphics</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#overview-3"><i class="fa fa-check"></i>1. Overview</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#univariate-plots-1"><i class="fa fa-check"></i>2. Univariate plots</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#barplots-and-histograms-1"><i class="fa fa-check"></i>2.1. Barplots and histograms</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#plotting-parameters-1"><i class="fa fa-check"></i>2.2. Plotting Parameters</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#density-plots-1"><i class="fa fa-check"></i>2.3. Density Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#bivariate-plots-1"><i class="fa fa-check"></i>3. Bivariate plots</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#overlaying-plots-by-grouping-1"><i class="fa fa-check"></i>3.1. Overlaying Plots by grouping</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#boxplots-1"><i class="fa fa-check"></i>3.2. Boxplots</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#scatter-plots-1"><i class="fa fa-check"></i>3.3. Scatter Plots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#advanced-plotting-1"><i class="fa fa-check"></i>4. Advanced plotting</a>
<ul>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#multiple-plots-1"><i class="fa fa-check"></i>4.1. Multiple Plots</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#color-palettes-1"><i class="fa fa-check"></i>4.2. Color Palettes</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#rcolorbrewer-1"><i class="fa fa-check"></i>4.3. RColorBrewer</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#saving-imagery-1"><i class="fa fa-check"></i>4.4. Saving Imagery</a></li>
<li class="chapter" data-level="" data-path="review-of-r-skills-1.html"><a href="review-of-r-skills-1.html#interactive-graphics-1"><i class="fa fa-check"></i>4.5. Interactive Graphics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="further-r-resources-1.html"><a href="further-r-resources-1.html"><i class="fa fa-check"></i>Further R Resources</a></li>
<li class="part"><span><b>Basic Topics</b></span></li>
<li class="chapter" data-level="" data-path="Week1.html"><a href="Week1.html"><i class="fa fa-check"></i>Week 1: Importing Genetic Data</a>
<ul>
<li class="chapter" data-level="" data-path="video-1a.html"><a href="video-1a.html"><i class="fa fa-check"></i>Course Video</a>
<ul>
<li class="chapter" data-level="" data-path="video-1a.html"><a href="video-1a.html#preview"><i class="fa fa-check"></i>Preview</a></li>
<li class="chapter" data-level="" data-path="video-1a.html"><a href="video-1a.html#open-video-in-new-window"><i class="fa fa-check"></i>Open video in new window</a></li>
<li class="chapter" data-level="" data-path="video-1a.html"><a href="video-1a.html#download-slides"><i class="fa fa-check"></i>Download slides</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="tutorial-1.html"><a href="tutorial-1.html"><i class="fa fa-check"></i>Interactive Tutorial</a>
<ul>
<li class="chapter" data-level="" data-path="tutorial-1.html"><a href="tutorial-1.html#preview-1"><i class="fa fa-check"></i>Preview</a></li>
<li class="chapter" data-level="" data-path="tutorial-1.html"><a href="tutorial-1.html#list-of-r-commands-used"><i class="fa fa-check"></i>List of R commands used</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html"><i class="fa fa-check"></i>Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#overview-of-worked-example"><i class="fa fa-check"></i>1. Overview of Worked Example</a>
<ul>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#a.-goals"><i class="fa fa-check"></i>a. Goals</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#b.-data-set"><i class="fa fa-check"></i>b. Data set</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#c.-required-r-libraries"><i class="fa fa-check"></i>c. Required R libraries</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#import-data-from-.csv-file"><i class="fa fa-check"></i>2. Import data from .csv file</a>
<ul>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#a.-preparation"><i class="fa fa-check"></i>a. Preparation</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#b.-excel-file"><i class="fa fa-check"></i>b. Excel file</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#c.-import-with-function-read.csv"><i class="fa fa-check"></i>c. Import with function ‘read.csv’</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#d.-create-id-variable"><i class="fa fa-check"></i>d. Create ID variable</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#e.-export-with-function-write.csv"><i class="fa fa-check"></i>e. Export with function ‘write.csv’</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#create-genind-object"><i class="fa fa-check"></i>3. Create ‘genind’ Object</a>
<ul>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#a.-read-the-helpfile"><i class="fa fa-check"></i>a. Read the helpfile</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#b.-set-all-arguments-of-function-df2genind"><i class="fa fa-check"></i>b. Set all arguments of function ‘df2genind’</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#c.-check-imported-data"><i class="fa fa-check"></i>c. Check imported data</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#d.-summarize-genind-object"><i class="fa fa-check"></i>d. Summarize ‘genind’ object</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#view-information-stored-in-genind-object"><i class="fa fa-check"></i>4. View information stored in ‘genind’ object</a>
<ul>
<li><a href="WE-1.html#a.-slot-tab">a. Slot <code>@tab</code></a></li>
<li><a href="WE-1.html#b.-slot-loc.n.all">b. Slot <code>@loc.n.all</code></a></li>
<li><a href="WE-1.html#c.-slot-loc.fac">c. Slot <code>@loc.fac</code></a></li>
<li><a href="WE-1.html#d.-slot-all.names">d. Slot <code>@all.names</code></a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#e.-further-slots"><i class="fa fa-check"></i>e. Further slots</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#import-data-with-gstudio-package"><i class="fa fa-check"></i>5. Import data with ‘gstudio’ package</a>
<ul>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#a.-function-read_population"><i class="fa fa-check"></i>a. Function ‘read_population’</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#b.-set-arguments"><i class="fa fa-check"></i>b. Set arguments</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#c.-check-imported-data-1"><i class="fa fa-check"></i>c. Check imported data</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#d.-add-frogid"><i class="fa fa-check"></i>d. Add FrogID</a></li>
<li class="chapter" data-level="" data-path="WE-1.html"><a href="WE-1.html#e.-convert-to-genind-object"><i class="fa fa-check"></i>e. Convert to ‘genind’ object</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="r-exercise-week-1.html"><a href="r-exercise-week-1.html"><i class="fa fa-check"></i>R exercise Week 1</a></li>
<li class="chapter" data-level="" data-path="bonus-1a.html"><a href="bonus-1a.html"><i class="fa fa-check"></i>Bonus: Importing SNP data</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Landscape Genetic Data Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="review-of-r-skills-1" class="section level1">
<h1>Review of R Skills</h1>
<div id="basic-r-programming-1" class="section level3">
<h3>Basic R Programming</h3>
</div>
<div id="overview-2" class="section level3">
<h3>1. Overview</h3>
<p>This worked example is adapted from “Applied Population Genetics” by Rodney Dyer. The entire book is available here: <a href="http://dyerlab.github.io/applied_population_genetics/index.html" class="uri">http://dyerlab.github.io/applied_population_genetics/index.html</a></p>
<p>R is a statistical programming language, and it thus requires users to work with code. This can be intimidating at first. Working through this document will help you get up to speed with basic R concepts and notation. Whether you are new to R or need a refresher, this worked example will get you to the level expected for the ‘Landscape Genetics with R’ lab course. The main topics covered here are:</p>
<ul>
<li>R data types (how data are stored in R: numeric, character, etc.)</li>
<li>R containers (how data are organized: vectors, data frames, etc.)</li>
<li>R functions (how to tell R what to do)</li>
</ul>
<p>See also video “Week 0: Intro to R Notebooks” for options how to work this this document as .html or .Rmd.</p>
</div>
<div id="data-types-1" class="section level3">
<h3>2. Data Types</h3>
<p>The data we work with comes in many forms—integers, stratum, categories, genotypes, etc.—all of which we need to be able to work with in our analyses. In this chapter, the basic data types we will commonly use in population genetic analyses. This section covers some of the basic types of data we will use in R. These include numbers, character, factors, and logical data types. We will also introduce the locus object from the gstudio library and see how it is just another data type that we can manipulate in R.</p>
<p>The very first hurdle you need to get over is the oddness in the way in which R assigns values to variables.</p>
<p>Yes that is a less-than and dash character. This is the assignment operator that historically has been used and it is the one that I will stick with. In some cases you can use the ‘=’ to assign variables instead but then it takes away the R-ness of R itself. For decision making, the equality operator (e.g., is this equal to that) is the double equals sign ‘==.’ We will get into that below where we talk about logical types and later in decision making.</p>
<p>If you are unaware of what type a particular variable may be, you can always use the <code>type()</code> function and R will tell you.</p>
<p>R also has a pretty good help system built into itself. You can get help for any function by typing a question mark in front of the function name. This is a particularly awesome features because at the end of the help file, there is often examples of its usage, which are priceless. Here is the documentation for the ‘help’ function as given by:</p>
<p>There are also package vignettes available (for most packages you download) that provide additional information on the routines, data sets, and other items included in these packages. You can get a list of vignettes currently installed on your machine by:</p>
<p>and vignettes for a particular package by passing the package name as an argument to the function itself.</p>
<div id="numeric-data-types-1" class="section level4">
<h4>2.1. Numeric Data Types</h4>
<div id="a.-numeric-data-1" class="section level5">
<h5>a. Numeric data</h5>
<p>The quantitative measurements we make are often numeric, in that they can be represented as as a number with a decimal component (think weight, height, latitude, soil moisture, ear wax viscosity, etc.). The most basic type of data in R, is the numeric type and represents both integers and floating point numbers (n.b., there is a strict integer data type but it is often only needed when interfacing with other C libraries and can for what we are doing be disregarded).</p>
<p>Assigning a value to a variable is easy</p>
<pre><code>## [1] 3</code></pre>
<p>By default, R automatically outputs whole numbers numbers within decimal values appropriately.</p>
<pre><code>## [1] 3.142857</code></pre>
<p>If there is a mix of whole numbers and numbers with decimals together in a container such as</p>
<pre><code>## [1] 3.000000 3.142857</code></pre>
<p>then both are shown with decimals. The <code>c()</code> part here is a function that combines several data objects together into a vector and is very useful. In fact, the use of vectors are are central to working in R and functions almost all the functions we use on individual variables can also be applied to vectors.</p>
<p>A word of caution should be made about numeric data types on any computer. Consider the following example.</p>
<pre><code>## [1] 0.1</code></pre>
<p>which is exactly what we’d expect. However, the way in which computers store decimal numbers plays off our notion of significant digits pretty well. Look what happens when I print out x but carry out the number of decimal places.</p>
<pre><code>## [1] 0.099999999999999991673</code></pre>
<p>Not quite 0.1 is it? Not that far away from it but not exact. That is a general problem, not one that R has any more claim to than any other language and/or implementation. Does this matter much, probably not in the realm of the kinds of things we do in population genetics, it is just something that you should be aware of.
You can make random sets of numeric data by using using functions describing various distributions. For example, some random numbers from the normal distribution are:</p>
<pre><code>##  [1]  2.84589336 -0.12269543 -1.02897700  0.30225416  0.84246090 -1.70200563
##  [7] -0.33855292 -0.37052778  2.08541981 -0.03189712</code></pre>
<p>from the normal distribution with designated mean and standard deviation:</p>
<pre><code>##  [1] 48.39717 37.20291 29.51442 36.91876 37.46333 46.78928 22.87352 67.07184
##  [9] 24.57257 55.40510</code></pre>
<p>A poisson distribution with mean 2:</p>
<pre><code>##  [1] 0 2 2 2 1 1 2 1 1 3</code></pre>
<p>and the <span class="math inline">\(\chi^2\)</span> distribution with 1 degree of freedom:</p>
<pre><code>##  [1] 0.0013707733 5.4989043896 0.0006194959 0.0645389172 0.0073757360
##  [6] 1.6181433787 0.4727262252 1.0108424510 0.0892304584 1.7073369898</code></pre>
<p>There are several more distributions that if you need to access random numbers, quantiles, probability densities, and cumulative density values are available.</p>
</div>
<div id="b.-coercion-to-numeric-1" class="section level5">
<h5>b. Coercion to Numeric</h5>
<p>All data types have the potential ability to take another variable and coerce it into their type. Some combinations make sense, and some do not. For example, if you load in a CSV data file using read_csv(), and at some point a stray non-numeric character was inserted into one of the cells on your spreadsheet, R will interpret the entire column as a character type rather than as a numeric type. This can be a very frustrating thing, spreadsheets should generally be considered evil as they do all kinds of stuff behind the scenes and make your life less awesome.</p>
<p>Here is an example of coercion of some data that is initially defined as a set of characters</p>
<pre><code>## [1] &quot;42&quot; &quot;99&quot;</code></pre>
<p>and is coerced into a numeric type using the as.numeric() function.</p>
<pre><code>## [1] 42 99</code></pre>
<p>It is a built-in feature of the data types in R that they all have (or should have if someone is producing a new data type and is being courteous to their users) an <code>as.X()</code> function. This is where the data type decides if the values asked to be coerced are reasonable or if you need to be reminded that what you are asking is not possible. Here is an example where I try to coerce a non-numeric variable into a number.</p>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre><code>## [1] NA</code></pre>
<p>By default, the result should be NA (missing data/non-applicable) if you ask for things that are not possible.</p>
</div>
</div>
<div id="characters-1" class="section level4">
<h4>2.2. Characters</h4>
<div id="a.-character-data-1" class="section level5">
<h5>a. Character data</h5>
<p>A collection of letters, number, and or punctuation is represented as a character data type. These are enclosed in either single or double quotes and are considered a single entity. For example, my name can be represented as:</p>
<pre><code>## [1] &quot;Rodney J. Dyer&quot;</code></pre>
<p>In R, character variables are considered to be a single entity, that is the entire prof variable is a single unit, not a collection of characters. This is in part due to the way in which vectors of variables are constructed in the language. For example, if you are looking at the length of the variable I assigned my name to you see</p>
<pre><code>## [1] 1</code></pre>
<p>which shows that there is only one ‘character’ variable. If, as is often the case, you are interested in knowing how many characters are in the variable prof, then you use the</p>
<pre><code>## [1] 14</code></pre>
<p>function instead. This returns the number of characters (even the non-printing ones like tabs and spaces.</p>
<pre><code>## [1] 3</code></pre>
<p>As all other data types, you can define a vector of character values using the <code>c()</code> function.</p>
<pre><code>## [1] &quot;I am&quot;     &quot;not&quot;      &quot;a looser&quot;</code></pre>
<p>And looking at the <code>length()</code> and <code>nchar()</code> of this you can see how these operations differ.</p>
<pre><code>## [1] 3</code></pre>
<pre><code>## [1] 4 3 8</code></pre>
</div>
<div id="b.-concatenation-of-characters-1" class="section level5">
<h5>b. Concatenation of Characters</h5>
<p>Another common use of characters is concatenating them into single sequences. Here we use the function <code>paste()</code> and can set the separators (or characters that are inserted between entities when we collapse vectors). Here is an example, entirely fictional and only provided for instructional purposes only.</p>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
<pre><code>## [1] &quot;I am a looser&quot;</code></pre>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
</div>
<div id="c.-coercion-to-characters-1" class="section level5">
<h5>c. Coercion to Characters</h5>
<p>A character data type is often the most basal type of data you can work with. For example, consider the case where you have named sample locations. These can be kept as a character data type or as a factor (see below). There are benefits and drawbacks to each representation of the same data (see below). By default (as of the version of R I am currently using when writing this book), if you use a function like read_table() to load in an external file, columns of character data will be treated as factors. This can be good behavior if all you are doing is loading in data and running an analysis, or it can be a total pain in the backside if you are doing more manipulative analyses.</p>
<p>Here is an example of coercing a numeric type into a character type using the <code>as.character()</code> function.</p>
<pre><code>## [1] 42</code></pre>
<pre><code>## [1] &quot;42&quot;</code></pre>
</div>
</div>
<div id="factors-1" class="section level4">
<h4>2.3. Factors</h4>
<div id="a.-factor-vs.-character-1" class="section level5">
<h5>a. Factor vs. Character</h5>
<p>A factor is a categorical data type. If you are coming from SAS, these are class variables. If you are not, then perhaps you can think of them as mutually exclusive classifications. For example, an sample may be assigned to one particular locale, one particular region, and one particular species. Across all the data you may have several species, regions, and locales. These are finite, and defined, sets of categories. One of the more common headaches encountered by people new to R is working with factor types and trying to add categories that are not already defined.</p>
<p>Since factors are categorical, it is in your best interest to make sure you label them in as descriptive as a fashion as possible. You are not saving space or cutting down on computational time to take shortcuts and label the locale for Rancho Santa Maria as RSN or pop3d or 5. Our computers are fast and large enough, and our programmers are cleaver enough, to not have to rename our populations in numeric format to make them work (hello STRUCTURE I’m calling you out here). The only thing you have to loose by adopting a reasonable naming scheme is confusion in your output.</p>
<p>To define a factor type, you use the function <code>factor()</code> and pass it a vector of values.</p>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: East North South West</code></pre>
<p>When you print out the values, it shows you all the levels present for the factor. If you have levels that are not present in your data set, when you define it, you can tell R to consider additional levels of this factor by passing the optional levels= argument as:</p>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: North South East West Central</code></pre>
<p>If you try to add a data point to a factor list that does not have the factor that you are adding, it will give you an error (or ‘barf’ as I like to say).</p>
<pre><code>## Warning in `[&lt;-.factor`(`*tmp*`, 1, value = &quot;Bob&quot;): invalid factor level, NA
## generated</code></pre>
<p>Now, I have to admit that the Error message in its entirety, with its <code>“[&lt;-.factor</code>(<code>*tmp*</code>, 1, value = “Bob”)“` part is, perhaps, not the most informative. Agreed. However, the “invalid factor level” does tell you something useful. Unfortunately, the programmers that put in the error handling system in R did not quite adhere to the spirit of the “fail loudly” mantra. It is something you will have to get good at. Google is your friend, and if you post a questions to (<a href="http://stackoverflow.org" class="uri">http://stackoverflow.org</a>) or the R user list without doing serious homework, put on your asbestos shorts!</p>
<p>Unfortunately, the error above changed the first element of the region vector to NA (missing data). I’ll turn it back before we move too much further.</p>
<p>Factors in R can be either unordered (as say locale may be since locale A is not <code>&gt;</code>, <code>=</code>, or <code>&lt;</code> locale B) or they may be ordered categories as in <code>Small &lt; Medium &lt; Large &lt; X-Large</code>. When you create the factor, you need to indicate if it is an ordered type (by default it is not). If the factors are ordered in some way, you can also create an ordination on the data. If you do not pass a levels= option to the <code>factors()</code> function, it will take the order in which they occur in data you pass to it. If you want to specify an order for the factors specifically, pass the optional <code>levels=</code> and they will be ordinated in the order given there.</p>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
</div>
<div id="b.-missing-levels-in-factors-1" class="section level5">
<h5>b. Missing Levels in Factors</h5>
<p>There are times when you have a subset of data that do not have all the potential categories.</p>
<pre><code>## [1] South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
<pre><code>## subregion
##  West North South  East 
##     3     0     2     2</code></pre>
</div>
</div>
<div id="logical-types-1" class="section level4">
<h4>2.4. Logical Types</h4>
<p>A logical type is either TRUE or FALSE, there is no in-between. It is common to use these types in making decisions (see if-else decisions) to check a specific condition being satisfied. To define logical variables you can either use the TRUE or FALSE directly</p>
<pre><code>## [1] FALSE  TRUE FALSE FALSE FALSE</code></pre>
<p>or can implement some logical condition</p>
<pre><code>## [1] FALSE  TRUE</code></pre>
<p>on the variables. Notice here how each of the items is actually evaluated as to determine the truth of each expression. In the first case, the character is not equal to zero and in the second, the number of characters (what <code>nchar()</code> does) is indeed equal to 8 for the character string “Marshawn.”</p>
<p>It is common to use logical types to serve as indices for vectors. Say for example, you have a vector of data that you want to select some subset from.</p>
<pre><code>##  [1]  1.45010950 -0.99521537 -1.06561710 -0.81785934 -1.14479521  0.49352335
##  [7] -0.46075136  0.45053814 -0.25209687 -0.68123799  2.47974375  1.02343809
## [13]  0.76239990  0.48381964 -0.79725996 -1.51504379 -0.85361262 -0.41785004
## [19]  1.41630113 -0.01860237</code></pre>
<p>Perhaps you are on interested in the non-negative values</p>
<pre><code>## [1] 1.4501095 0.4935234 0.4505381 2.4797437 1.0234381 0.7623999 0.4838196
## [8] 1.4163011</code></pre>
<p>If you look at the condition being passed to as the index</p>
<pre><code>##  [1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE
## [13]  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE</code></pre>
<p>you see that individually, each value in the data vector is being evaluated as a logical value, satisfying the condition that it is strictly greater than zero. When you pass that as indices to a vector it only shows the indices that are <code>TRUE</code>.</p>
<p>You can coerce a value into a logical if you understand the rules. Numeric types that equal 0 (zero) are <code>FALSE</code>, always. Any non-zero value is considered <code>TRUE</code>. Here I use the modulus operator, <code>%%</code>, which provides the remainder of a division.</p>
<pre><code>##  [1] 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0</code></pre>
<p>which used as indices give us</p>
<pre><code>##  [1]  1.4501095 -1.0656171 -1.1447952 -0.4607514 -0.2520969  2.4797437
##  [7]  0.7623999 -0.7972600 -0.8536126  1.4163011</code></pre>
<p>You can get as complicated in the creation of indices as you like, even using logical operators such as OR and AND. I leave that as an example for you to play with.</p>
</div>
</div>
<div id="data-containers-1" class="section level3">
<h3>3. Data Containers</h3>
<p>We almost never work with a single datum<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>, rather we keep lots of data. Moreover, the kinds of data are often heterogeneous, including categorical (Populations, Regions), continuous (coordinates, rainfall, elevation), imagry (hyperspectral, LiDAR), and perhaps even genetic. R has a very rich set of containers into which we can stuff our data as we work with it. Here these container types are examined and the restrictions and benefits associated with each type are explained.</p>
<div id="vectors-1" class="section level4">
<h4>3.1. Vectors</h4>
<p>We have already seen several examples of several vectors in action (see the introduction to Numeric data types for example). A vector of objects is simply a collection of them, often created using the <code>c()</code> function (<em>c</em> for combine). Vectorized data is restricted to having homogeneous data types—you cannot mix character and numeric types in the same vector. If you try to mix types, R will either coerce your data into a reasonable type</p>
<pre><code>## [1] 1 2 3</code></pre>
<pre><code>## [1]  TRUE  TRUE FALSE</code></pre>
<pre><code>## [1] &quot;I&quot;      &quot;am&quot;     &quot;not&quot;    &quot;a&quot;      &quot;looser&quot;</code></pre>
<p>or coearce them into one type that is amenable to all the types of data that you have given it. In this example, a Logical, Character, Constant, and Function are combined resulting in a vector output of type Character.</p>
<pre><code>##  [1] &quot;TRUE&quot;             &quot;1&quot;                &quot;3.14159265358979&quot; &quot;canThrow&quot;        
##  [5] &quot;data&quot;             &quot;prof&quot;             &quot;region&quot;           &quot;stable&quot;          
##  [9] &quot;subregion&quot;        &quot;terms&quot;            &quot;x&quot;                &quot;y&quot;               
## [13] &quot;z&quot;</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Accessing elements within a vector are done using the square bracket <code>[]</code> notation. All indices (for vectors and matrices) start at 1 (not zero as is the case for some languages). Getting and setting the components within a vector are accomplished using numeric indices with the assignment operators just like we do for variables containing a single value.</p>
<pre><code>## [1] 1 2 3</code></pre>
<pre><code>## [1] 2 2 1</code></pre>
<pre><code>## [1] 2</code></pre>
<p>A common type of vector is that of a sequences. We use sequences all the time, to iterate through a list, to counting generations, etc. There are a few ways to generate sequences, depending upon the step sequence. For a sequence of whole numbers, the easiest is through the use of the colon operator.</p>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>This provides a nice shorthand for getting the values X:Y from X to Y, inclusive. It is also possible to go backwards using this operator, counting down from X to Y as in:</p>
<pre><code>## [1] 5 4 3 2</code></pre>
<p>The only constraint here is that we are limited to a step size of 1.0. It is possible to use non-integers as the bounds, it will just count up by 1.0 each time.</p>
<pre><code>## [1] 3.2 4.2 5.2 6.2 7.2 8.2</code></pre>
<p>If you are interested in making a sequence with a step other than 1.0, you can use the <code>seq()</code> function. If you do not provide a step value, it defaults to 1.0.</p>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>But if you do, it will use that instead.</p>
<pre><code>##  [1]  1  3  5  7  9 11 13 15 17 19</code></pre>
<p>It is also possible to create a vector of objects as repetitions using the <code>rep()</code> (for repeat) function.</p>
<pre><code>## [1] &quot;Beetlejuice&quot; &quot;Beetlejuice&quot; &quot;Beetlejuice&quot;</code></pre>
<p>If you pass a vector of items to <code>rep()</code>, it can repeat these as either a vector being repeated (the default value)</p>
<pre><code>## [1] &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot;</code></pre>
<p>or as each item in the vector repeated.</p>
<pre><code>## [1] &quot;No&quot;    &quot;No&quot;    &quot;No&quot;    &quot;Free&quot;  &quot;Free&quot;  &quot;Free&quot;  &quot;Lunch&quot; &quot;Lunch&quot; &quot;Lunch&quot;</code></pre>
</div>
<div id="matrices-1" class="section level4">
<h4>3.2. Matrices</h4>
<p>A matrix is a 2- or higher dimensional container, most commonly used to store numeric data types. There are some libraries that use matrices in more than two dimensions (rows and columns and sheets), though you will not run across them too often. Here I restrict myself to only 2-dimensional matrices.</p>
<p>You can define a matrix by giving it a set of values and an indication of the number of rows and columns you want. The easiest matrix to try is one with empty values:</p>
<pre><code>##      [,1] [,2]
## [1,]   NA   NA
## [2,]   NA   NA</code></pre>
<p>Perhaps more useful is one that is pre-populated with values.</p>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4</code></pre>
<p>Notice that here, there were four entries and I only specified the number of rows required. By default the ‘filling-in’ of the matrix will proceed down column (<em>by-column</em>). In this example, we have the first column with the first two entries and the last two entries down the second column. If you want it to fill by row, you can pass the optional argument</p>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4</code></pre>
<p>and it will fill <em>by-row</em>.</p>
<p>When filling matrices, the default size and the size of the data being added to the matrix are critical. For example, I can create a matrix as:</p>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4
## [3,]    5    6</code></pre>
<p>or</p>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<p>and both produce a similar matrix, only transposed.</p>
<pre><code>##      [,1] [,2] [,3]
## [1,] TRUE TRUE TRUE
## [2,] TRUE TRUE TRUE</code></pre>
<p>In the example above, the number of rows (or columns) was a clean multiple of the number of entries. However, if it is not, R will fill in values.</p>
<pre><code>## Warning in matrix(c(1, 2, 3, 4, 5, 6), ncol = 4, byrow = TRUE): data length [6]
## is not a sub-multiple or multiple of the number of columns [4]</code></pre>
<p>Notice how you get a warning from the interpreter. But that does not stop it from filling in the remaining slots by starting over in the sequence of numbers you passed to it.</p>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    1    2</code></pre>
<p>The dimensionality of a matrix (and <code>data.frame</code> as we will see shortly) is returned by the <code>dim()</code> function. This will provide the number of rows and columns as a vector.</p>
<pre><code>## [1] 2 4</code></pre>
<p>Accessing elements to retrieve or set their values within a matrix is done using the square brackets just like for a vector but you need to give <code>[row,col]</code> indices. Again, these are 1-based so that</p>
<pre><code>## [1] 3</code></pre>
<p>is the entry in the 1st row and 3rd column.</p>
<p>You can also use ‘slices’ through a matrix to get the rows</p>
<pre><code>## [1] 1 2 3 4</code></pre>
<p>or columns</p>
<pre><code>## [1] 3 1</code></pre>
<p>of data. Here you just omit the index for the entity you want to span. Notice that when you grab a slice, even if it is a column, is given as a vector.</p>
<pre><code>## [1] 2</code></pre>
<p>You can grab a sub-matrix using slices if you give a range (or sequence) of indices.</p>
<pre><code>##      [,1] [,2]
## [1,]    2    3
## [2,]    6    1</code></pre>
<p>If you ask for values from a matrix that exceed its dimensions, R will give you an error.</p>
<pre><code>## Error in X[1, 8] : subscript out of bounds
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>There are a few cool extensions of the <code>rep()</code> function that can be used to create matrices as well. They are optional values that can be passed to the function.</p>
<ul>
<li><code>times=x</code>: This is the default option that was occupied by the ‘3’ in the example above and represents the number of times that first argument will be repeated.<br />
</li>
<li><code>each=x</code> This will take each element in the first argument are repeat them <code>each</code> times.<br />
</li>
<li><code>length.out=x</code>: This make the result equal in length to <code>x</code>.</li>
</ul>
<p>In combination, these can be quite helpful. Here is an example using numeric sequences in which it is necessary to find the index of all entries in a 3x2 matrix. To make the indices, I bind two columns together using <code>cbind()</code>. There is a matching row binding function, denoted as <code>rbind()</code> (perhaps not so surprisingly). What is returned is a matrix</p>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1    5
## [2,]    1    2    5
## [3,]    1    3    5
## [4,]    2    1    5
## [5,]    2    2    5
## [6,]    2    3    5</code></pre>
</div>
<div id="lists-1" class="section level4">
<h4>3.3. Lists</h4>
<p>A list is a type of vector but is indexed by ‘keys’ rather than by numeric indices. Moreover, lists can contain heterogeneous types of data (e.g., values of different <code>class</code>), which is not possible in a vector type. For example, consider the list</p>
<pre><code>##          Length Class  Mode     
## x        20     -none- numeric  
## dog       5     -none- character
## hasStyle  5     -none- logical</code></pre>
<p>which is defined with a numeric, a character, and a logical component. Each of these entries can be different in length as well as type. Once defined, the entries may be observed as:</p>
<pre><code>## $x
##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40
## 
## $dog
## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;
## 
## $hasStyle
## [1] FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Once created, you can add variables to the list using the $-operator followed by the name of the key for the new entry.</p>
<p>or use double brackets and the name of the variable as a character string.</p>
<p>The keys currently in the list are given by the <code>names()</code> function</p>
<pre><code>## [1] &quot;x&quot;                   &quot;dog&quot;                 &quot;hasStyle&quot;           
## [4] &quot;my_favoriate_number&quot; &quot;lotto numbers&quot;</code></pre>
<p>Getting and setting values within a list are done the same way using either the <code>$</code>-operator</p>
<pre><code>##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or the double brackets</p>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or using a numeric index, but that numeric index is looks to the results of <code>names()</code> to figure out which key to use.</p>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;</code></pre>
<p>The use of the double brackets in essence provides a direct link to the variable in the list whose name is second in the <code>names()</code> function (<em>dog</em> in this case). If you want to access elements within that variable, then you add a second set of brackets on after the double ones.</p>
<pre><code>## [1] 6</code></pre>
<p>This deviates from the matrix approach as well as from how we access entries in a <code>data.frame</code> (described next). It is not a single square bracket with two indices, that gives you an error:</p>
<pre><code>## Error in theList[1, 3] : incorrect number of dimensions
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>List are rather robust objects that allow you to store a wide variety of data types (including nested lists). Once you get the indexing scheme down, it they will provide nice solutions for many of your computational needs.</p>
</div>
<div id="data-frames-1" class="section level4">
<h4>3.4. Data Frames</h4>
<div id="a.-data-frames-as-spreadsheets-1" class="section level5">
<h5>a. Data Frames as spreadsheets</h5>
<p>The <code>data.frame</code> is the default data container in R. It is analogous to both a spreadsheet, at least in the way that I have used spreadsheets in the past, as well as a database. If you consider a single spreadsheet containing measurements and observations from your research, you may have many columns of data, each of which may be a different kind of data. There may be <code>factors</code> representing designations such as species, regions, populations, sex, flower color, etc. Other columns may contain numeric data types for items such as latitude, longitude, dbh, and nectar sugar content. You may also have specialized columns such as dates collected, genetic loci, and any other information you may be collecting.</p>
<p>On a spreadsheet, each column has a unified data type, either quantified with a value or as a missing value, <code>NA</code>, in each row. Rows typically represent the sampling unit, perhaps individual or site, along which all of these various items have been measured or determined. A <code>data.frame</code> is similar to this, at least conceptually. You define a <code>data.frame</code> by designating the columns of data to be used. You do not need to define all of them, more can be added later. The values passed can be sequences, collections of values, or computed parameters. For example:</p>
<pre><code>##   ID Names Score
## 1  1   Bob    87
## 2  2 Alice    91
## 3  3 Vicki    92
## 4  4  John    81
## 5  5 Sarah    88</code></pre>
<p>You can see that each column is a unified type of data and each row is equivalent to a record. Additional data columns may be added to an existing data.frame as:</p>
<p>Since we may have many (thousands?) of rows of observations, a <code>summary()</code> of the data.frame can provide a more compact description.</p>
<pre><code>##        ID      Names       Score      Passed_Class   
##  Min.   :1   Alice:1   Min.   :81.0   Mode :logical  
##  1st Qu.:2   Bob  :1   1st Qu.:87.0   FALSE:1        
##  Median :3   John :1   Median :88.0   TRUE :4        
##  Mean   :3   Sarah:1   Mean   :87.8                  
##  3rd Qu.:4   Vicki:1   3rd Qu.:91.0                  
##  Max.   :5             Max.   :92.0</code></pre>
<p>We can add columns of data to the data.frame after the fact using the <code>$</code>-operator to indicate the column name. Depending upon the data type, the summary will provide an overview of what is there.</p>
</div>
<div id="b.-indexing-data-frames-1" class="section level5">
<h5>b. Indexing Data Frames</h5>
<p>You can access individual items within a <code>data.frame</code> by numeric index such as:</p>
<pre><code>## [1] 87</code></pre>
<p>You can slide indices along rows (which return a new <code>data.frame</code> for you)</p>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    87         TRUE</code></pre>
<p>or along columns (which give you a vector of data)</p>
<pre><code>## [1] 87 91 92 81 88</code></pre>
<p>or use the <code>$</code>-operator as you did for the list data type to get direct access to a either all the data or a specific subset therein.</p>
<pre><code>## [1] Vicki
## Levels: Alice Bob John Sarah Vicki</code></pre>
<p>Indices are ordered just like for matrices, rows first then columns. You can also pass a set of indices such as:</p>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    87         TRUE
## 2  2 Alice    91         TRUE
## 3  3 Vicki    92         TRUE</code></pre>
<p>It is also possible to use logical operators as indices. Here I select only those names in the data.frame whose score was &gt;90 and they passed popgen.</p>
<pre><code>## [1] Alice Vicki
## Levels: Alice Bob John Sarah Vicki</code></pre>
<p>This is why <code>data.frame</code> objects are very database like. They can contain lots of data and you can extract from them subsets that you need to work on. This is a VERY important feature, one that is vital for reproducible research. Keep you data in one and only one place.</p>
</div>
</div>
</div>
<div id="programming-1" class="section level3">
<h3>4. Programming</h3>
<p>One of the strengths of R as an analysis platform is that it is a language rather than a program. With programs, such as SPSS &amp; JMP, you are limited by the functionality that the designers thought would be necessary to meet the broadest audience. In R, you can rely upon simple functions or you can create entire analysis and simulation programs de novo. To do this, we need to dig into flow control and decision making processes, both of which you need for doing more in-depth programming.</p>
<div id="function-writing-1" class="section level4">
<h4>4.1. Function Writing</h4>
<p>Here we look at how to create an R function. Writing small functions like this is a huge benefit to you as an analyst and this is a great place to start. A function in R is defined as:</p>
<p>You define a function name for whatever you like and assign it the stuff to the right. In R, the function named <code>function()</code> is a special one, it tells R that you are about to create a little routine and you want that set of code to be available to you for later use under the name of whatever you named it. This allows a tremendous amount of flexibility as you develop your own set of routines and analyses for your work. The part that actually does stuff is after the function call. It may be that the function that you create does need some data (those are the arguments) or you may not need any input in to the function (in which you pass no arguments). It all depends upon what you are creating.</p>
<p>The key to understanding functions is that they are encapsulations of code—a shortcut for a sequence of instructions if you will not have to type over and over again. The less typing you do, the lower the probability that you will have errors (and all code has errors).</p>
<p>Here is an example of some code that I’m going to develop into a function. This function will allow me to determine if one genotype could possibly be the offspring of the other genotype.</p>
<pre><code>## 128:130 128:128</code></pre>
<p>We start out with two loci, a <code>128:130</code> heterozygote and a <code>128:128</code> homozygote. These may represent repeat motifs at a microsatellite locus or some other co-dominant genotype. First, I’ll break the locus into a vector of genotypes.</p>
<pre><code>## [1] &quot;128&quot; &quot;130&quot;</code></pre>
<pre><code>## [1] &quot;128&quot; &quot;128&quot;</code></pre>
<p>To be a valid potential offspring there should be at least one of the alleles in the parent that matches the allele in the offspring. The <code>intersect()</code> function returns the set of values common to both vectors.</p>
<pre><code>## [1] &quot;128&quot;</code></pre>
<p>If it has at least one of the alleles present (it could have both if parent and offspring are both the same heterozygote) then you cannot exclude this individual as a potential offspring. If there are no alleles in common, then the value returned is an empty vector.</p>
<pre><code>## character(0)</code></pre>
<p>This logic can be shoved into a function. You have to wrap it into a set of curly brackets. I use the length of the result from the intersect() to return from the function. Potential values for</p>
<p>Now, you can call this function anytime you need, just passing it two genotypes. If they can be offspring it returns TRUE, as in the comparison between 128:130 and 128:128 genotypes.</p>
<pre><code>## [1] TRUE</code></pre>
<p>And it returns FALSE for the comparison between 128:128 and 132:132.</p>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="variable-scope-1" class="section level4">
<h4>4.2. Variable Scope</h4>
<p>There is a lot more information on writing functions and we will get into that as we progress through the text. However, it is important that I bring this up now. The value assigned to a variable is defined by its scope. Consider the following code</p>
<p>and the function defined as</p>
<p>When I call the function, the variable x that is the argument of the function is not the same variable that is in the environment that I assigned a value of 10. The x in the function argument is what we call “local to that function” in that within the curly brackets that follow (and any number of curly brackets nested within those, the value of x is given whatever was passed to the function.</p>
</div>
<div id="decision-making-1" class="section level4">
<h4>4.3. Decision Making</h4>
<p>We interact with our data in many ways and introspection of the values we have in the variables we are working with are of prime importance. Decision making in your code is where you evaluate your data and make a choice of outcomes based upon some criteria. Here is some example data that we can use as we explore the basics of <code>if()</code>, <code>if(){} else{}</code>, and <code>if(){} elif(){} else{}</code> coding patterns.</p>
<div id="a.-the-if-pattern-1" class="section level5">
<h5>a. The if Pattern</h5>
<p>The most basic version of decision making is asking a single question and if the answer is TRUE then do something. The <code>if(){}</code> function does this and has the form</p>
<p>You pass a logical statement (or something that can be coerced into a logical type) to the function as the CRITERIA and if it evaluates to <code>TRUE</code>, then the contents of the <code>DO_SOMETHING</code> are executed. If the value of <code>CRITERIA</code> is not <code>TRUE</code> the <code>DO_SOMETHING</code> is skipped entirely—it is not even seen by the interpreter.</p>
<p>Here we can test this out using the loci defined above along with the is_heterozygote() function. This function takes one or more locus objects and returns TRUE/FALSE if they are or are not a heterozygote.</p>
<pre><code>## [1]  TRUE FALSE</code></pre>
<p>If we shove that function into the <code>if()</code> parameters we can use its evaluation of the heterozygous state of the locus to do something interesting, say tell us it is a heterozygote—it is admittedly a contrived example, but hey you try to make easy examples, it is not easy.</p>
<pre><code>## [1] &quot;It&#39;s a het!&quot;</code></pre>
<p>If the <code>is_heterozygote()</code> function returns a value of FALSE, then the contents of the <code>if()</code> function (the stuff within the curly brackets is skipped entirely.</p>
<p>Notice, there was no indication of any of that code inside the curly brackets.
The if-else Pattern
If there are more than on thing you want to potentially do when making a decision, you can add an else clause after the if pattern. Here if is_heterozygote() returns FALSE, the contents of the else{} clause will be executed. Here is the heterozygote example</p>
<pre><code>## 128:130 is a heterozygote</code></pre>
<p>and the homozygote one</p>
<pre><code>## 128:128 is a homozygote</code></pre>
<p>There is a slightly shorter version of this that is available for the lazy programmer and lets be honest, all programmers are lazy and the more you can accomplish with fewer strokes on the keyboard the better (this is how we got emacs and vim). I generally don’t teach the shortcuts up front, but this one is short and readily apparent so it may be more helpful than confusing. The <code>ifelse()</code> function has three parts, the condition, the result if <code>TRUE</code>, and the result if <code>FALSE</code>.</p>
<pre><code>## [1] &quot;heterozygote&quot; &quot;Not&quot;</code></pre>
<p>So iterating through the x vector, the condition <code>x&gt;0</code> is evaluated and if TRUE the sqrt() of the value is returned, else the NA is given. It is compact and easy to use so you may run into it often.</p>
</div>
<div id="b.-the-if-else-pattern-1" class="section level5">
<h5>b. The <code>if-else</code> Pattern</h5>
<p>It is possible to test many conditions in a single sequence by stringing together else-if conditions. The point that is important here is that the first condition that evaluates to TRUE will be executed and all remaining ones will be skipped, even if they also are logically TRUE. This means that it is important to figure out the proper order of asking your conditions. Here is an example function that determines if none, one, or both of the genotypes passed to it are heterozygotes. By default, I step through every one of the potential options of available on this comparison.<br />
1. The first is a heterozygote and the second one isn’t
2. The first one isn’t and the second one is
3. Both are heterozygotes
4. The last state (both are not)</p>
<p>Here is the function.</p>
<p>It is possible that the order of these CRITERIA could be changed, the important thing to remember is that the sequence of if - else if - else if etc. will terminate the very first time one of the CRITERIA is evaluated to be <code>TRUE</code>.</p>
</div>
</div>
<div id="flow-control-1" class="section level4">
<h4>4.4. Flow Control</h4>
<p>Flow control is the process of iterating across objects and perhaps doing operations on those objects. The R language has several mechanisms that you can use to control the flow of a script or bit of code.</p>
<div id="a.-the-for-loop-1" class="section level5">
<h5>a. The for() Loop</h5>
<pre><code>## [1] 3 8 5 4 6</code></pre>
<p>You can iterate through this vector using a for() loop. This is a simple function that has the form:</p>
<p>Where the <code>SOME_SEQUENCE</code> component is a sequence of values either specified OR calculated and the <code>DO_SOMETHING</code> is the thing you want to do with each of the values in the sequence. Usually, there is a variable defined in the <code>SOME_SEQUENCE</code> component and the value of that variable is used. Here are a few examples. The first goes through the existing vector directly and assigns (in sequential order) the entries of ‘x’ to the variable val. We can then do whatever we want with the value in val (though if we change it, nothing happens to the original x vector).</p>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>We can also specify a sequence directly and then use it as an index. Here I use an index variable named i to take on the integer seqeunce equal in length to the length of the original <code>x</code> variable. Then I can iterate through the original vector and use that index variable to grab the value I want.</p>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>Both give us the same output, namely a way to go through the variable <code>x</code>. However, there may be a need to use the latter approach in your calculations. For example, perhaps I want to do some other operation on the values. In this very contrived example that follows, I want to perform operations on the values in <code>x</code> depending on if they are even or odd. For the odd ones, I add the corresponding value in <code>y</code> and if not I subtract it. Sure, this is totally contrived and I cannot think of a reason why I would be doing this, but if I need to know what index (row, column or whatever) an entry is during the iteration process, then I need to use this approach over the <code>for( val in x)</code> approach.</p>
<pre><code>## [1] 4
## [1] 6
## [1] 8
## [1] 0
## [1] 1</code></pre>
</div>
<div id="b.-short-circuiting-the-loop-1" class="section level5">
<h5>b. Short Circuiting the Loop</h5>
<p>It is possible to short circuit the looping process using the keywords next and break, though in my programming style, I consider their use in my source files as evidence of inelegant code. That said, you may need them on occasion.</p>
<p>The next keyword basically stops all commands after that during the current iteration of the loop. It does not terminate the loop itself, it just stops the commands that follow it this time through. Here is an example that uses the modulus operator, <code>%%</code> (e.g., the remainder after division), to print out only those numbers that are divisible by three.</p>
<pre><code>## The value of i = 3 
## The value of i = 6 
## The value of i = 9 
## The value of i = 12 
## The value of i = 15 
## The value of i = 18</code></pre>
<p>The use of break to exit the loop entirely is perhaps more commonly encountered. When this keyword is encountered, the loop terminates immediately, as if it reached the send of the sequence.</p>
<pre><code>## The value of i= 1 
## The value of i= 2</code></pre>
</div>
</div>
</div>
<div id="r-graphics-1" class="section level3">
<h3>R Graphics</h3>
</div>
<div id="overview-3" class="section level3">
<h3>1. Overview</h3>
<p>This worked example is adapted from “Applied Population Genetics” by Rodney Dyer. The entire book is available here: <a href="http://dyerlab.github.io/applied_population_genetics/index.html" class="uri">http://dyerlab.github.io/applied_population_genetics/index.html</a></p>
<p>One of the most critical features of data analysis is the ability to present your results in a logical and meaningful fashion. R has built-in functions that can provide you graphical output that will suffice for your understanding and interpretations. However, there are also third-party packages that make some truly beautiful output. In this section, both built-in graphics and graphical output from the ggplot2 library are explained and highlighted.</p>
<p>We are going to use the venerable iris dataset that was used by Anderson (1935) and Fisher (1936). These data are measurements of four morphological variables (Sepal Length, Sepal Width, Petal Length, and Petal Width) measured on fifty individual iris plants from three recognized species. Here is a summary of this data set.</p>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
<p>I will also provide examples using two different plotting approaches. R has a robust set of built-in graphical routines that you can use. However, the development community has also provided several additional graphics libraries available for creating output. The one I prefer is <code>ggplot2</code> written by Hadley Wickham. His approach in designing this library a philosophy of graphics depicted in Leland Wilkson’s (2005) book <em>The Grammar of Graphics</em>. As I understand it, the idea is that a graphical display consists of several layers of information. These layers may include:</p>
<ul>
<li>The underlying data.<br />
</li>
<li>Mapping of the data onto one or more axes.<br />
</li>
<li>Geometric representations of data as points, lines, and/or areas.<br />
</li>
<li>Transformations of the axes into different coordinate spaces (e.g., cartesian, polar, etc.) or the data onto different scales (e.g., logrithmic)<br />
</li>
<li>Specification of subplots.</li>
</ul>
<p>In the normal plotting routines discussed before, configuration of these layers were specified as arguments passed to the plotting function (<code>plot()</code>, <code>boxplot()</code>, etc.). The ggplot2 library takes a different approach, allowing you to specify these components separately and literally add them together like components of a linear model.</p>
<p>Required packages:</p>
</div>
<div id="univariate-plots-1" class="section level3">
<h3>2. Univariate plots</h3>
<div id="barplots-and-histograms-1" class="section level4">
<h4>2.1. Barplots and histograms</h4>
<p>Univariate data can represent either counts (e.g., integers) of items or vectors of data that have decimal components (e.g., frequency distributions, etc.). If the sampling units are discrete, then a the <code>barplot()</code> function can make a nice visual representation. Here is an example using some fictions data.</p>
<pre><code>##    Bob  Alice   Jane   Fred Barney   Lucy 
##      2      3      6      3      2      4</code></pre>
<p>From this, a barplot can be constructed where the x-axis has discrete entities for each name and the y-axis represents the magnitude of whatever it is we are measuring.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Notice here that I included labels for both the x- and y-axes. You do this by inserting these arguments into the parameters passed to the <code>barplot()</code> (it is the same for all built-in plotting as we will see below).</p>
<p>To use <code>ggplot</code> for displaying this, you have to present the data in a slightly different way. There are shortcuts using the <code>qplot()</code> function but I prefer to use the more verbose approach. Here is how we would plot the same output using ggplot.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p>There are a couple of things to point out about this.</p>
<ol style="list-style-type: decimal">
<li>This is a compound statement, the plotting commands are literally ‘added together.’</li>
<li>The <code>ggplot()</code> function specifies a <code>data.frame</code> from which your data will be extracted.</li>
<li>The <code>aes()</code> component within the <code>ggplot()</code> function describes the aesthetics of the plot. This is how you designate which variable columns in the <code>data.frame</code> will be on the x- and y- axes, colors, plot shapes, categories, etc.</li>
<li>To the basic description of the data and aesthetics, a geometry is added, that of a barplot. If necessary, you can pass additional information to the <code>geom_bar()</code> function. In this case, I had to tell it that you use the raw data <code>stat='identity'</code> instead of trying to summarize many observations.<br />
</li>
<li>The axis labels are taken directly from the names of the columns in the <code>data.frame</code>.</li>
</ol>
<p>If the data on the x-axis is not discrete but measured on a single variable, then the <code>hist()</code> function can take the data and categorize it into groups based upon the density of the underlying data.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<p>The <code>hist()</code> function itself returns a bit of information that may be of interest. It is not necessary that you capture these data, R will ignore it if you do not assign it to a variable. What is of interest though is that it returns a <code>list()</code> object with the following keys:</p>
<pre><code>## [1] &quot;breaks&quot;   &quot;counts&quot;   &quot;density&quot;  &quot;mids&quot;     &quot;xname&quot;    &quot;equidist&quot;</code></pre>
<p>The data within these keys can be accessed directly as:</p>
<pre><code>## $breaks
## [1] 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0
## 
## $counts
## [1]  5 27 27 30 31 18  6  6
## 
## $density
## [1] 0.06666667 0.36000000 0.36000000 0.40000000 0.41333333 0.24000000 0.08000000
## [8] 0.08000000
## 
## $mids
## [1] 4.25 4.75 5.25 5.75 6.25 6.75 7.25 7.75
## 
## $xname
## [1] &quot;iris$Sepal.Length&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<p>and provide the basic information on how to construct the histogram as shown below. The values defined for the break locations for each of the bars and the midpoints are the default ones for the <code>hist()</code> function. If you wish, you can provide the number of breaks in the data, the location of the breaks, including the lowest and highest terms, plot as a count versus a frequency, etc.</p>
<p>The corresponding <code>ggplot</code> approach is</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-124-1.png" width="672" /></p>
<p>which also takes a few liberties with the default binning parameters.</p>
<p>By default, both the R and <code>ggplot</code> approches make a stab at creating enough of the meta data around the plot to make it somewhat useful. However, it is helpful if we add a bit to that and create graphics that suck just a little bit less. There are many options that we can add to the standard plot command to make it more informative and/or appropriate for your use. The most common ones include:</p>
<ul>
<li><code>xlab</code> Change the label on the x-axis<br />
</li>
<li><code>ylab</code> Change the lable on the y-axis</li>
<li><code>main</code> Change the title of the graph</li>
<li><code>col</code> Either a single value, or a vector of values, indicating the color to be plot.</li>
<li><code>xlim/ylim</code> The limits for the x- and y-axes.</li>
</ul>
<p>Additional options are given in tabular form in the next section.</p>
<p>Here is another plot of the same data but spiffied up a bit.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-125-1.png" width="672" /></p>
<p>A few things to notice:</p>
<ol style="list-style-type: decimal">
<li>The main title over the top of the image was visually removed by assigning an empty characters string to it.<br />
</li>
<li>The color parameter refers to the fill color of the bars, not the border color.</li>
</ol>
<p>In <code>ggplot</code> we add those additional components either to the geometry where it is defined (e.g., the color in the geom_bar) or to the overall plot (as in the addition of labels on the axes).</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
</div>
<div id="plotting-parameters-1" class="section level4">
<h4>2.2. Plotting Parameters</h4>
<p>There are several parameters common to the various plotting functions used in the basic R plotting functions. Here is a short table of the most commonly used ones.</p>
<table>
<colgroup>
<col width="11%" />
<col width="23%" />
<col width="64%" />
</colgroup>
<thead>
<tr class="header">
<th>Command</th>
<th>Usage</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bg</td>
<td>bg=“white”</td>
<td>Sets the background color for the entire figure.</td>
</tr>
<tr class="even">
<td>bty</td>
<td>bty=“n”</td>
<td>Sets the style of the box type around the graph. Useful values are “o” for complete box (the default), “l,” “7,” “c,” “u,” “]” which will make a box with sides around the plot area resembling the upper case version of these letters, and “n” for no box.</td>
</tr>
<tr class="odd">
<td>cex</td>
<td>cex=2</td>
<td>Magnifies the default font size by the corresponding factor.</td>
</tr>
<tr class="even">
<td>cex.axis</td>
<td>cex.axis=2</td>
<td>Magnifies the font size on the axes.</td>
</tr>
<tr class="odd">
<td>col</td>
<td>col=“blue”</td>
<td>Sets the plot color for the points, lines, etc.</td>
</tr>
<tr class="even">
<td>fg</td>
<td>fg=“blue”</td>
<td>Sets the foreground color for the image.</td>
</tr>
<tr class="odd">
<td>lty</td>
<td>lty=1</td>
<td>Sets the type of line as 0-none, 1-solid, 2-dashed, 3-dotted, etc.</td>
</tr>
<tr class="even">
<td>lwd</td>
<td>lwd=3</td>
<td>Specifies the width of the line.</td>
</tr>
<tr class="odd">
<td>main</td>
<td>main=“title”</td>
<td>Sets the title to be displayed over the top of the graph.</td>
</tr>
<tr class="even">
<td>mfrow</td>
<td>mfrow=c(2,2)</td>
<td>Creates a ‘matrix’ of plots in a single figure.</td>
</tr>
<tr class="odd">
<td>pch</td>
<td>pch=16</td>
<td>Sets the type of symbol to be used in a scatter plot.</td>
</tr>
<tr class="even">
<td>sub</td>
<td>sub=“subtitle”</td>
<td>Sets the subtitle under the main title on the graph.</td>
</tr>
<tr class="odd">
<td>type</td>
<td>type=“l”</td>
<td>Specifies the type of the graph to be shown using a generic plot() command. Types are “p” for points (default), “l” for lines, and “b” for both.</td>
</tr>
<tr class="even">
<td>xlab</td>
<td>xlab=“Size (m)”</td>
<td>Sets the label attached to the x-axis.</td>
</tr>
<tr class="odd">
<td>ylab</td>
<td>ylab=“Frequency”</td>
<td>Sets the label attached to the y-axis.</td>
</tr>
</tbody>
</table>
</div>
<div id="density-plots-1" class="section level4">
<h4>2.3. Density Plots</h4>
<p>Another way of looking at the distribution of univariate data is through the use of the <code>density()</code> function. This function takes a vector of values and creates a probability density function of it returning an object of class “density.”</p>
<pre><code>## $names
## [1] &quot;x&quot;         &quot;y&quot;         &quot;bw&quot;        &quot;n&quot;         &quot;call&quot;      &quot;data.name&quot;
## [7] &quot;has.na&quot;   
## 
## $class
## [1] &quot;density&quot;</code></pre>
<p>The <code>density()</code> function takes the univariate data and fits its density (internally represented by <code>d$y</code>) along the range of values (in <code>d$x</code>).</p>
<p>A plot can be produced using d as the variables as follows (with a bit of extra plotting parameters as depicted in the previous table).</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p>The corresponding <code>ggplot</code> approach is:</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
</div>
</div>
<div id="bivariate-plots-1" class="section level3">
<h3>3. Bivariate plots</h3>
<div id="overlaying-plots-by-grouping-1" class="section level4">
<h4>3.1. Overlaying Plots by grouping</h4>
<p>The data in the previous density plot represents the sepal lengths across all three iris species. It may be more useful to plot them as the density of each species instead of combined. Overlaying plots is a pretty easy feature built into the default R plotting functionalities.</p>
<p>Lets look at the data and see if the mean length differs across species. I do this using the <code>by()</code> command, which takes three parameters; the first parameter is the raw data you want to examine, the second one is the way you would like to partition that data, and the third one is the function you want to call on those groupings of raw data. This general form</p>
<p>mixing both data and functions to be used, is pretty common in R and you will see it over and over again. The generic call below asks to take the sepal data and partition it by species and estimate the mean.</p>
<pre><code>## iris$Species: setosa
## [1] 5.006
## ------------------------------------------------------------ 
## iris$Species: versicolor
## [1] 5.936
## ------------------------------------------------------------ 
## iris$Species: virginica
## [1] 6.588</code></pre>
<p>So there may be differences. Lets pull the data out and create density plots for each.</p>
<p>I can now plot the densities independently. After the first <code>plot()</code> function is called, you can add to it by using <code>lines()</code> or <code>points()</code> function calls. They will overlay the subsequent plots over the first one. One of the things you need to be careful of is that you need to make sure the x- and y-axes are properly scaled so that subsequent calls to <code>points()</code> or <code>lines()</code> does not plot stuff outside the boundaries of your initial plot.</p>
<p>Here I plot the setosa data first, specify the <code>xlim</code> (limits of the x-axis), set the color, and labels. On subsequent plotting calls, I do not specify labels but set alternative colors. Then a nice legend is placed on the graph, the coordinates of which are specified on the values of the x- and y-axis (I also dislike the boxes around graphic so I remove them as well with <code>bty="n"</code>).</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<p>A lot of that background material is unnecessary using <code>geom_density()</code> because we can specify to the plotting commands that the data are partitioned by the values contained in the <code>Species</code> column of the <code>data.frame</code>. This allows us to make this plot</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<p>or a correpsonding one using <code>fill=Species</code> instead (I set the alpha transparency to allow you to see the plots in the background).</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<p>We can use the <code>barplot()</code> function here as well and either stack or stagger the density of sepal lengths using discrete bars.</p>
<p>Here I make a matrix of bins using the <code>hist()</code> function with a specified set of breaks and then use it to plot discrete bin counts using the <code>barplot()</code> function. I include this example here because there are times when you want to produce a stacked bar plot (rarely) or a staggered barplot (more common) for some univariate data source and I always forget how to specifically do that.</p>
<pre><code>##            4 4.2 4.4 4.6 4.8  5 5.2 5.4 5.6 5.8 6 6.2 6.4 6.6 6.8 7 7.2 7.4 7.6
## setosa     0   4   5   7  12 11   6   2   3   0 0   0   0   0   0 0   0   0   0
## versicolor 0   0   0   0   3  2   1  10   8   6 6   5   3   4   2 0   0   0   0
## virginica  0   0   0   0   1  0   0   1   4   3 4  11   4   7   3 4   2   1   4
##            7.8
## setosa       0
## versicolor   0
## virginica    1</code></pre>
<p>The matrix of data</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
<p>Stacked barplots may or may not be that informative, depending upon the complexity of your underlying data. It is helpful though to be able to stagger them. In the basic <code>barplot()</code> function allows you to specify the bars to be spaced beside each other as:</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-138-1.png" width="672" /></p>
<p>For plotting onto a barplot object, the x-axis number is not based upon the labels on the x-axis. It is an integer that relates to the number of bar-widths and separations. In this example, there are three bars for each category plus one separator (e.g., the area between two categories). So I had to plot the legend at 60 units on the x-coordinate, which puts it just after the 15th category (e.g., 15*4=60).</p>
<p>We can do the same thing with <code>geom_histogram()</code>, though again with a bit less typing involved. Here is the raw plot (which by default stacks just like in the <code>barplot()</code> example)</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
<p>and the correspondingly staggered plot with bars positioned next to eachother.</p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-140-1.png" width="672" /></p>
<p>Notice how we add the fill color to the <code>aes()</code> function because the categories for assigning colors will be extracted from the <code>data.frame</code>, whereas when we just wanted to set them all light blue, the color is specified outside the <code>aes()</code> function. Also notice when we specify something to the <code>aes()</code> command in this way, we do not quote the name of the column, we call it just as if it were a normal variable.</p>
</div>
<div id="boxplots-1" class="section level4">
<h4>3.2. Boxplots</h4>
<p>Boxplots are a display of distributions of continuous data within categories, much like what we displayed in the previous staggered barplot. It is often the case that boxplots depict differences in mean values while giving some indication of the dispersal around that mean. This can be done in the staggered barplot as above but not quite as specifically.</p>
<p>The default display for boxplots in R provides the requires a factor and a numeric data type. The factor will be used as the categories for the x-axis on which the following visual components will be displayed:</p>
<ul>
<li>The median of the data for each factor,<br />
</li>
<li>An optional 5% confidence interval (shown by passing notch=TRUE) around the mean.</li>
<li>The inner 50th percentile of the data,<br />
</li>
<li>Outlier data points.</li>
</ul>
<p>Here is how the sepal length can be plot as a function of the Iris species.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-141-1.png" width="672" /></p>
<p>A couple of things should be noted on this plot call. First, I used a ‘functional’ form for the relationship between the continuous variable (<code>Sepal.Length</code>) and the factor (<code>Species</code>) with the response variable indicated on the left side of the tilde and the predictor variables on the right side. It is just as reasonable to use <code>boxplot(Species,Sepal.Length, ...)</code> in the call as x- and y- variables in the first two positions. However, it reads a bit better to do it as a function, like a regression. Also, it should be noted that I added the optional term, <code>data=iris</code>, to the call. This allowed me to reference the columns in the iris data.frame without the dollar sign notation. Without that I would have had to write <code>boxplot( data$Sepal.Length ~ data$Species, ...)</code>, a much more verbose way of doing it but most programmers are relatively lazy and anything they can do to get more functionality out of less typing… Finally, I set <code>frame.plot=FALSE</code> to remove the box around the plot since the <code>bty="n"</code> does not work on boxplots (big shout out for consistency!). I don’t know why these are different, I just hate the box.</p>
<p>The corresponding <code>ggplot</code> approach is the same as the <code>boxplot()</code> one, we just have to specify the <code>notch=TRUE</code> in the <code>geom_boxplot()</code> function.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-142-1.png" width="672" /></p>
</div>
<div id="scatter-plots-1" class="section level4">
<h4>3.3. Scatter Plots</h4>
<p>With two sets of continuous data, we can produce scatter plots. These consist of 2- (or 3-) coordinates where we can plot our data. With the addition of alternative colors (<code>col=</code>) and/or plot shapes (<code>pch=</code>) passed to the generic plot() command, we can make really informative graphical output. Here I plot two characteristics of the iris data set, sepal length and width, and use the species to indicate alternative symbols.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-143-1.png" width="672" /></p>
<p>The call to <code>pch=</code> that I used coerced a factor into a numeric data type. By default, this will create a numeric sequence (starting at 1) for all levels of the factor, including ones that may not be in the data you are doing the conversion on. The parameter passed to <code>pch</code> is an integer that determines the shape of the symbol being plot. I typically forget which numbers correspond to which symbols (there are 25 of them in total ) and have to look them up when I need them. One of the easiest ways is just to plot them as:</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<p>which produces the following figure where you can choose the appropriate symbols for your plotting needs.</p>
<p>A scatter plot in <code>ggplot</code> is created using the <code>geom_point()</code> layer.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-145-1.png" width="672" /></p>
<p>and the shapes are specified automatically.</p>
</div>
</div>
<div id="advanced-plotting-1" class="section level3">
<h3>4. Advanced plotting</h3>
<div id="multiple-plots-1" class="section level4">
<h4>4.1. Multiple Plots</h4>
<p>The last figure was a bit confusing. You can see a few points where the three species have the same measurements for both sepal length and width—both <em>I. versicolor</em> and <em>I. virginica</em> have examples with sepal widths of 3.0cm and lengths of 6.7cm. For some of these it would be difficult to determine using a graphical output like this if there were more overlap. In this case, it may be a more informative approach to make plots for each species rather than using different symbols.</p>
<p>In <code>ggplot</code>, there is a facet geometry that can be added to a plot that can pull apart the individual species plots (in this case) and plot them either next to each other (if you are looking at y-axis differences), on top of each other (for x-axis comparisons), or as a grid (for both x- and y- axis comparisons). This layer is added to the plot using <code>facet_grid()</code> and take a functional argument (as I used for the boxplot example above) on which factors will define rows and columns of plots. Here is an example where I stack plots by species.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<p>The <code>Species ~ .</code> means that the rows will be defined by the levels indicatd in <code>iris$Species</code> and all the plotting (the period part) will be done as columns. If you have more than one factor, you can specify <code>RowFactor ~ ColumnFactor</code> and it will make the corresponding grid.</p>
<p>I would argue that this is a much more intuitive display of differences in width than the previous plot.</p>
<p>You can achieve a similar effect using built-in plotting functions as well. To do this, we need to mess around a bit with the plotting attributes. These are default parameters (hence the name <code>par</code>) for plotting that are used each time we make a new graphic. Here are all of them (consult with the previous Table for some of the meanings).</p>
<pre><code>##  [1] &quot;xlog&quot;      &quot;ylog&quot;      &quot;adj&quot;       &quot;ann&quot;       &quot;ask&quot;       &quot;bg&quot;       
##  [7] &quot;bty&quot;       &quot;cex&quot;       &quot;cex.axis&quot;  &quot;cex.lab&quot;   &quot;cex.main&quot;  &quot;cex.sub&quot;  
## [13] &quot;cin&quot;       &quot;col&quot;       &quot;col.axis&quot;  &quot;col.lab&quot;   &quot;col.main&quot;  &quot;col.sub&quot;  
## [19] &quot;cra&quot;       &quot;crt&quot;       &quot;csi&quot;       &quot;cxy&quot;       &quot;din&quot;       &quot;err&quot;      
## [25] &quot;family&quot;    &quot;fg&quot;        &quot;fig&quot;       &quot;fin&quot;       &quot;font&quot;      &quot;font.axis&quot;
## [31] &quot;font.lab&quot;  &quot;font.main&quot; &quot;font.sub&quot;  &quot;lab&quot;       &quot;las&quot;       &quot;lend&quot;     
## [37] &quot;lheight&quot;   &quot;ljoin&quot;     &quot;lmitre&quot;    &quot;lty&quot;       &quot;lwd&quot;       &quot;mai&quot;      
## [43] &quot;mar&quot;       &quot;mex&quot;       &quot;mfcol&quot;     &quot;mfg&quot;       &quot;mfrow&quot;     &quot;mgp&quot;      
## [49] &quot;mkh&quot;       &quot;new&quot;       &quot;oma&quot;       &quot;omd&quot;       &quot;omi&quot;       &quot;page&quot;     
## [55] &quot;pch&quot;       &quot;pin&quot;       &quot;plt&quot;       &quot;ps&quot;        &quot;pty&quot;       &quot;smo&quot;      
## [61] &quot;srt&quot;       &quot;tck&quot;       &quot;tcl&quot;       &quot;usr&quot;       &quot;xaxp&quot;      &quot;xaxs&quot;     
## [67] &quot;xaxt&quot;      &quot;xpd&quot;       &quot;yaxp&quot;      &quot;yaxs&quot;      &quot;yaxt&quot;      &quot;ylbias&quot;</code></pre>
<p>To create multiple plots on one graphic, we need to modify either the mfrow or mfcol property (either will do). They represent the number of figures to plot as a 2-integer vector for rows and columns. By default, it is set to</p>
<pre><code>## [1] 1 1</code></pre>
<p>because there is only 1 row and 1 column in the plot. To change this, we simply pass a new value to the <code>par()</code> command and then do the plotting. In the following example, I plot the results of a linear model (<code>lm()</code>) function call. This returns four plots looking at the normality of the data, residuals, etc. This time, instead of seeing them one at a time, I’m going to plot all four into one figure.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
</div>
<div id="color-palettes-1" class="section level4">
<h4>4.2. Color Palettes</h4>
<p>The default plotting colors in R are black and white. However, there is a rich set of colors available for your plotting needs. The easiest set are named colors. At the time of this writing, there are</p>
<pre><code>## [1] 657</code></pre>
<p>different colors available for your use. Not all are distinct as some overlap. However the benefit of these colors is that they have specific names, making it easier for you to remember than RGB or hex representations. Here are a random set of 20 color names.</p>
<pre><code>##  [1] &quot;orange2&quot;         &quot;lightgrey&quot;       &quot;paleturquoise4&quot;  &quot;gray92&quot;         
##  [5] &quot;linen&quot;           &quot;grey17&quot;          &quot;tan4&quot;            &quot;maroon4&quot;        
##  [9] &quot;violetred1&quot;      &quot;gray59&quot;          &quot;orchid3&quot;         &quot;grey98&quot;         
## [13] &quot;darksalmon&quot;      &quot;lightsteelblue3&quot; &quot;gray85&quot;          &quot;gray23&quot;         
## [17] &quot;green&quot;           &quot;gray76&quot;          &quot;lightblue&quot;       &quot;mediumseagreen&quot;</code></pre>
<p>To use these colors you can call them by name in the col= option to a plot. Here is an example where I define three named colors and then coerce the <code>iris$Species</code> variable into an integer to select the color by species and plot it in a scatter plot (another version of the <code>pch=</code> example previously).</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-152-1.png" width="672" /></p>
<p>There is a lot of colors to choose from, and you are undoubtedly able to fit any color scheme on any presentation you may encounter.</p>
<p>In addition to named colors, there are color palettes available for you to grab the hex value for individual color along a pre-defined gradient. These colors ramps are:</p>
<ul>
<li><code>rainbow()</code>: A palette covering the visible spectrum<br />
</li>
<li><code>heat.colors()</code>: A palette ranging from red, through orange and yellow, to white.<br />
</li>
<li><code>terrain.colors()</code>: A palette for plotting topography with lower values as green and increasing through yellow, brown, and finally white.<br />
</li>
<li><code>topo.colors()</code>: A palette starting at dark blue (water) and going through green (land) and yellow to beige (mountains).<br />
</li>
<li><code>cm.colors()</code>: A palette going from light blue through white to pink.</li>
</ul>
<p>and are displayed in the following figure.</p>
<p>The individual palette functions return the hex value for an equally separated number of colors along the palette, you only need to ask for the number of colors you are requesting. Here is an example from the <code>rainbow()</code> function.</p>
<pre><code>##  [1] &quot;#FF0000FF&quot; &quot;#FF9900FF&quot; &quot;#CCFF00FF&quot; &quot;#33FF00FF&quot; &quot;#00FF66FF&quot; &quot;#00FFFFFF&quot;
##  [7] &quot;#0066FFFF&quot; &quot;#3300FFFF&quot; &quot;#CC00FFFF&quot; &quot;#FF0099FF&quot;</code></pre>
</div>
<div id="rcolorbrewer-1" class="section level4">
<h4>4.3. RColorBrewer</h4>
<p>The ggplot2 library has a slightly more interesting color palette, but it too is often a bit lacking. You have total control over the colors you produce and can specify them as RGB, hex (e.g. the way the web makes colors), or CMYK. You can also define your own color palettes.</p>
<p>To start, the RColorBrewer library provides several palettes for plotting either quantitative, qualitative, or divergent data. These three groups and the names of individual color palettes can be viewed as:</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p>In ggplot, we can use these palettes as follows.</p>
<p>You can change the default palette in ggplot output adding the <code>scale_color_brewer()</code> (and <code>scale_fill_brewer()</code> if you are doing fill colors like in a barplot) to the plot. Here is an example where I change the default palette to the 6th divergent palette.</p>
<p><img src="00-ReviewR_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
</div>
<div id="saving-imagery-1" class="section level4">
<h4>4.4. Saving Imagery</h4>
<p>Creating a graphic for display on your screen is only the first step. For it to be truly useful, you need to save it to a file, often with specific parameters such as DPI or image size, so that you can use it outside of R.</p>
<p>For normal R graphics, you can copy the current graphical device to a file using <code>dev.copy()</code> or you can create a graphic file object and plot directly to it instead of the display. In both cases, you will need to make sure that you have your graphic formatted the way you like. Once you have the file configured the way you like, decide on the image format you will want. Common ones are jpg, png, tiff and pdf. Here are the function arguments for each of the formats.</p>
<p>Notes: png is preferred over jpg because jpg compression results in loss. The command ‘pdf’ does not take a ‘units’ argument, it assumes that the unit is inches. Only the most commonly used arguments are listed here, for further arguments, see the help file for each function.</p>
<pre><code>jpeg(filename = &quot;Rplot%03d.jpeg&quot;,
     width = 480, height = 480, units = &quot;px&quot;, pointsize = 12)

png(filename = &quot;Rplot%03d.png&quot;,
    width = 480, height = 480, units = &quot;px&quot;, pointsize = 12, 
    bg = &quot;white&quot;,  res = 300)

tiff(filename = &quot;Rplot%03d.tiff&quot;,
     width = 480, height = 480, units = &quot;px&quot;, pointsize = 12, 
     compression = &quot;none&quot;, bg = &quot;white&quot;)
     
pdf(file = &quot;Rplot%03d.pdf&quot;,
    width = 6, height = 6, pointsize = 12, bg = &quot;white&quot;)</code></pre>
<p>These are the default values. If you need a transparent background, it is easiest to use the png file and set <code>bg="transparent"</code>. If you are producing an image for a publication, you will most likely be given specific parameters about the image format in terms of DPI, pointsize, dimensions, etc. They can be set here.</p>
<p>To create the image, call the appropriate function above, and a file will be created for your plotting. You must then call the plotting functions to create your graphic. Instead of showing up in a graphical display window, they will instead be plot to the file. When done you must tell R that your plotting is now finished and it can close the graphics file. This is done by calling dev.off(). Here is an example workflow saving an image of a scatter plot with a smoothed line through it using ggplot.</p>
<p>This will create a file MyCoolGraphic.png saved in the same folder as the current working directory.</p>
<p>To use <code>dev.copy()</code> instead, you first make the graphic and then copy the current graphic to a file. For this example, it would be:</p>
<p>In general, I prefer the first method as it allows me to specify the specifics of the file in an easier fashion than the second approach.</p>
<p>If you are using ggplot2 graphics, there is a built-in function ggsave() that can also be used to save your currently displaying graphic (or others if you so specify) to file. Here are the specifics on that function call.</p>
<p>Either approach will allow you to produce publication quality graphics.</p>
</div>
<div id="interactive-graphics-1" class="section level4">
<h4>4.5. Interactive Graphics</h4>
<p>There are several other libraries available for creating useful plots in R. The most dynamical ones are based on javascript and as such are restricted to web or ebook displays. Throughout this book, I will be showing how you can use various libraries to create interactive content as well as providing some ‘widgets’ that will demonstrate how some feature of popualtion or landscape structure changes under a specified model. These widgets are also written in R and are hosted online as a <a href="http://shiny.rstudio.org">shiny</a> application. I would encourage you to look into creating dynamcial reports using these techniques, they <em>can</em> facilitate a better understanding of the underlying biology than static approaches.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>The word <em>data</em> is plural, datum is singular<a href="review-of-r-skills-1.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="further-r-resources.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="further-r-resources-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
