<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.3 Worked Example | Landscape Genetic Data Analysis with R</title>
  <meta name="description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="5.3 Worked Example | Landscape Genetic Data Analysis with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  <meta name="github-repo" content="hhwagner1/LandGenCourse_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.3 Worked Example | Landscape Genetic Data Analysis with R" />
  
  <meta name="twitter:description" content="This is a web-interface to the teaching materials for the lab course ‘Landscape Genetic Data Analysis with R’ associated with the distributed graduate course ‘DGS Landscape Genetics.’ The output format is bookdown::gitbook." />
  

<meta name="author" content="Editor: Helene Wagner (University of Toronto)" />


<meta name="date" content="2022-04-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tutorial_2.html"/>
<link rel="next" href="r-exercise-week-2.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/d3-3.5.6/d3.min.js"></script>
<link href="libs/profvis-0.3.6.9000/profvis.css" rel="stylesheet" />
<script src="libs/profvis-0.3.6.9000/profvis.js"></script>
<script src="libs/profvis-0.3.6.9000/scroll.js"></script>
<link href="libs/highlight-6.2.0/textmate.css" rel="stylesheet" />
<script src="libs/highlight-6.2.0/highlight.js"></script>
<script src="libs/profvis-binding-0.3.7/profvis.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Landscape Genetic Data Analysis with R</a></li>

<li class="divider"></li>
<li class="part"><span><b>Getting Started<span></span></b></span></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i><b>1.1</b> How to use this Book<span></span></a>
<ul>
<li><a href="how-to-use-this-book.html#book-structure">1. Book Structure<span></span></a></li>
<li><a href="how-to-use-this-book.html#find-what-is-relevant-for-you">2. Find what is relevant for you<span></span></a></li>
<li><a href="how-to-use-this-book.html#course-r-package-landgencourse">3. Course R package ‘LandGenCourse’<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="list-of-packages.html"><a href="list-of-packages.html"><i class="fa fa-check"></i><b>1.2</b> List of R Packages by Vignette<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="review-of-r-skills.html"><a href="review-of-r-skills.html"><i class="fa fa-check"></i><b>2</b> Review of R Skills<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-r.html"><a href="basic-r.html"><i class="fa fa-check"></i><b>2.1</b> Basic R Programming<span></span></a>
<ul>
<li><a href="basic-r.html#overview">1. Overview<span></span></a></li>
<li><a href="basic-r.html#data-types">2. Data Types<span></span></a></li>
<li><a href="basic-r.html#data-containers">3. Data Containers<span></span></a></li>
<li><a href="basic-r.html#programming">4. Programming<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-graphics.html"><a href="r-graphics.html"><i class="fa fa-check"></i><b>2.2</b> R Graphics<span></span></a>
<ul>
<li><a href="r-graphics.html#overview-1">1. Overview<span></span></a></li>
<li><a href="r-graphics.html#univariate-plots">2. Univariate plots<span></span></a></li>
<li><a href="r-graphics.html#bivariate-plots">3. Bivariate plots<span></span></a></li>
<li><a href="r-graphics.html#advanced-plotting">4. Advanced plotting<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i><b>2.3</b> Further R resources<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="github-for-group-projects.html"><a href="github-for-group-projects.html"><i class="fa fa-check"></i><b>3</b> GitHub for Group Projects<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="github.html"><a href="github.html"><i class="fa fa-check"></i><b>3.1</b> Why use GitHub?<span></span></a>
<ul>
<li><a href="github.html#goals">1. Goals<span></span></a></li>
<li><a href="github.html#version">2. Watch course video: Version Control 101<span></span></a></li>
<li><a href="github.html#slides">3. Preview slides<span></span></a></li>
<li><a href="github.html#next-steps">4. Next steps<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>3.2</b> Installation<span></span></a>
<ul>
<li><a href="install.html#goals-1">1. Goals<span></span></a></li>
<li class="chapter" data-level="3.2.1" data-path="install.html"><a href="install.html#how-to-get-github-and-gitkraken-for-free"><i class="fa fa-check"></i><b>3.2.1</b> 2. How to get GitHub and GitKraken for free<span></span></a></li>
<li><a href="install.html#happygit">3. Happy Git with R<span></span></a></li>
<li><a href="install.html#gitvideos">4. Video tutorials: installation<span></span></a></li>
<li><a href="install.html#join">5. Joining your group’s project on GitHub<span></span></a></li>
<li><a href="install.html#repo">6. Setting up a group repo<span></span></a></li>
<li><a href="install.html#next-steps-1">7. Next steps<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="workflow.html"><a href="workflow.html"><i class="fa fa-check"></i><b>3.3</b> Workflows<span></span></a>
<ul>
<li><a href="workflow.html#goals-2">1. Goals<span></span></a></li>
<li><a href="workflow.html#step-by-step-tutorials">2. Step-by-step tutorials<span></span></a></li>
<li><a href="workflow.html#further-resources">3. Further resources<span></span></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Basic Topics<span></span></b></span></li>
<li class="chapter" data-level="4" data-path="Week1.html"><a href="Week1.html"><i class="fa fa-check"></i><b>4</b> Week 1: Importing Genetic Data<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="video_1.html"><a href="video_1.html"><i class="fa fa-check"></i><b>4.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_1.html#embedded-video">1. Embedded Video<span></span></a></li>
<li><a href="video_1.html#preview-slides">2. Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="tutorial_1.html"><a href="tutorial_1.html"><i class="fa fa-check"></i><b>4.2</b> Interactive Tutorial 1<span></span></a>
<ul>
<li><a href="tutorial_1.html#list-of-r-commands-covered-this-week">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_1.html#general-instructions">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="WE_1.html"><a href="WE_1.html"><i class="fa fa-check"></i><b>4.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_1.html#overview-of-worked-example">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_1.html#import-data-from-.csv-file">2. Import data from .csv file<span></span></a></li>
<li><a href="WE_1.html#create-genind-object">3. Create ‘genind’ Object<span></span></a></li>
<li><a href="WE_1.html#view-information-stored-in-genind-object">4. View information stored in ‘genind’ object<span></span></a></li>
<li><a href="WE_1.html#import-data-with-gstudio-package">5. Import data with ‘gstudio’ package<span></span></a></li>
<li><a href="WE_1.html#importing-snp-data">6. Importing SNP data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="r-exercise-week-1.html"><a href="r-exercise-week-1.html"><i class="fa fa-check"></i><b>4.4</b> R exercise Week 1<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="Week2.html"><a href="Week2.html"><i class="fa fa-check"></i><b>5</b> Week 2: Spatial Data<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="video_2.html"><a href="video_2.html"><i class="fa fa-check"></i><b>5.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_2.html#embedded-video-1">1. Embedded Video<span></span></a></li>
<li><a href="video_2.html#preview-slides-1">2. Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="tutorial_2.html"><a href="tutorial_2.html"><i class="fa fa-check"></i><b>5.2</b> Interactive Tutorial 2<span></span></a>
<ul>
<li><a href="tutorial_2.html#list-of-r-commands-covered-this-week-1">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_2.html#general-instructions-1">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="WE_2.html"><a href="WE_2.html"><i class="fa fa-check"></i><b>5.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_2.html#overview-of-worked-example-1">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_2.html#import-site-data-from-.csv-file">2. Import site data from .csv file<span></span></a></li>
<li><a href="WE_2.html#display-raster-data-and-overlay-sampling-locations-extract-data">3. Display raster data and overlay sampling locations, extract data<span></span></a></li>
<li><a href="WE_2.html#calculate-landscape-metrics">4. Calculate landscape metrics<span></span></a></li>
<li><a href="WE_2.html#sample-landscape-metrics-within-buffer-around-sampling-locations">5. Sample landscape metrics within buffer around sampling locations<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="r-exercise-week-2.html"><a href="r-exercise-week-2.html"><i class="fa fa-check"></i><b>5.4</b> R Exercise Week 2<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="bonus_2a.html"><a href="bonus_2a.html"><i class="fa fa-check"></i><b>5.5</b> Bonus: ‘sf’ and ‘terra’<span></span></a>
<ul>
<li><a href="bonus_2a.html#overview-2">1. Overview<span></span></a></li>
<li><a href="bonus_2a.html#convert-spatialpointsdataframe-to-sf-object">2. Convert ‘SpatialPointsDataFrame’ to ‘sf’ object<span></span></a></li>
<li><a href="bonus_2a.html#plot-variables-first-10-in-data-set">3. Plot variables (first 10 in data set)<span></span></a></li>
<li><a href="bonus_2a.html#export-site-data-as-esri-shapefile">4. Export site data as ESRI shapefile<span></span></a></li>
<li><a href="bonus_2a.html#use-terra-and-tmap-to-display-categorical-map-with-color-scheme">5. Use ‘terra’ and ‘tmap’ to display categorical map with color scheme<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Week3.html"><a href="Week3.html"><i class="fa fa-check"></i><b>6</b> Week 3: Genetic Diversity<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="video_3.html"><a href="video_3.html"><i class="fa fa-check"></i><b>6.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_3.html#embedded-video-2">1. Embedded Video<span></span></a></li>
<li><a href="video_3.html#video-part-1">Video, Part 1<span></span></a></li>
<li><a href="video_3.html#video-part-2">Video, Part 2<span></span></a></li>
<li><a href="video_3.html#preview-slides-2">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="tutorial_3.html"><a href="tutorial_3.html"><i class="fa fa-check"></i><b>6.2</b> Interactive Tutorial 3<span></span></a>
<ul>
<li><a href="tutorial_3.html#list-of-r-commands-covered-this-week-2">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_3.html#general-instructions-2">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="WE_3.html"><a href="WE_3.html"><i class="fa fa-check"></i><b>6.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_3.html#overview-of-worked-example-2">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_3.html#basic-checking-of-markers-and-populations">2. Basic checking of markers and populations<span></span></a></li>
<li><a href="WE_3.html#assess-genetic-diversity">3. Assess genetic diversity<span></span></a></li>
<li><a href="WE_3.html#aggregate-genetic-data-at-population-level-allele-frequencies">4. Aggregate genetic data at population level (allele frequencies)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="r-exercise-week-3.html"><a href="r-exercise-week-3.html"><i class="fa fa-check"></i><b>6.4</b> R Exercise Week 3<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Week4.html"><a href="Week4.html"><i class="fa fa-check"></i><b>7</b> Week 4: Metapopulations<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="video_4.html"><a href="video_4.html"><i class="fa fa-check"></i><b>7.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_4.html#embedded-video-3">1. Embedded Video<span></span></a></li>
<li><a href="video_4.html#video-part-1-1">Video, Part 1<span></span></a></li>
<li><a href="video_4.html#video-part-2-1">Video, Part 2<span></span></a></li>
<li><a href="video_4.html#preview-slides-3">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="tutorial_4.html"><a href="tutorial_4.html"><i class="fa fa-check"></i><b>7.2</b> Interactive Tutorial 4<span></span></a>
<ul>
<li><a href="tutorial_4.html#list-of-r-commands-covered-this-week-3">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_4.html#general-instructions-3">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="WE_4.html"><a href="WE_4.html"><i class="fa fa-check"></i><b>7.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_4.html#overview-of-worked-example-3">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_4.html#spatial-distribution-of-genetic-structure">2. Spatial distribution of genetic structure<span></span></a></li>
<li><a href="WE_4.html#what-determines-genetic-differentiation-among-sites">3. What determines genetic differentiation among sites?<span></span></a></li>
<li><a href="WE_4.html#what-determines-genetic-diversity">4. What determines genetic diversity?<span></span></a></li>
<li><a href="WE_4.html#are-genetic-differentiation-and-diversity-related">5. Are genetic differentiation and diversity related?<span></span></a></li>
<li><a href="WE_4.html#effect-of-recent-extinction-events">6. Effect of recent extinction events<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="r-exercise-week-4.html"><a href="r-exercise-week-4.html"><i class="fa fa-check"></i><b>7.4</b> R Exercise Week 4<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="Week5.html"><a href="Week5.html"><i class="fa fa-check"></i><b>8</b> Week 5: Spatial Statistics<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="video_5.html"><a href="video_5.html"><i class="fa fa-check"></i><b>8.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_5.html#embedded-video-4">1. Embedded Video<span></span></a></li>
<li><a href="video_5.html#preview-slides-4">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tutorial_5.html"><a href="tutorial_5.html"><i class="fa fa-check"></i><b>8.2</b> Interactive Tutorial 5<span></span></a>
<ul>
<li><a href="tutorial_5.html#list-of-r-commands-covered-this-week-4">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_5.html#general-instructions-4">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="WE_5.html"><a href="WE_5.html"><i class="fa fa-check"></i><b>8.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_5.html#overview-of-worked-example-4">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_5.html#data-import-and-manipulation">2. Data import and manipulation<span></span></a></li>
<li><a href="WE_5.html#calculate-genetic-distances">3. Calculate genetic distances<span></span></a></li>
<li><a href="WE_5.html#perform-a-mantel-test-to-test-for-ibd">4. Perform a Mantel test to test for IBD<span></span></a></li>
<li><a href="WE_5.html#create-mantel-correlogram-for-genetic-data">5. Create Mantel correlogram for genetic data<span></span></a></li>
<li><a href="WE_5.html#specify-spatial-weights-and-calculate-morans-i">6. Specify spatial weights and calculate Moran’s I<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="r-exercise-week-5.html"><a href="r-exercise-week-5.html"><i class="fa fa-check"></i><b>8.4</b> R Exercise Week 5<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="Week6.html"><a href="Week6.html"><i class="fa fa-check"></i><b>9</b> Week 6: Quantitative Genetics<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="video_6.html"><a href="video_6.html"><i class="fa fa-check"></i><b>9.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_6.html#embedded-video-5">1. Embedded Video<span></span></a></li>
<li><a href="video_6.html#video-part-1-2">Video, Part 1<span></span></a></li>
<li><a href="video_6.html#video-part-2-2">Video, Part 2<span></span></a></li>
<li><a href="video_6.html#preview-slides-5">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="tutorial_6.html"><a href="tutorial_6.html"><i class="fa fa-check"></i><b>9.2</b> Interactive Tutorial 6<span></span></a>
<ul>
<li><a href="tutorial_6.html#list-of-r-commands-covered-this-week-5">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_6.html#general-instructions-5">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="WE_6.html"><a href="WE_6.html"><i class="fa fa-check"></i><b>9.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_6.html#overview-of-worked-example-5">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_6.html#estimate-genetic-and-non-genetic-variance-components-from-a-common-garden-experiment">2. Estimate genetic and non-genetic variance components from a common garden experiment<span></span></a></li>
<li><a href="WE_6.html#estimate-trait-heritability">3. Estimate trait heritability<span></span></a></li>
<li><a href="WE_6.html#compare-q_st-to-f_st-measured-from-snp-data">4. Compare <span class="math inline">\(Q_{st}\)</span> to <span class="math inline">\(F_{st}\)</span> measured from SNP data<span></span></a></li>
<li><a href="WE_6.html#assess-correlation-between-trait-and-environment">5. Assess correlation between trait and environment<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="r-exercise-week-6.html"><a href="r-exercise-week-6.html"><i class="fa fa-check"></i><b>9.4</b> R Exercise Week 6<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Week7.html"><a href="Week7.html"><i class="fa fa-check"></i><b>10</b> Week 7: Spatial Linear Models<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="video_7.html"><a href="video_7.html"><i class="fa fa-check"></i><b>10.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_7.html#embedded-video-6">1. Embedded Video<span></span></a></li>
<li><a href="video_7.html#video-part-1-3">Video, Part 1<span></span></a></li>
<li><a href="video_7.html#video-part-2-3">Video, Part 2<span></span></a></li>
<li><a href="video_7.html#preview-slides-6">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="tutorial_7.html"><a href="tutorial_7.html"><i class="fa fa-check"></i><b>10.2</b> Interactive Tutorial 7<span></span></a>
<ul>
<li><a href="tutorial_7.html#list-of-r-commands-covered-this-week-6">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_7.html#general-instructions-6">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="WE_7.html"><a href="WE_7.html"><i class="fa fa-check"></i><b>10.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_7.html#overview-of-worked-example-6">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_7.html#explore-data-set">2. Explore data set<span></span></a></li>
<li><a href="WE_7.html#test-regression-residuals-for-spatial-autocorrelation">3. Test regression residuals for spatial autocorrelation<span></span></a></li>
<li><a href="WE_7.html#fit-models-with-spatially-correlated-error-gls-with-package-nlme">4. Fit models with spatially correlated error (GLS) with package ‘nlme’<span></span></a></li>
<li><a href="WE_7.html#fit-spatial-simultaneous-autoregressive-error-models-sar">5. Fit spatial simultaneous autoregressive error models (SAR)<span></span></a></li>
<li><a href="WE_7.html#spatial-filtering-with-mem-using-package-spmoran">6. Spatial filtering with MEM using package ‘spmoran’<span></span></a></li>
<li><a href="WE_7.html#fit-spatially-varying-coefficients-model-with-package-spmoran">7. Fit spatially varying coefficients model with package ‘spmoran’<span></span></a></li>
<li><a href="WE_7.html#model-with-patchsize-and-ibr">Model with PatchSize and IBR<span></span></a></li>
<li><a href="WE_7.html#model-with-ibr-only">Model with IBR only<span></span></a></li>
<li><a href="WE_7.html#conclusions">8. Conclusions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="r-exercise-week-7.html"><a href="r-exercise-week-7.html"><i class="fa fa-check"></i><b>10.4</b> R Exercise Week 7<span></span></a></li>
<li class="chapter" data-level="10.5" data-path="bonus_7a.html"><a href="bonus_7a.html"><i class="fa fa-check"></i><b>10.5</b> Bonus: Si index<span></span></a>
<ul>
<li><a href="bonus_7a.html#overview-of-bonus-materials">1. Overview of Bonus Materials<span></span></a></li>
<li><a href="bonus_7a.html#import-ecological-distance-matrices">2. Import ecological distance matrices<span></span></a></li>
<li><a href="bonus_7a.html#optimize-the-scaling-parameter-alpha">3. Optimize the scaling parameter alpha<span></span></a></li>
<li><a href="bonus_7a.html#calculate-hanskis-index-si-with-source-patch-parameters">4. Calculate Hanski’s index Si with source patch parameters<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Week8.html"><a href="Week8.html"><i class="fa fa-check"></i><b>11</b> Week 8: Simulation Experiments<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="video_8.html"><a href="video_8.html"><i class="fa fa-check"></i><b>11.1</b> View Course Video<span></span></a>
<ul>
<li><a href="video_8.html#embedded-video-7">1. Embedded Video<span></span></a></li>
<li><a href="video_8.html#video-part-1-4">Video, Part 1<span></span></a></li>
<li><a href="video_8.html#video-part-2-4">Video, Part 2<span></span></a></li>
<li><a href="video_8.html#preview-slides-7">Preview Slides<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="tutorial_8.html"><a href="tutorial_8.html"><i class="fa fa-check"></i><b>11.2</b> Interactive Tutorial 8<span></span></a>
<ul>
<li><a href="tutorial_8.html#list-of-r-commands-covered-this-week-7">1. List of R commands covered this week<span></span></a></li>
<li><a href="tutorial_8.html#general-instructions-7">2. General Instructions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="WE_8.html"><a href="WE_8.html"><i class="fa fa-check"></i><b>11.3</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_8.html#overview-of-worked-example-7">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_8.html#initialize-a-landscape">2. Initialize a landscape<span></span></a></li>
<li><a href="WE_8.html#define-simulation-parameters">3. Define simulation parameters<span></span></a></li>
<li><a href="WE_8.html#run-simulations-and-analyze-results">4. Run simulations and analyze results<span></span></a></li>
<li><a href="WE_8.html#run-simulator-using-a-previously-defined-parameter-set">5. Run simulator using a previously defined parameter set<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="r-exercise-week-8.html"><a href="r-exercise-week-8.html"><i class="fa fa-check"></i><b>11.4</b> R Exercise Week 8<span></span></a></li>
<li class="chapter" data-level="11.5" data-path="bonus_8a.html"><a href="bonus_8a.html"><i class="fa fa-check"></i><b>11.5</b> Bonus: Efficient R<span></span></a>
<ul>
<li><a href="bonus_8a.html#overview-of-bonus-material">1. Overview of Bonus Material<span></span></a></li>
<li><a href="bonus_8a.html#navigating-the-file-system">2. Navigating the file system<span></span></a></li>
<li><a href="bonus_8a.html#benchmarking-file-import-and-export-options">3. Benchmarking file import and export options<span></span></a></li>
<li><a href="bonus_8a.html#profiling-your-code">4. Profiling your code<span></span></a></li>
<li><a href="bonus_8a.html#creating-and-executing-a-bash-r-script">5. Creating and executing a Bash R script<span></span></a></li>
<li><a href="bonus_8a.html#parallelizing-code">6. Parallelizing code<span></span></a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Advanced Topics<span></span></b></span></li>
<li class="chapter" data-level="12" data-path="Week9.html"><a href="Week9.html"><i class="fa fa-check"></i><b>12</b> Week 9: Population Structure<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="WE_9.html"><a href="WE_9.html"><i class="fa fa-check"></i><b>12.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_9.html#overview-of-worked-example-8">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_9.html#simulated-data-2-island-model">2. Simulated data: 2-island model<span></span></a></li>
<li><a href="WE_9.html#simulated-data-2-island-model-with-admixture">3. Simulated data: 2-island model with admixture<span></span></a></li>
<li><a href="WE_9.html#empirical-data-threespine-sticklebacks">4. Empirical data: Threespine sticklebacks<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Week10.html"><a href="Week10.html"><i class="fa fa-check"></i><b>13</b> Week 10: Landscape Resistance<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="WE_10.html"><a href="WE_10.html"><i class="fa fa-check"></i><b>13.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_10.html#overview-of-worked-example-9">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_10.html#explore-the-data-set">2. Explore the data set<span></span></a></li>
<li><a href="WE_10.html#setting-cost-values-and-calculating-conductance">3. Setting cost values and calculating conductance<span></span></a></li>
<li><a href="WE_10.html#convert-conductance-into-effective-distance">4. Convert conductance into effective distance<span></span></a></li>
<li><a href="WE_10.html#create-cost-distance-matrices">5. Create cost-distance matrices<span></span></a></li>
<li><a href="WE_10.html#how-does-changing-resolution-affect-these-metrics">6. How does changing resolution affect these metrics?<span></span></a></li>
<li><a href="WE_10.html#references">7. References<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="bonus-10a.html"><a href="bonus-10a.html"><i class="fa fa-check"></i><b>13.2</b> Bonus: ‘radish’ tutorial<span></span></a>
<ul>
<li><a href="bonus-10a.html#overview-of-bonus-materials-1">1. Overview of Bonus Materials<span></span></a></li>
<li><a href="bonus-10a.html#import-data">2. Import data<span></span></a></li>
<li><a href="bonus-10a.html#basic-model-fitting">3. Basic model fitting<span></span></a></li>
<li><a href="bonus-10a.html#advanced-modeling-topics">4. Advanced modeling topics<span></span></a></li>
<li><a href="bonus-10a.html#summary">5. Summary<span></span></a></li>
<li><a href="bonus-10a.html#references-1">6. References<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="Week11.html"><a href="Week11.html"><i class="fa fa-check"></i><b>14</b> Week 11: Detecting Adaptation<span></span></a>
<ul>
<li class="chapter" data-level="14.1" data-path="WE_11.html"><a href="WE_11.html"><i class="fa fa-check"></i><b>14.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_11.html#overview-of-worked-example-10">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_11.html#import-and-prepare-the-data">2. Import and prepare the data<span></span></a></li>
<li><a href="WE_11.html#latent-factor-mixed-models-lfmm-a-univariate-gea">3. Latent Factor Mixed Models (LFMM): a univariate GEA<span></span></a></li>
<li><a href="WE_11.html#redundancy-analysis-rda-a-multivariate-gea">4. Redundancy Analysis (RDA): a multivariate GEA<span></span></a></li>
<li><a href="WE_11.html#compare-lfmm-and-rda-candidates">5. Compare LFMM and RDA candidates<span></span></a></li>
<li><a href="WE_11.html#a-quick-note-on-controlling-for-population-structure-in-rda">6. A quick note on controlling for population structure in RDA<span></span></a></li>
<li><a href="WE_11.html#references-2">7. References<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="Week12.html"><a href="Week12.html"><i class="fa fa-check"></i><b>15</b> Week 12: Model Selection<span></span></a>
<ul>
<li class="chapter" data-level="15.1" data-path="WE_12.html"><a href="WE_12.html"><i class="fa fa-check"></i><b>15.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_12.html#overview-of-worked-example-11">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_12.html#fitting-candidate-models">2. Fitting candidate models<span></span></a></li>
<li><a href="WE_12.html#your-turn-to-test-additional-hypotheses">3. Your turn to test additional hypotheses!<span></span></a></li>
<li><a href="WE_12.html#nested-model-nmlpe-for-hierarchical-sampling-designs">4. Nested model (NMLPE) for hierarchical sampling designs<span></span></a></li>
<li><a href="WE_12.html#references-3">5. References<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="Week13.html"><a href="Week13.html"><i class="fa fa-check"></i><b>16</b> Week 13: Gravity Models<span></span></a>
<ul>
<li class="chapter" data-level="16.1" data-path="WE_13.html"><a href="WE_13.html"><i class="fa fa-check"></i><b>16.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_13.html#overview-of-worked-example-12">1. Overview of Worked Example<span></span></a></li>
<li><a href="WE_13.html#setup">2. Setup<span></span></a></li>
<li><a href="WE_13.html#wetland-complex-data-preparation">3. Wetland complex data preparation<span></span></a></li>
<li><a href="WE_13.html#wetland-field-data-preparation">4. Wetland field-data preparation<span></span></a></li>
<li><a href="WE_13.html#saturated-graph">5. Saturated Graph<span></span></a></li>
<li><a href="WE_13.html#spatial-model-data-prepration">6. Spatial model data prepration<span></span></a></li>
<li><a href="WE_13.html#gravity-model">7. Gravity model<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="Week14.html"><a href="Week14.html"><i class="fa fa-check"></i><b>17</b> Week 14: Contemporary Gene Flow<span></span></a>
<ul>
<li class="chapter" data-level="17.1" data-path="WE_14.html"><a href="WE_14.html"><i class="fa fa-check"></i><b>17.1</b> Worked Example<span></span></a>
<ul>
<li><a href="WE_14.html#overview-3">1. Overview<span></span></a></li>
<li><a href="WE_14.html#import-genotypes">2. Import Genotypes<span></span></a></li>
<li><a href="WE_14.html#pollen-pool-genetic-structure">3. Pollen pool genetic structure<span></span></a></li>
<li><a href="WE_14.html#paternity-analysis">4. Paternity analysis<span></span></a></li>
<li><a href="WE_14.html#linking-paternity-to-ecological-variables">5. Linking paternity to ecological variables<span></span></a></li>
<li><a href="WE_14.html#references-4">6. References<span></span></a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Landscape Genetic Data Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="WE_2" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Worked Example<a href="WE_2.html#WE_2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Helene Wagner and Max Hesselbarth</p>
<p>There has been a lot of development recently in R regarding data types for geospatial data. We are currently in a transition period, where some packages still expect the “old” data types (based e.g. on packages <code>raster</code> and <code>sp</code>), others expect the “new” data types (based e.g. on packages <code>terra</code> and <code>sf</code>), and many accept both.</p>
<p>This vignette uses the older packages <code>raster</code> and <code>sp</code>, as these are still widely used and compatible with other functions used in landscape genetics. The bonus vignette uses the new packages <code>sf</code>, <code>terra</code>, and <code>tmap</code>, yet it can only scratch the surface.</p>
<p>For a thorough introduction to geocomputation with R, see this excellent Gitbook: <a href="https://geocompr.robinlovelace.net/index.html" class="uri">https://geocompr.robinlovelace.net/index.html</a>. Note: 2nd edition expected for spring 2022.</p>
<div id="overview-of-worked-example-1" class="section level3 unnumbered hasAnchor">
<h3>1. Overview of Worked Example<a href="WE_2.html#overview-of-worked-example-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This code builds on data and code from the <code>GeNetIt</code> package by Jeff Evans and Melanie Murphy. Landscape metrics will be calculated with the <code>landscapemetrics</code> package described in: Hesselbarth et al. (2019), Ecography 42: 1648-1657.</p>
<div id="a.-goals-1" class="section level4 unnumbered hasAnchor">
<h4>a. Goals<a href="WE_2.html#a.-goals-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This worked example shows:</p>
<ul>
<li>How to import spatial coordinates and site attributes as spatially referenced data.<br />
</li>
<li>How to plot raster data in R and overlay sampling locations.</li>
<li>How to calculate landscape metrics.</li>
<li>How to extract landscape data at sampling locations and within a buffer around them.</li>
</ul>
<p>Try modifying the code to import your own data!</p>
</div>
<div id="b.-data-set-1" class="section level4 unnumbered hasAnchor">
<h4>b. Data set<a href="WE_2.html#b.-data-set-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>This code uses landscape data and spatial coordinates from 30 locations where Colombia spotted frogs (<em>Rana luteiventris</em>) were sampled for the full data set analyzed by Funk et al. (2005) and Murphy et al. (2010). Please see the separate introduction to the data set.</p>
<ul>
<li>ralu.site: SpatialPointsDataFrame object with UTM coordinates (zone 11) in slot <code>@coords</code> and 17 site variables in slot <code>@data</code> for 31 sites. The data are included in the ‘GeNetIt’ package, for meta data type: ?ralu.site</li>
</ul>
<p>We will extract values at sampling point locations and within a local neighborhood (buffer) from six raster maps (see Murphy et al. 2010 for definitions), which are included with the <code>GeNetIt</code> package as a SpatialPixelsDataFrame called ‘rasters’:</p>
<ul>
<li>cti: Compound Topographic Index (“wetness”)</li>
<li>err27: Elevation Relief Ratio</li>
<li>ffp: Frost Free Period</li>
<li>gsp: Growing Season Precipitation</li>
<li>hli: Heat Load Index</li>
<li>nlcd: USGS Landcover (categorical map)</li>
</ul>
</div>
<div id="c.-required-r-packages-1" class="section level4 unnumbered hasAnchor">
<h4>c. Required R packages<a href="WE_2.html#c.-required-r-packages-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Install some packages needed for this worked example.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="WE_2.html#cb338-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">&quot;GeNetIt&quot;</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&quot;jeffreyevans/GeNetIt&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="WE_2.html#cb339-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LandGenCourse)</span>
<span id="cb339-2"><a href="WE_2.html#cb339-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(landscapemetrics)</span>
<span id="cb339-3"><a href="WE_2.html#cb339-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb339-4"><a href="WE_2.html#cb339-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sp)</span>
<span id="cb339-5"><a href="WE_2.html#cb339-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(raster)</span>
<span id="cb339-6"><a href="WE_2.html#cb339-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GeNetIt)</span>
<span id="cb339-7"><a href="WE_2.html#cb339-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span></code></pre></div>
</div>
</div>
<div id="import-site-data-from-.csv-file" class="section level3 unnumbered hasAnchor">
<h3>2. Import site data from .csv file<a href="WE_2.html#import-site-data-from-.csv-file" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="a.-import-data-into-spatialpointsdataframe" class="section level4 unnumbered hasAnchor">
<h4>a. Import data into SpatialPointsDataFrame<a href="WE_2.html#a.-import-data-into-spatialpointsdataframe" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The site data are already in a SpatialPointsDataFrame named <code>ralu.site</code> that comes with the package <code>GeNetIt</code>. Use <code>data(ralu.site)</code> to load it. This will create an object <code>ralu.site</code>.</p>
<p>To demonstrate how to create a SpatialPointsDataFrame, we create a simple data frame <code>Sites</code> with the coordinates and site data.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="WE_2.html#cb340-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ralu.site)</span>
<span id="cb340-2"><a href="WE_2.html#cb340-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(ralu.site)</span></code></pre></div>
<pre><code>## [1] &quot;SpatialPointsDataFrame&quot;
## attr(,&quot;package&quot;)
## [1] &quot;sp&quot;</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="WE_2.html#cb342-1" aria-hidden="true" tabindex="-1"></a>Sites <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(ralu.site<span class="sc">@</span>coords, ralu.site<span class="sc">@</span>data)</span>
<span id="cb342-2"><a href="WE_2.html#cb342-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(Sites)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="WE_2.html#cb344-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Sites)</span></code></pre></div>
<pre><code>##   coords.x1 coords.x2       SiteName        Drainage      Basin Substrate
## 1  688816.6   5003207   AirplaneLake ShipIslandCreek Sheepeater      Silt
## 2  688494.4   4999093 BachelorMeadow     WilsonCreek    Skyhigh      Silt
## 3  687938.4   5000223 BarkingFoxLake  WaterfallCreek    Terrace      Silt
## 4  689732.8   5002522   BirdbillLake      ClearCreek   Birdbill      Sand
## 5  690104.0   4999355        BobLake     WilsonCreek     Harbor      Silt
## 6  688742.5   4997481      CacheLake     WilsonCreek    Skyhigh      Silt
##                               NWI AREA_m2 PERI_m Depth_m  TDS FISH ACB   AUC
## 1                      Lacustrine 62582.2 1142.8   21.64  2.5    1   0 0.411
## 2 Riverine_Intermittent_Streambed   225.0   60.0    0.40  0.0    0   0 0.000
## 3                      Lacustrine 12000.0  435.0    5.00 13.8    1   0 0.300
## 4                      Lacustrine 12358.6  572.3    3.93  6.4    1   0 0.283
## 5                      Palustrine  4600.0  321.4    2.00 14.3    0   0 0.000
## 6                      Palustrine  2268.8  192.0    1.86 10.9    0   0 0.000
##   AUCV  AUCC   AUF AWOOD  AUFV
## 1    0 0.411 0.063 0.063 0.464
## 2    0 0.000 1.000 0.000 0.000
## 3    0 0.300 0.700 0.000 0.000
## 4    0 0.283 0.717 0.000 0.000
## 5    0 0.000 0.500 0.000 0.500
## 6    0 0.000 0.556 0.093 0.352</code></pre>
<p><strong>Question</strong>: What are the variable names for the spatial coordinates?</p>
<p>To illustrate importing spatial data from Excel, here we export the data as a csv file, import it again as a data frame, then convert it to a SpatialPointsDataFrame. First we create a folder <code>output</code> if it does not yet exist.</p>
<p>Note: to run the code, remove all the hashtags <code>#</code> at the beginning of the lines to uncomment them. This part assumes that you have writing permission on your computer. Alternatively, try setting up your R project folder on an external drive where you have writing permission.</p>
<p>The second line exports the data in <code>Sites</code> as a .csv file. The third line re-imports the .csv file to re-create data frame <code>Sites</code>.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="WE_2.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="co">#require(here)</span></span>
<span id="cb346-2"><a href="WE_2.html#cb346-2" aria-hidden="true" tabindex="-1"></a><span class="co">#if(!dir.exists(paste0(here(),&quot;/output&quot;))) dir.create(paste0(here(),&quot;/output&quot;))</span></span>
<span id="cb346-3"><a href="WE_2.html#cb346-3" aria-hidden="true" tabindex="-1"></a><span class="co">#write.csv(Sites, file=paste0(here(),&quot;/output/ralu.site.csv&quot;), </span></span>
<span id="cb346-4"><a href="WE_2.html#cb346-4" aria-hidden="true" tabindex="-1"></a><span class="co">#          quote=FALSE, row.names=FALSE)</span></span>
<span id="cb346-5"><a href="WE_2.html#cb346-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Sites &lt;- read.csv(paste0(here(),&quot;/output/ralu.site.csv&quot;), header=TRUE)</span></span></code></pre></div>
<p>The dataset <code>Sites</code> contains two columns with spatial coordinates and 17 attribute variables. So far, R treats the spatial coordinates like any other quantitative variables. To let R know this is spatial information, we import it into a spatial object type, a <code>SpatialPointsDataFrame</code> from the ‘sp’ package.</p>
<p>The conversion is done with the function <code>coordinates</code>, which takes a data frame and converts it to a spatial object of the same name. The code is not very intuitive.</p>
<p>Note: the tilde symbol <code>~</code> (here before the first coordinate) is often used in R formulas, we will see it again later. It roughly translates to “is modeled as a function of.”</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="WE_2.html#cb347-1" aria-hidden="true" tabindex="-1"></a>Sites.sp <span class="ot">&lt;-</span> Sites</span>
<span id="cb347-2"><a href="WE_2.html#cb347-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coordinates</span>(Sites.sp) <span class="ot">&lt;-</span> <span class="er">~</span>coords.x1<span class="sc">+</span>coords.x2</span></code></pre></div>
<p>Now R knows these are spatial data and knows how to handle them. It does not treat the coordinates as variables anymore, hence the first column is now <code>SiteName</code>.</p>
</div>
<div id="b.-add-spatial-reference-data" class="section level4 unnumbered hasAnchor">
<h4>b. Add spatial reference data<a href="WE_2.html#b.-add-spatial-reference-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Before we can combine the sampling locations with other spatial datasets, such as raster data, we need to tell R where on earth these locations are (georeferencing). This is done by specifying the “Coordinate Reference System” (CRS) or a <code>proj4</code> string.</p>
<p>For a visual explanation of projections and coordinate systems, see:
<a href="https://www.nwcg.gov/publications/pms437/mapping/using-gis" class="uri">https://www.nwcg.gov/publications/pms437/mapping/using-gis</a></p>
<p>For more information on CRS, see: <a href="https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf" class="uri">https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/OverviewCoordinateReferenceSystems.pdf</a></p>
<p>We know that these coordinates are UTM zone 11 (Northern hemisphere) coordinates. We define it here by its EPSG code (32611). You can search for EPSG codes here: <a href="https://epsg.io/32611" class="uri">https://epsg.io/32611</a>.</p>
<p>Here we call the function and the package simultaneously (this is good practice, as it helps keep track of where the functions in your code come from).</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="WE_2.html#cb348-1" aria-hidden="true" tabindex="-1"></a>sp<span class="sc">::</span><span class="fu">proj4string</span>(Sites.sp) <span class="ot">&lt;-</span> sp<span class="sc">::</span><span class="fu">CRS</span>(<span class="at">SRS_string =</span> <span class="st">&quot;EPSG:32611&quot;</span>)</span></code></pre></div>
<p>Note: this function only <strong>declares</strong> the existing projection, it does not change the coordinates to that projection.</p>
</div>
<div id="c.-change-projection" class="section level4 unnumbered hasAnchor">
<h4>c. Change projection<a href="WE_2.html#c.-change-projection" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In case we needed to <strong>transform</strong> the projection from UTM zone 11 to longitude/latitude (EPSG code: 4326), we could create a new <code>sp</code> object <code>Sites.sp.longlat</code>. We use the function <code>spTransform</code> to change the projection from the projection of the old object <code>Sites.sp</code> to the “longlat” coordinate system, which we define by the argument <code>CRSobj</code>.</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="WE_2.html#cb349-1" aria-hidden="true" tabindex="-1"></a>Sites.sp.longlat <span class="ot">&lt;-</span> sp<span class="sc">::</span><span class="fu">spTransform</span>(Sites.sp, </span>
<span id="cb349-2"><a href="WE_2.html#cb349-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">CRSobj =</span> sp<span class="sc">::</span><span class="fu">CRS</span>(<span class="at">SRS_string =</span> <span class="st">&quot;EPSG:4326&quot;</span>))</span>
<span id="cb349-3"><a href="WE_2.html#cb349-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Sites.sp.longlat<span class="sc">@</span>coords)</span></code></pre></div>
<pre><code>##   coords.x1 coords.x2
## 1 -114.5977  45.15708
## 2 -114.6034  45.12016
## 3 -114.6100  45.13047
## 4 -114.5864  45.15067
## 5 -114.5828  45.12208
## 6 -114.6008  45.10560</code></pre>
<p><strong>Question</strong>: Where on earth is this? You can enter the coordinates from the “longlat” projection in Google maps. Note that Google expects the Latitude (Y coordinate) first, then the Longitude (X coordinate). Here, coords.x1 is the longitude (X) and coords.x2 is the latitude (Y). Thus, to locate the first site in Google maps, you will need to enter <code>45.15708, -114.5977</code>. Where is it located?</p>
</div>
<div id="d.-access-data-in-spatialpointsdataframe" class="section level4 unnumbered hasAnchor">
<h4>d. Access data in ‘SpatialPointsDataFrame’<a href="WE_2.html#d.-access-data-in-spatialpointsdataframe" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>As an S4 object, Sites.sp has predefined slots. These can be accessed with the <code>@</code> symbol:</p>
<ul>
<li><code>@data</code>: the attribute data</li>
<li><code>@coords</code>: the spatial coordinates</li>
<li><code>@coords.nrs</code>: the column numbers of the input data from which the coordinates were taken (filled automatically)</li>
<li><code>@bbox</code>: bounding box, i.e., the minimum and maximum of x and y coordinates (filled automatically)</li>
<li><code>@proj4string</code>: the georeferencing information</li>
</ul>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="WE_2.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slotNames</span>(Sites.sp)</span></code></pre></div>
<pre><code>## [1] &quot;data&quot;        &quot;coords.nrs&quot;  &quot;coords&quot;      &quot;bbox&quot;        &quot;proj4string&quot;</code></pre>
<p>Here are the first few lines of the coordinates:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="WE_2.html#cb353-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Sites.sp<span class="sc">@</span>coords)</span></code></pre></div>
<pre><code>##   coords.x1 coords.x2
## 1  688816.6   5003207
## 2  688494.4   4999093
## 3  687938.4   5000223
## 4  689732.8   5002522
## 5  690104.0   4999355
## 6  688742.5   4997481</code></pre>
<p>And the proj4 string: Let’s compare this to the proj4string of the original <code>ralu.site</code> dataset.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="WE_2.html#cb355-1" aria-hidden="true" tabindex="-1"></a>Sites.sp<span class="sc">@</span>proj4string</span></code></pre></div>
<pre><code>## Coordinate Reference System:
## Deprecated Proj.4 representation:
##  +proj=utm +zone=11 +datum=WGS84 +units=m +no_defs 
## WKT2 2019 representation:
## PROJCRS[&quot;WGS 84 / UTM zone 11N&quot;,
##     BASEGEOGCRS[&quot;WGS 84&quot;,
##         ENSEMBLE[&quot;World Geodetic System 1984 ensemble&quot;,
##             MEMBER[&quot;World Geodetic System 1984 (Transit)&quot;],
##             MEMBER[&quot;World Geodetic System 1984 (G730)&quot;],
##             MEMBER[&quot;World Geodetic System 1984 (G873)&quot;],
##             MEMBER[&quot;World Geodetic System 1984 (G1150)&quot;],
##             MEMBER[&quot;World Geodetic System 1984 (G1674)&quot;],
##             MEMBER[&quot;World Geodetic System 1984 (G1762)&quot;],
##             ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##                 LENGTHUNIT[&quot;metre&quot;,1]],
##             ENSEMBLEACCURACY[2.0]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         ID[&quot;EPSG&quot;,4326]],
##     CONVERSION[&quot;UTM zone 11N&quot;,
##         METHOD[&quot;Transverse Mercator&quot;,
##             ID[&quot;EPSG&quot;,9807]],
##         PARAMETER[&quot;Latitude of natural origin&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8801]],
##         PARAMETER[&quot;Longitude of natural origin&quot;,-117,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8802]],
##         PARAMETER[&quot;Scale factor at natural origin&quot;,0.9996,
##             SCALEUNIT[&quot;unity&quot;,1],
##             ID[&quot;EPSG&quot;,8805]],
##         PARAMETER[&quot;False easting&quot;,500000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8806]],
##         PARAMETER[&quot;False northing&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8807]]],
##     CS[Cartesian,2],
##         AXIS[&quot;(E)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         AXIS[&quot;(N)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##     USAGE[
##         SCOPE[&quot;Engineering survey, topographic mapping.&quot;],
##         AREA[&quot;Between 120°W and 114°W, northern hemisphere between equator and 84°N, onshore and offshore. Canada - Alberta; British Columbia (BC); Northwest Territories (NWT); Nunavut. Mexico. United States (USA).&quot;],
##         BBOX[0,-120,84,-114]],
##     ID[&quot;EPSG&quot;,32611]]</code></pre>
<p>The default for <code>get_proj4("utm11")</code> results in a slightly different proj4string than the <code>ralu.site</code> dataset. The difference is in the <code>datum</code> argument (<code>WGS84</code> vs. <code>NAD83</code>):</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="WE_2.html#cb357-1" aria-hidden="true" tabindex="-1"></a>ralu.site<span class="sc">@</span>proj4string</span></code></pre></div>
<pre><code>## Coordinate Reference System:
## Deprecated Proj.4 representation:
##  +proj=utm +zone=11 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m
## +no_defs 
## WKT2 2019 representation:
## PROJCRS[&quot;unknown&quot;,
##     BASEGEOGCRS[&quot;unknown&quot;,
##         DATUM[&quot;North American Datum 1983&quot;,
##             ELLIPSOID[&quot;GRS 1980&quot;,6378137,298.257222101,
##                 LENGTHUNIT[&quot;metre&quot;,1]],
##             ID[&quot;EPSG&quot;,6269]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8901]]],
##     CONVERSION[&quot;UTM zone 11N&quot;,
##         METHOD[&quot;Transverse Mercator&quot;,
##             ID[&quot;EPSG&quot;,9807]],
##         PARAMETER[&quot;Latitude of natural origin&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8801]],
##         PARAMETER[&quot;Longitude of natural origin&quot;,-117,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8802]],
##         PARAMETER[&quot;Scale factor at natural origin&quot;,0.9996,
##             SCALEUNIT[&quot;unity&quot;,1],
##             ID[&quot;EPSG&quot;,8805]],
##         PARAMETER[&quot;False easting&quot;,500000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8806]],
##         PARAMETER[&quot;False northing&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8807]],
##         ID[&quot;EPSG&quot;,16011]],
##     CS[Cartesian,2],
##         AXIS[&quot;(E)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1,
##                 ID[&quot;EPSG&quot;,9001]]],
##         AXIS[&quot;(N)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1,
##                 ID[&quot;EPSG&quot;,9001]]]]</code></pre>
<p>Let’s go with the original information and copy it:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="WE_2.html#cb359-1" aria-hidden="true" tabindex="-1"></a>Sites.sp<span class="sc">@</span>proj4string <span class="ot">&lt;-</span> ralu.site<span class="sc">@</span>proj4string</span></code></pre></div>
</div>
</div>
<div id="display-raster-data-and-overlay-sampling-locations-extract-data" class="section level3 unnumbered hasAnchor">
<h3>3. Display raster data and overlay sampling locations, extract data<a href="WE_2.html#display-raster-data-and-overlay-sampling-locations-extract-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="a.-display-raster-data" class="section level4 unnumbered hasAnchor">
<h4>a. Display raster data<a href="WE_2.html#a.-display-raster-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The raster data for this project are already available in the package <code>GeNetIt</code>, under the name <code>rasters</code>, and we can load them with <code>data(rasters)</code>. They are stored as a <code>SpatialPixelsDataFrame</code>, another S4 object type from the <code>sp</code> package.</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb360-1"><a href="WE_2.html#cb360-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(rasters)</span>
<span id="cb360-2"><a href="WE_2.html#cb360-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(rasters)</span></code></pre></div>
<pre><code>## [1] &quot;SpatialPixelsDataFrame&quot;
## attr(,&quot;package&quot;)
## [1] &quot;sp&quot;</code></pre>
<p>However, raster data are better analyzed with the package <code>raster</code>, which has an object type <code>raster</code>. Let’s convert the data to a <code>RasterStack</code> of <code>RasterLayer</code> objects (i.e. a set of raster layers with the same spatial reference information).</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="WE_2.html#cb362-1" aria-hidden="true" tabindex="-1"></a>RasterMaps <span class="ot">&lt;-</span> <span class="fu">stack</span>(rasters)</span>
<span id="cb362-2"><a href="WE_2.html#cb362-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(RasterMaps)</span></code></pre></div>
<pre><code>## [1] &quot;RasterStack&quot;
## attr(,&quot;package&quot;)
## [1] &quot;raster&quot;</code></pre>
<p>Printing the name of the raster stack displays a summary. A few explanations:</p>
<ul>
<li><strong>dimensions</strong>: number of rows (nrow), number of columns (ncol), number of cells (ncell), number of layers (nlayers). So we see there are 6 layers in the raster stack.</li>
<li><strong>resolution</strong>: cell size is 30 m both in x and y directions (typical for Landsat-derived remote sensing data)</li>
<li><strong>coord.ref</strong>: projected in UTM zone 11, though the ‘datum’ (NAD83) is different than what we used for the sampling locations.</li>
</ul>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="WE_2.html#cb364-1" aria-hidden="true" tabindex="-1"></a>RasterMaps</span></code></pre></div>
<pre><code>## class      : RasterStack 
## dimensions : 426, 358, 152508, 6  (nrow, ncol, ncell, nlayers)
## resolution : 30, 30  (x, y)
## extent     : 683282.5, 694022.5, 4992833, 5005613  (xmin, xmax, ymin, ymax)
## crs        : +proj=utm +zone=11 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
## names      :          cti,        err27,          ffp,          gsp,          hli,         nlcd 
## min values : 8.429851e-01, 3.906551e-02, 0.000000e+00, 2.270000e+02, 1.014000e+03, 1.100000e+01 
## max values :   23.7147598,    0.7637643,   51.0000000,  338.0696716, 9263.0000000,   95.0000000</code></pre>
<p>Now we can use <code>plot</code>, which knows what to do with a raster stack.</p>
<p>Note: layer <code>nlcd</code> is a categorical map of land cover types. See this week’s bonus materials for how to better display a categorical map in R.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="WE_2.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(RasterMaps)</span></code></pre></div>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-22-1.png" width="768" /></p>
<p>Some layers seem to show a similar pattern. It is easy to calculate the correlation between quantitative raster layers. Here, the last layer <code>ncld</code>, is in fact categorical (land cover type), and it’s correlation here is meaningless.</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="WE_2.html#cb367-1" aria-hidden="true" tabindex="-1"></a><span class="fu">layerStats</span>(RasterMaps, <span class="st">&#39;pearson&#39;</span>, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## $`pearson correlation coefficient`
##              cti       err27         ffp         gsp         hli       nlcd
## cti    1.0000000 -0.25442672  0.12264734 -0.14029572 -0.30501483 -0.1807878
## err27 -0.2544267  1.00000000 -0.23467075  0.21403415  0.07724426  0.1256296
## ffp    0.1226473 -0.23467075  1.00000000 -0.95144256 -0.07567975 -0.3297561
## gsp   -0.1402957  0.21403415 -0.95144256  1.00000000  0.09520075  0.3765363
## hli   -0.3050148  0.07724426 -0.07567975  0.09520075  1.00000000  0.2465540
## nlcd  -0.1807878  0.12562961 -0.32975610  0.37653635  0.24655404  1.0000000
## 
## $mean
##          cti        err27          ffp          gsp          hli         nlcd 
##    5.3386441    0.4509513   11.2037444  277.2211529 1938.3644530   50.8191308</code></pre>
</div>
<div id="b.-change-color-ramp-add-sampling-locations" class="section level4 unnumbered hasAnchor">
<h4>b. Change color ramp, add sampling locations<a href="WE_2.html#b.-change-color-ramp-add-sampling-locations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can specify a color ramp by setting the <code>col</code> argument. The default is <code>terrain.colors(255)</code>. Here we change it to <code>rainbow(9)</code>, a rainbow colorpalette with 9 color levels.</p>
<p>Note: To learn about options for the <code>plot</code> function for <code>raster</code> objects, access the help file by typing <code>?plot</code> and select <code>Plot a Raster object</code>.</p>
<p>We can add the sampling locations (if we plot only a single raster layer). Here we use <code>rev</code> to reverse the color ramp for plotting raster layer <code>ffp</code>, and add the sites as white circles with black outlines.</p>
<div class="sourceCode" id="cb369"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb369-1"><a href="WE_2.html#cb369-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb369-2"><a href="WE_2.html#cb369-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">raster</span>(RasterMaps, <span class="at">layer=</span><span class="st">&quot;ffp&quot;</span>), <span class="at">col=</span><span class="fu">rev</span>(<span class="fu">rainbow</span>(<span class="dv">9</span>)))</span>
<span id="cb369-3"><a href="WE_2.html#cb369-3" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(Sites.sp, <span class="at">pch=</span><span class="dv">21</span>, <span class="at">col=</span><span class="st">&quot;black&quot;</span>, <span class="at">bg=</span><span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-24-1.png" width="427.2" /></p>
<p><strong>Question</strong>: Recall that ‘ffp’ stands for frost free period (in days). What do you think is the average length of the frost free period at theses sampling sites?</p>
</div>
<div id="c.-extract-raster-values-at-sampling-locations" class="section level4 unnumbered hasAnchor">
<h4>c. Extract raster values at sampling locations<a href="WE_2.html#c.-extract-raster-values-at-sampling-locations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The following code adds six variables to the data slot of Sites.sp. Technically we combine the columns of the existing data frame <code>Sites.sp</code> with the new columns in a new data frame with the same name.</p>
<p>R notices the difference in projection (CRS) between the sampling point data and the rasters and takes care of it, providing just a warning.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="WE_2.html#cb370-1" aria-hidden="true" tabindex="-1"></a>Sites.sp<span class="sc">@</span>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Sites.sp<span class="sc">@</span>data, <span class="fu">extract</span>(RasterMaps, Sites.sp))</span></code></pre></div>
<p>Let’s calcualate the mean length of the frost free period for these sites:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb371-1"><a href="WE_2.html#cb371-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Sites.sp<span class="sc">@</span>data<span class="sc">$</span>ffp)</span></code></pre></div>
<pre><code>## [1] 8.0963</code></pre>
<p>What land cover type is assigned to the most sampling units? Let’s tabulate them.</p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb373-1"><a href="WE_2.html#cb373-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Sites.sp<span class="sc">@</span>data<span class="sc">$</span>nlcd)</span></code></pre></div>
<pre><code>## 
## 11 12 42 52 71 90 
##  3  1 21  1  4  1</code></pre>
<p>Note: land cover types are coded by numbers. Check here what the numbers mean: <a href="https://www.mrlc.gov/data/legends/national-land-cover-database-2016-nlcd2016-legend" class="uri">https://www.mrlc.gov/data/legends/national-land-cover-database-2016-nlcd2016-legend</a></p>
<p><strong>Question</strong>: A total of 21 sites are classified as <code>42</code>. What is this most frequent land cover type?</p>
</div>
</div>
<div id="calculate-landscape-metrics" class="section level3 unnumbered hasAnchor">
<h3>4. Calculate landscape metrics<a href="WE_2.html#calculate-landscape-metrics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We are going to use the package <a href="https://r-spatialecology.github.io/landscapemetrics/"><code>landscapemetrics</code></a>. It is an R package to calculate landscape metrics in a tidy workflow (for more information about tidy data see <a href="https://www.jstatsoft.org/article/view/v059i10/">here</a>). <code>landscapemetrics</code> is basically a reimplementation of <a href="https://www.umass.edu/landeco/research/fragstats/fragstats.html">‘FRAGSTATS’</a>, which allows an integration into larger workflows within the R environment. The core of the package are functions to calculate landscape metrics, but also several auxiliary functions exit.</p>
<p>To facilitate an integration into larger workflows, <code>landscapemetrics</code> is based on the <a href="https://CRAN.R-project.org/package=raster"><code>raster</code> package</a>. To check if a raster is suitable for <code>landscapemetrics</code>, run the <code>check_landscape()</code> function first. The function checks the coordinate reference system (and mainly if units are in meters) and if the raster values are discrete classes. If the check fails, the calculation of metrics is still possible, however, especially metrics that are based on area and distances must be used with caution.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb375-1"><a href="WE_2.html#cb375-1" aria-hidden="true" tabindex="-1"></a>nlcd <span class="ot">&lt;-</span> <span class="fu">raster</span>(RasterMaps, <span class="at">layer =</span> <span class="st">&quot;nlcd&quot;</span>)</span>
<span id="cb375-2"><a href="WE_2.html#cb375-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb375-3"><a href="WE_2.html#cb375-3" aria-hidden="true" tabindex="-1"></a>landscapemetrics<span class="sc">::</span><span class="fu">check_landscape</span>(nlcd)</span></code></pre></div>
<pre><code>##   layer       crs units   class n_classes OK
## 1     1 projected     m integer         8  ✓</code></pre>
<p>There are three different levels of landscape metrics. Firstly, metrics can be calculated for each single patch (a patch is defined as neighbouring cells of the same class). Secondly, metrics can be calculated for a certain class (i.e. all patches belonging to the same class) and lastly for the whole landscape. All these levels are implemented and easily accessible in <code>landscapemetrics</code>.</p>
<p>All functions to calculate metrics start with <code>lsm_</code> (for landscapemetrics). The second part of the name specifies the level (patch - <code>p</code>, class - <code>c</code> or landscape - <code>l</code>). Lastly, the final part of the function name is the abbreviation of the corresponding metric (e.g. <code>enn</code> for the Euclidean nearest-neighbor distance). To list all available metrics, you can use the <code>list_lsm()</code> function. The function also allows to show metrics filtered by level, type or metric name. For more information about the metrics, please see either the corresponding helpfile(s) or <a href="https://r-spatialecology.github.io/landscapemetrics/reference/index.html">https://r-spatialecology.github.io/landscapemetrics</a>.</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="WE_2.html#cb377-1" aria-hidden="true" tabindex="-1"></a>landscapemetrics<span class="sc">::</span><span class="fu">list_lsm</span>(<span class="at">level =</span> <span class="st">&quot;landscape&quot;</span>, <span class="at">type =</span> <span class="st">&quot;diversity metric&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 9 × 5
##   metric name                               type             level function_name
##   &lt;chr&gt;  &lt;chr&gt;                              &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt;        
## 1 msidi  modified simpson&#39;s diversity index diversity metric land… lsm_l_msidi  
## 2 msiei  modified simpson&#39;s evenness index  diversity metric land… lsm_l_msiei  
## 3 pr     patch richness                     diversity metric land… lsm_l_pr     
## 4 prd    patch richness density             diversity metric land… lsm_l_prd    
## 5 rpr    relative patch richness            diversity metric land… lsm_l_rpr    
## 6 shdi   shannon&#39;s diversity index          diversity metric land… lsm_l_shdi   
## 7 shei   shannon&#39;s evenness index           diversity metric land… lsm_l_shei   
## 8 sidi   simpson&#39;s diversity index          diversity metric land… lsm_l_sidi   
## 9 siei   simspon&#39;s evenness index           diversity metric land… lsm_l_siei</code></pre>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb379-1"><a href="WE_2.html#cb379-1" aria-hidden="true" tabindex="-1"></a>landscapemetrics<span class="sc">::</span><span class="fu">list_lsm</span>(<span class="at">metric =</span> <span class="st">&quot;area&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 7 × 5
##   metric  name       type                 level     function_name
##   &lt;chr&gt;   &lt;chr&gt;      &lt;chr&gt;                &lt;chr&gt;     &lt;chr&gt;        
## 1 area    patch area area and edge metric patch     lsm_p_area   
## 2 area_cv patch area area and edge metric class     lsm_c_area_cv
## 3 area_mn patch area area and edge metric class     lsm_c_area_mn
## 4 area_sd patch area area and edge metric class     lsm_c_area_sd
## 5 area_cv patch area area and edge metric landscape lsm_l_area_cv
## 6 area_mn patch area area and edge metric landscape lsm_l_area_mn
## 7 area_sd patch area area and edge metric landscape lsm_l_area_sd</code></pre>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb381-1"><a href="WE_2.html#cb381-1" aria-hidden="true" tabindex="-1"></a>landscapemetrics<span class="sc">::</span><span class="fu">list_lsm</span>(<span class="at">level =</span> <span class="fu">c</span>(<span class="st">&quot;class&quot;</span>, <span class="st">&quot;landscape&quot;</span>), <span class="at">type =</span> <span class="st">&quot;aggregation metric&quot;</span>, </span>
<span id="cb381-2"><a href="WE_2.html#cb381-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">simplify =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;lsm_c_ai&quot;       &quot;lsm_c_clumpy&quot;   &quot;lsm_c_cohesion&quot; &quot;lsm_c_division&quot;
##  [5] &quot;lsm_c_enn_cv&quot;   &quot;lsm_c_enn_mn&quot;   &quot;lsm_c_enn_sd&quot;   &quot;lsm_c_iji&quot;     
##  [9] &quot;lsm_c_lsi&quot;      &quot;lsm_c_mesh&quot;     &quot;lsm_c_nlsi&quot;     &quot;lsm_c_np&quot;      
## [13] &quot;lsm_c_pd&quot;       &quot;lsm_c_pladj&quot;    &quot;lsm_c_split&quot;    &quot;lsm_l_ai&quot;      
## [17] &quot;lsm_l_cohesion&quot; &quot;lsm_l_contag&quot;   &quot;lsm_l_division&quot; &quot;lsm_l_enn_cv&quot;  
## [21] &quot;lsm_l_enn_mn&quot;   &quot;lsm_l_enn_sd&quot;   &quot;lsm_l_iji&quot;      &quot;lsm_l_lsi&quot;     
## [25] &quot;lsm_l_mesh&quot;     &quot;lsm_l_np&quot;       &quot;lsm_l_pd&quot;       &quot;lsm_l_pladj&quot;   
## [29] &quot;lsm_l_split&quot;</code></pre>
<div id="a.-calculate-patch--class--and-landscape-level-landscape-metrics" class="section level4 unnumbered hasAnchor">
<h4>a. Calculate patch-, class- and landscape level landscape metrics<a href="WE_2.html#a.-calculate-patch--class--and-landscape-level-landscape-metrics" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Note: This section explains different ways of calculating a selection of landscape metrics from a raster map with ‘landscapemetrics.’ If this seems too technical for a first go, you may jump to section 4b.</p>
<p>To calculate a single metric, just use the corresponding function. The result of all landscape metric functions is always an identically structured <code>tibble</code> (i.e. an advanced <code>data.frame</code>). The first coloumn is the layer id (only interesting for e.g. a <code>RasterStack</code>). The second coloumn specifies the level (‘patch,’ ‘class’ or ‘landscape’). The third coloumn is the class ID (<code>NA</code> on landscape level) and the fourth coloumn is the patch ID (<code>NA</code> on class- and landscape level). Lastly, The fith coloumn is the abbreviation of the metric and finally the corresponding value in the last coloumn.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="WE_2.html#cb383-1" aria-hidden="true" tabindex="-1"></a><span class="do">## c.lculate percentage of landscape of class</span></span>
<span id="cb383-2"><a href="WE_2.html#cb383-2" aria-hidden="true" tabindex="-1"></a>percentage_class <span class="ot">&lt;-</span> <span class="fu">lsm_c_pland</span>(<span class="at">landscape =</span> nlcd)</span>
<span id="cb383-3"><a href="WE_2.html#cb383-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb383-4"><a href="WE_2.html#cb383-4" aria-hidden="true" tabindex="-1"></a>percentage_class</span></code></pre></div>
<pre><code>## # A tibble: 8 × 6
##   layer level class    id metric   value
##   &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;
## 1     1 class    11    NA pland   0.948 
## 2     1 class    12    NA pland   0.441 
## 3     1 class    31    NA pland   0.394 
## 4     1 class    42    NA pland  59.1   
## 5     1 class    52    NA pland  11.0   
## 6     1 class    71    NA pland  28.1   
## 7     1 class    90    NA pland   0.0557
## 8     1 class    95    NA pland   0.0210</code></pre>
<p><strong>Questions</strong>:</p>
<ul>
<li>What percentage of the overall landscape (total map) is evergreen forest (class 42)?</li>
<li>What percentage of the landscape is classified as wetlands (classes 90 and 95)?</li>
</ul>
<p>Because the resulting <code>tibble</code> is type stable, you can easily row-bind (<code>rbind</code>) different metrics (even of different levels):</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="WE_2.html#cb385-1" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb385-2"><a href="WE_2.html#cb385-2" aria-hidden="true" tabindex="-1"></a>  landscapemetrics<span class="sc">::</span><span class="fu">lsm_c_pladj</span>(nlcd), </span>
<span id="cb385-3"><a href="WE_2.html#cb385-3" aria-hidden="true" tabindex="-1"></a>  landscapemetrics<span class="sc">::</span><span class="fu">lsm_l_pr</span>(nlcd),</span>
<span id="cb385-4"><a href="WE_2.html#cb385-4" aria-hidden="true" tabindex="-1"></a>  landscapemetrics<span class="sc">::</span><span class="fu">lsm_l_shdi</span>(nlcd)</span>
<span id="cb385-5"><a href="WE_2.html#cb385-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb385-6"><a href="WE_2.html#cb385-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb385-7"><a href="WE_2.html#cb385-7" aria-hidden="true" tabindex="-1"></a>metrics</span></code></pre></div>
<pre><code>## # A tibble: 10 × 6
##    layer level     class    id metric value
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1     1 class        11    NA pladj  77.9 
##  2     1 class        12    NA pladj  52.5 
##  3     1 class        31    NA pladj  48.8 
##  4     1 class        42    NA pladj  89.9 
##  5     1 class        52    NA pladj  58.6 
##  6     1 class        71    NA pladj  81.6 
##  7     1 class        90    NA pladj  41.8 
##  8     1 class        95    NA pladj  32.8 
##  9     1 landscape    NA    NA pr      8   
## 10     1 landscape    NA    NA shdi    1.01</code></pre>
<p>To calculate a larger set of landscape metrics, you can just use the wrapper <code>calculate_lsm()</code>. The arguments are similar to <code>list_lsm()</code>, e.g. you can specify the level or the type of metrics to calculate. Alternatively, you can also provide a vector with the function names of metrics to calculate to the <code>what</code> argument.</p>
<p>However, watch out, for large rasters and many metrics, this can be rather slow (set <code>progress = TRUE</code> to get an progress report on the console). Also, we suggest to not just calculate all available metrics, but rather think about which ones might be actually suitable for your research question.</p>
<p>Calculate all patch-level metrics using wrapper:</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="WE_2.html#cb387-1" aria-hidden="true" tabindex="-1"></a>nlcd_patch <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">calculate_lsm</span>(<span class="at">landscape =</span> nlcd,</span>
<span id="cb387-2"><a href="WE_2.html#cb387-2" aria-hidden="true" tabindex="-1"></a>                                              <span class="at">level =</span> <span class="st">&quot;patch&quot;</span>)</span>
<span id="cb387-3"><a href="WE_2.html#cb387-3" aria-hidden="true" tabindex="-1"></a>nlcd_patch</span></code></pre></div>
<pre><code>## # A tibble: 19,776 × 6
##    layer level class    id metric value
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1     1 patch    11     1 area    0.45
##  2     1 patch    11     2 area    0.45
##  3     1 patch    11     3 area   41.7 
##  4     1 patch    11     4 area    0.72
##  5     1 patch    11     5 area    6.12
##  6     1 patch    11     6 area    0.9 
##  7     1 patch    11     7 area    0.9 
##  8     1 patch    11     8 area    1.89
##  9     1 patch    11     9 area    0.09
## 10     1 patch    11    10 area    1.17
## # … with 19,766 more rows</code></pre>
<p>Show abbreviation of all calculated metrics:</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="WE_2.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nlcd_patch<span class="sc">$</span>metric)</span></code></pre></div>
<pre><code>##  [1] &quot;area&quot;   &quot;cai&quot;    &quot;circle&quot; &quot;contig&quot; &quot;core&quot;   &quot;enn&quot;    &quot;frac&quot;   &quot;gyrate&quot;
##  [9] &quot;ncore&quot;  &quot;para&quot;   &quot;perim&quot;  &quot;shape&quot;</code></pre>
<p>Calculate all aggregation metrics on landscape level:</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="WE_2.html#cb391-1" aria-hidden="true" tabindex="-1"></a>nlcd_landscape_aggr <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">calculate_lsm</span>(<span class="at">landscape =</span> nlcd, </span>
<span id="cb391-2"><a href="WE_2.html#cb391-2" aria-hidden="true" tabindex="-1"></a>                                                       <span class="at">level =</span> <span class="st">&quot;landscape&quot;</span>, </span>
<span id="cb391-3"><a href="WE_2.html#cb391-3" aria-hidden="true" tabindex="-1"></a>                                                       <span class="at">type =</span> <span class="st">&quot;aggregation metric&quot;</span>)</span>
<span id="cb391-4"><a href="WE_2.html#cb391-4" aria-hidden="true" tabindex="-1"></a>nlcd_landscape_aggr</span></code></pre></div>
<pre><code>## # A tibble: 14 × 6
##    layer level     class    id metric      value
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;       &lt;dbl&gt;
##  1     1 landscape    NA    NA ai         84.1  
##  2     1 landscape    NA    NA cohesion   99.2  
##  3     1 landscape    NA    NA contag     62.7  
##  4     1 landscape    NA    NA division    0.804
##  5     1 landscape    NA    NA enn_cv    218.   
##  6     1 landscape    NA    NA enn_mn    129.   
##  7     1 landscape    NA    NA enn_sd    281.   
##  8     1 landscape    NA    NA iji        43.0  
##  9     1 landscape    NA    NA lsi        32.3  
## 10     1 landscape    NA    NA mesh     2694.   
## 11     1 landscape    NA    NA np       1648    
## 12     1 landscape    NA    NA pd         12.0  
## 13     1 landscape    NA    NA pladj      83.7  
## 14     1 landscape    NA    NA split       5.09</code></pre>
<p>Calculate specific metrics:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="WE_2.html#cb393-1" aria-hidden="true" tabindex="-1"></a>nlcd_subset <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">calculate_lsm</span>(<span class="at">landscape =</span> nlcd, </span>
<span id="cb393-2"><a href="WE_2.html#cb393-2" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;lsm_c_pladj&quot;</span>, </span>
<span id="cb393-3"><a href="WE_2.html#cb393-3" aria-hidden="true" tabindex="-1"></a>                                                        <span class="st">&quot;lsm_l_pr&quot;</span>, </span>
<span id="cb393-4"><a href="WE_2.html#cb393-4" aria-hidden="true" tabindex="-1"></a>                                                        <span class="st">&quot;lsm_l_shdi&quot;</span>))</span>
<span id="cb393-5"><a href="WE_2.html#cb393-5" aria-hidden="true" tabindex="-1"></a>nlcd_subset</span></code></pre></div>
<pre><code>## # A tibble: 10 × 6
##    layer level     class    id metric value
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1     1 class        11    NA pladj  77.9 
##  2     1 class        12    NA pladj  52.5 
##  3     1 class        31    NA pladj  48.8 
##  4     1 class        42    NA pladj  89.9 
##  5     1 class        52    NA pladj  58.6 
##  6     1 class        71    NA pladj  81.6 
##  7     1 class        90    NA pladj  41.8 
##  8     1 class        95    NA pladj  32.8 
##  9     1 landscape    NA    NA pr      8   
## 10     1 landscape    NA    NA shdi    1.01</code></pre>
<p>The resulting <code>tibble</code> is easy to integrate into a workflow. For example, to get the ordered patch IDs of the 5% largest patches, the following code could be used.</p>
<p>The pipe operator %&gt;% from the <code>dplyr</code> package passes the resulting object automatically to the next function as first argument.</p>
<p>Note: the last step (pulling the id variable only) could be done by adding this to the pipe: <code>%&gt;% dplyr::pull(id)</code>. Due to some package inconsistencies, this sometimes created an error. Here we extract the id variable in a separate step as a work-around.</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="WE_2.html#cb395-1" aria-hidden="true" tabindex="-1"></a>id_largest <span class="ot">&lt;-</span> nlcd_patch <span class="sc">%&gt;%</span> <span class="co"># previously calculated patch metrics</span></span>
<span id="cb395-2"><a href="WE_2.html#cb395-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(metric <span class="sc">==</span> <span class="st">&quot;area&quot;</span>) <span class="sc">%&gt;%</span> <span class="co"># only patch area</span></span>
<span id="cb395-3"><a href="WE_2.html#cb395-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="sc">-</span>value) <span class="sc">%&gt;%</span> <span class="co"># order by decreasing size</span></span>
<span id="cb395-4"><a href="WE_2.html#cb395-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(value <span class="sc">&gt;</span> <span class="fu">quantile</span>(value, <span class="at">probs =</span> <span class="fl">0.95</span>)) <span class="do">## g.t only patches larger than 95% quantile</span></span>
<span id="cb395-5"><a href="WE_2.html#cb395-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb395-6"><a href="WE_2.html#cb395-6" aria-hidden="true" tabindex="-1"></a>id_largest <span class="ot">&lt;-</span> id_largest<span class="sc">$</span>id <span class="do">## g.t only patch id</span></span>
<span id="cb395-7"><a href="WE_2.html#cb395-7" aria-hidden="true" tabindex="-1"></a>id_largest</span></code></pre></div>
<pre><code>##  [1]  206  166 1265 1459 1549 1558 1421  427 1434 1385  226    3  386 1205  589
## [16] 1441  426 1059 1206  324  433 1195  315 1225  712 1266 1377  389  753 1528
## [31]  894 1510  286  563  240 1411  478 1364  435 1336  812  640 1376 1523  786
## [46]  467  485 1559 1244  284 1537 1574  718  814  499  864  955 1015 1430  443
## [61]  393  930 1250  548  851  885 1481  928 1554   43  164  281 1608  716  514
## [76]  802 1614  729  977 1488   37  357 1353</code></pre>
<p>Because the metric names are only abbreviated, there is also a way to include the full name in the results. For the wrapper, just set <code>full_name = TRUE</code>. For the rowbinded <code>tibble</code>, you can use the provided <code>tibble</code> called <code>lsm_abbreviations_names</code> that comes with the package and use e.g. <code>dplyr::left_join()</code> to combine it with your results.</p>
<p>Add full metrics name to result:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="WE_2.html#cb397-1" aria-hidden="true" tabindex="-1"></a>nlcd_subset_full_a <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">calculate_lsm</span>(nlcd, </span>
<span id="cb397-2"><a href="WE_2.html#cb397-2" aria-hidden="true" tabindex="-1"></a>                                                      <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;lsm_c_pladj&quot;</span>, </span>
<span id="cb397-3"><a href="WE_2.html#cb397-3" aria-hidden="true" tabindex="-1"></a>                                                               <span class="st">&quot;lsm_l_pr&quot;</span>, </span>
<span id="cb397-4"><a href="WE_2.html#cb397-4" aria-hidden="true" tabindex="-1"></a>                                                               <span class="st">&quot;lsm_l_shdi&quot;</span>), </span>
<span id="cb397-5"><a href="WE_2.html#cb397-5" aria-hidden="true" tabindex="-1"></a>                                                      <span class="at">full_name =</span> <span class="cn">TRUE</span>)</span>
<span id="cb397-6"><a href="WE_2.html#cb397-6" aria-hidden="true" tabindex="-1"></a>nlcd_subset_full_a</span></code></pre></div>
<pre><code>## # A tibble: 10 × 9
##    layer level     class    id metric value name             type  function_name
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt;        
##  1     1 class        11    NA pladj  77.9  percentage of l… aggr… lsm_c_pladj  
##  2     1 class        12    NA pladj  52.5  percentage of l… aggr… lsm_c_pladj  
##  3     1 class        31    NA pladj  48.8  percentage of l… aggr… lsm_c_pladj  
##  4     1 class        42    NA pladj  89.9  percentage of l… aggr… lsm_c_pladj  
##  5     1 class        52    NA pladj  58.6  percentage of l… aggr… lsm_c_pladj  
##  6     1 class        71    NA pladj  81.6  percentage of l… aggr… lsm_c_pladj  
##  7     1 class        90    NA pladj  41.8  percentage of l… aggr… lsm_c_pladj  
##  8     1 class        95    NA pladj  32.8  percentage of l… aggr… lsm_c_pladj  
##  9     1 landscape    NA    NA pr      8    patch richness   dive… lsm_l_pr     
## 10     1 landscape    NA    NA shdi    1.01 shannon&#39;s diver… dive… lsm_l_shdi</code></pre>
<p>Add full metrics name to results calculated previously using <code>left_join()</code>:</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="WE_2.html#cb399-1" aria-hidden="true" tabindex="-1"></a>nlcd_subset_full_b <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(<span class="at">x =</span> nlcd_subset,</span>
<span id="cb399-2"><a href="WE_2.html#cb399-2" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">y =</span> lsm_abbreviations_names,</span>
<span id="cb399-3"><a href="WE_2.html#cb399-3" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;metric&quot;</span>, <span class="st">&quot;level&quot;</span>))</span>
<span id="cb399-4"><a href="WE_2.html#cb399-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb399-5"><a href="WE_2.html#cb399-5" aria-hidden="true" tabindex="-1"></a>nlcd_subset_full_b</span></code></pre></div>
<pre><code>## # A tibble: 10 × 9
##    layer level     class    id metric value name             type  function_name
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt;        
##  1     1 class        11    NA pladj  77.9  percentage of l… aggr… lsm_c_pladj  
##  2     1 class        12    NA pladj  52.5  percentage of l… aggr… lsm_c_pladj  
##  3     1 class        31    NA pladj  48.8  percentage of l… aggr… lsm_c_pladj  
##  4     1 class        42    NA pladj  89.9  percentage of l… aggr… lsm_c_pladj  
##  5     1 class        52    NA pladj  58.6  percentage of l… aggr… lsm_c_pladj  
##  6     1 class        71    NA pladj  81.6  percentage of l… aggr… lsm_c_pladj  
##  7     1 class        90    NA pladj  41.8  percentage of l… aggr… lsm_c_pladj  
##  8     1 class        95    NA pladj  32.8  percentage of l… aggr… lsm_c_pladj  
##  9     1 landscape    NA    NA pr      8    patch richness   dive… lsm_l_pr     
## 10     1 landscape    NA    NA shdi    1.01 shannon&#39;s diver… dive… lsm_l_shdi</code></pre>
</div>
<div id="b.-calculate-patch-level-landscape-metrics-for-evergreen-forest" class="section level4 unnumbered hasAnchor">
<h4>b. Calculate patch-level landscape metrics for ‘Evergreen Forest’<a href="WE_2.html#b.-calculate-patch-level-landscape-metrics-for-evergreen-forest" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To only get the results for class 42 (evergreen forest), you can just <code>dplyr::filter()</code> the <code>tibble</code> (or use any other subset method you prefer).</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="WE_2.html#cb401-1" aria-hidden="true" tabindex="-1"></a>forest_patch_metrics <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(nlcd_patch, class <span class="sc">==</span> <span class="dv">42</span>)</span></code></pre></div>
<p>All functions make heavy use of connected components labeling to delineate patches (neighbouring cells of the same class). To get all patches of every class you can just use <code>get_patches()</code>. To get only a certain class, just specify the <code>class</code> argument and the neighbourhood rule can be chosen between 8-neighbour rule or 4-neighbour rule with the argument <code>directions</code>.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="WE_2.html#cb402-1" aria-hidden="true" tabindex="-1"></a><span class="do">## c.nnected components labeling of landscape</span></span>
<span id="cb402-2"><a href="WE_2.html#cb402-2" aria-hidden="true" tabindex="-1"></a>cc_nlcd <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">get_patches</span>(nlcd, <span class="at">directions =</span> <span class="dv">8</span>)</span>
<span id="cb402-3"><a href="WE_2.html#cb402-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb402-4"><a href="WE_2.html#cb402-4" aria-hidden="true" tabindex="-1"></a><span class="co"># show name of each class</span></span>
<span id="cb402-5"><a href="WE_2.html#cb402-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(cc_nlcd, <span class="cf">function</span>(x) <span class="fu">names</span>(x)) </span></code></pre></div>
<pre><code>##      layer_1   
## [1,] &quot;class_11&quot;
## [2,] &quot;class_12&quot;
## [3,] &quot;class_31&quot;
## [4,] &quot;class_42&quot;
## [5,] &quot;class_52&quot;
## [6,] &quot;class_71&quot;
## [7,] &quot;class_90&quot;
## [8,] &quot;class_95&quot;</code></pre>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="WE_2.html#cb404-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the fourth list entry is class forest</span></span>
<span id="cb404-2"><a href="WE_2.html#cb404-2" aria-hidden="true" tabindex="-1"></a>cc_forest_a <span class="ot">&lt;-</span> cc_nlcd[<span class="dv">4</span>]</span>
<span id="cb404-3"><a href="WE_2.html#cb404-3" aria-hidden="true" tabindex="-1"></a>cc_forest_b <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">get_patches</span>(nlcd, <span class="at">class =</span> <span class="dv">42</span>) <span class="co"># watch out: result is list with one entry</span></span>
<span id="cb404-4"><a href="WE_2.html#cb404-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb404-5"><a href="WE_2.html#cb404-5" aria-hidden="true" tabindex="-1"></a>cc_forest_a</span></code></pre></div>
<pre><code>## $&lt;NA&gt;
## NULL</code></pre>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="WE_2.html#cb406-1" aria-hidden="true" tabindex="-1"></a>cc_forest_b</span></code></pre></div>
<pre><code>## $layer_1
## $layer_1$class_42
## class      : RasterLayer 
## dimensions : 426, 358, 152508  (nrow, ncol, ncell)
## resolution : 30, 30  (x, y)
## extent     : 683282.5, 694022.5, 4992833, 5005613  (xmin, xmax, ymin, ymax)
## crs        : +proj=utm +zone=11 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
## source     : memory
## names      : layer 
## values     : 1, 222  (min, max)</code></pre>
<p>To plot the patches you can use the <code>show_patches()</code> function. Here we show patches of class 42 (forest) and class 52 (shrubland):</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="WE_2.html#cb408-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_patches</span>(<span class="at">landscape =</span> nlcd, <span class="at">class =</span> <span class="fu">c</span>(<span class="dv">42</span>, <span class="dv">52</span>), <span class="at">labels =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $layer_1</code></pre>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-41-1.png" width="672" /></p>
<p>It is also possible to visualize only the core area of each patch using <code>show_cores()</code>. The core area is defined as all cells that are further away from the edge of each patch than a specified edge depth (e.g. 5 cells). Here we show core area with edge depth = 5 for class 42; try edge_depth = 1 for comparison:</p>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="WE_2.html#cb410-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_cores</span>(<span class="at">landscape =</span> nlcd, <span class="at">class =</span> <span class="fu">c</span>(<span class="dv">42</span>), <span class="at">edge_depth =</span> <span class="dv">5</span>, <span class="at">labels =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $layer_1</code></pre>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Note: this may create a warning “no non-missing arguments to min; returning Inf” for each patch that does not have any core area. Here we suppressed the warnings for the chunk with the chunk option <code>warning=FALSE</code>.</p>
<p>Lastly, you can plot the map and fill each patch with the corresponding metric value, e.g. patch size, using <code>show_lsm()</code>. Notice that there are two very large patches in class 42:</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="WE_2.html#cb412-1" aria-hidden="true" tabindex="-1"></a><span class="fu">show_lsm</span>(<span class="at">landscape =</span> nlcd, <span class="at">class =</span> <span class="fu">c</span>(<span class="dv">42</span>, <span class="dv">52</span>), <span class="at">what =</span> <span class="st">&quot;lsm_p_area&quot;</span>, <span class="at">labels =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## $layer_1</code></pre>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
</div>
<div id="c.-extract-forest-patch-size-at-samplig-locations" class="section level4 unnumbered hasAnchor">
<h4>c. Extract forest patch size at samplig locations<a href="WE_2.html#c.-extract-forest-patch-size-at-samplig-locations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Let’s add forest patch size to the <code>Sites.sp</code> data. To extract landscape metrics of the patch in which each sampling point is located, use <code>extract_lsm()</code>. Which metrics are extracted can be specified by the <code>what</code> argument (similar to <code>calculate_lsm()</code>). However, only patch-level metrics are available. Please be aware, that the resulting <code>tibble</code> now has a new column, namely the ID of the sampling point (in the same order as the input points).</p>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="WE_2.html#cb414-1" aria-hidden="true" tabindex="-1"></a><span class="do">## e.tract patch area of all classes:</span></span>
<span id="cb414-2"><a href="WE_2.html#cb414-2" aria-hidden="true" tabindex="-1"></a>patch_size_sp <span class="ot">&lt;-</span> <span class="fu">extract_lsm</span>(<span class="at">landscape =</span> nlcd, <span class="at">y =</span> Sites.sp, <span class="at">what =</span> <span class="st">&quot;lsm_p_area&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Only using &#39;what&#39; argument.</code></pre>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="WE_2.html#cb416-1" aria-hidden="true" tabindex="-1"></a><span class="do">## b.cause we are only interested in the forest patch size, we set all area of class != 42 to 0:</span></span>
<span id="cb416-2"><a href="WE_2.html#cb416-2" aria-hidden="true" tabindex="-1"></a>patch_size_sp_forest <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">mutate</span>(patch_size_sp, </span>
<span id="cb416-3"><a href="WE_2.html#cb416-3" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">value =</span> dplyr<span class="sc">::</span><span class="fu">case_when</span>(class <span class="sc">==</span> <span class="dv">42</span> <span class="sc">~</span> value, </span>
<span id="cb416-4"><a href="WE_2.html#cb416-4" aria-hidden="true" tabindex="-1"></a>                                                               class <span class="sc">!=</span> <span class="dv">42</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb416-5"><a href="WE_2.html#cb416-5" aria-hidden="true" tabindex="-1"></a><span class="do">## a.d data to sp object:</span></span>
<span id="cb416-6"><a href="WE_2.html#cb416-6" aria-hidden="true" tabindex="-1"></a>Sites.sp<span class="sc">@</span>data<span class="sc">$</span>ForestPatchSize <span class="ot">&lt;-</span> patch_size_sp_forest<span class="sc">$</span>value</span>
<span id="cb416-7"><a href="WE_2.html#cb416-7" aria-hidden="true" tabindex="-1"></a>Sites.sp<span class="sc">@</span>data<span class="sc">$</span>ForestPatchSize</span></code></pre></div>
<pre><code>##  [1] 3179.88    0.00 3179.88    0.00    6.66 4539.33 4539.33 4539.33    0.00
## [10] 4539.33 4539.33   23.76   23.76    0.00    0.00 4539.33    0.00 4539.33
## [19]    3.60 3179.88    0.00 4539.33    3.87 4539.33    0.00    0.00   23.76
## [28] 3179.88    0.00 4539.33    0.09</code></pre>
</div>
<div id="d.-plot-a-bubble-map-of-forest-patch-size-at-sampling-locations" class="section level4 unnumbered hasAnchor">
<h4>d. Plot a bubble map of forest patch size at sampling locations<a href="WE_2.html#d.-plot-a-bubble-map-of-forest-patch-size-at-sampling-locations" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="WE_2.html#cb418-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb418-2"><a href="WE_2.html#cb418-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bubble</span>(Sites.sp, <span class="st">&quot;ForestPatchSize&quot;</span>, <span class="at">fill =</span> <span class="cn">FALSE</span>, <span class="at">key.entries =</span> <span class="fu">as.numeric</span>(<span class="fu">names</span>(<span class="fu">table</span>(Sites.sp<span class="sc">@</span>data<span class="sc">$</span>ForestPatchSize))))</span></code></pre></div>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-45-1.png" width="427.2" /></p>
</div>
</div>
<div id="sample-landscape-metrics-within-buffer-around-sampling-locations" class="section level3 unnumbered hasAnchor">
<h3>5. Sample landscape metrics within buffer around sampling locations<a href="WE_2.html#sample-landscape-metrics-within-buffer-around-sampling-locations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The package <code>landscapemetrics</code> has a built-in function <code>sample_lsm</code> to sample metrics in a buffer around sampling locations, which are provided with argument <code>y</code>. You can choose the <code>shape</code> of the buffer window (either a circle or a square) and, with the argument <code>what</code>, which metrics to sample (similar to <code>calculate_lsm()</code>).</p>
<p>The argument <code>size</code> specifies the buffer size in map units (e.g., meters): radius for circles, half of the side length for squares. Here, the value <code>size = 500</code> results in a square window of 1000 m x 1000 m centered at the sampling location.</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="WE_2.html#cb419-1" aria-hidden="true" tabindex="-1"></a>nlcd_sampled <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">sample_lsm</span>(<span class="at">landscape =</span> nlcd, </span>
<span id="cb419-2"><a href="WE_2.html#cb419-2" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;lsm_l_ta&quot;</span>, </span>
<span id="cb419-3"><a href="WE_2.html#cb419-3" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">&quot;lsm_c_np&quot;</span>,</span>
<span id="cb419-4"><a href="WE_2.html#cb419-4" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">&quot;lsm_c_pland&quot;</span>, </span>
<span id="cb419-5"><a href="WE_2.html#cb419-5" aria-hidden="true" tabindex="-1"></a>                                                      <span class="st">&quot;lsm_c_ai&quot;</span>),</span>
<span id="cb419-6"><a href="WE_2.html#cb419-6" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">shape =</span> <span class="st">&quot;square&quot;</span>,</span>
<span id="cb419-7"><a href="WE_2.html#cb419-7" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">y =</span> Sites.sp, </span>
<span id="cb419-8"><a href="WE_2.html#cb419-8" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">size =</span> <span class="dv">500</span>)</span>
<span id="cb419-9"><a href="WE_2.html#cb419-9" aria-hidden="true" tabindex="-1"></a>nlcd_sampled</span></code></pre></div>
<pre><code>## # A tibble: 493 × 8
##    layer level class    id metric value plot_id percentage_inside
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;int&gt;             &lt;dbl&gt;
##  1     1 class    11    NA ai      88.6       1              98.0
##  2     1 class    31    NA ai      NA         1              98.0
##  3     1 class    42    NA ai      93.3       1              98.0
##  4     1 class    52    NA ai      50         1              98.0
##  5     1 class    71    NA ai      65.9       1              98.0
##  6     1 class    11    NA np       2         1              98.0
##  7     1 class    31    NA np       1         1              98.0
##  8     1 class    42    NA np       2         1              98.0
##  9     1 class    52    NA np       4         1              98.0
## 10     1 class    71    NA np       8         1              98.0
## # … with 483 more rows</code></pre>
<p>The <code>tibble</code> now contains two additional columns. Firstly, the <code>plot_id</code> (in the same order as the input points) and secondly, the <code>percentage_inside</code>, i.e. what percentage of the buffer around the sampling location lies within the map. (In cases where the sampling location is on the edge of the landscape, the buffer around the sampling location could be only partly within the map). The value can also deviate from 100 % because the sampling locations are not necessarily in the cell center and the actually clipped cells lead to a slightly smaller or larger buffer area. A circular buffer shape increases this effect.</p>
<p>It is also possible to get the clippings of the buffer around sampling locations as a <code>RasterLayer</code>. For this, just set <code>return_raster = TRUE</code>.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="WE_2.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sample some metrics within buffer around sample location and returning sample</span></span>
<span id="cb421-2"><a href="WE_2.html#cb421-2" aria-hidden="true" tabindex="-1"></a><span class="co"># plots as raster</span></span>
<span id="cb421-3"><a href="WE_2.html#cb421-3" aria-hidden="true" tabindex="-1"></a>nlcd_sampled_plots <span class="ot">&lt;-</span> landscapemetrics<span class="sc">::</span><span class="fu">sample_lsm</span>(<span class="at">landscape =</span> nlcd, </span>
<span id="cb421-4"><a href="WE_2.html#cb421-4" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;lsm_l_ta&quot;</span>,</span>
<span id="cb421-5"><a href="WE_2.html#cb421-5" aria-hidden="true" tabindex="-1"></a>                                                            <span class="st">&quot;lsm_c_np&quot;</span>,</span>
<span id="cb421-6"><a href="WE_2.html#cb421-6" aria-hidden="true" tabindex="-1"></a>                                                            <span class="st">&quot;lsm_c_pland&quot;</span>,</span>
<span id="cb421-7"><a href="WE_2.html#cb421-7" aria-hidden="true" tabindex="-1"></a>                                                            <span class="st">&quot;lsm_c_ai&quot;</span>),</span>
<span id="cb421-8"><a href="WE_2.html#cb421-8" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">shape =</span> <span class="st">&quot;square&quot;</span>,</span>
<span id="cb421-9"><a href="WE_2.html#cb421-9" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">y =</span> Sites.sp, </span>
<span id="cb421-10"><a href="WE_2.html#cb421-10" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">size =</span> <span class="dv">500</span>, </span>
<span id="cb421-11"><a href="WE_2.html#cb421-11" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">return_raster =</span> <span class="cn">TRUE</span>)</span>
<span id="cb421-12"><a href="WE_2.html#cb421-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb421-13"><a href="WE_2.html#cb421-13" aria-hidden="true" tabindex="-1"></a>nlcd_sampled_plots</span></code></pre></div>
<pre><code>## # A tibble: 493 × 9
##    layer level class    id metric value plot_id percentage_inside
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;int&gt;             &lt;dbl&gt;
##  1     1 class    11    NA ai      88.6       1              98.0
##  2     1 class    31    NA ai      NA         1              98.0
##  3     1 class    42    NA ai      93.3       1              98.0
##  4     1 class    52    NA ai      50         1              98.0
##  5     1 class    71    NA ai      65.9       1              98.0
##  6     1 class    11    NA np       2         1              98.0
##  7     1 class    31    NA np       1         1              98.0
##  8     1 class    42    NA np       2         1              98.0
##  9     1 class    52    NA np       4         1              98.0
## 10     1 class    71    NA np       8         1              98.0
## # … with 483 more rows, and 1 more variable: raster_sample_plots &lt;list&gt;</code></pre>
<p>The result will be a nested <code>tibble</code> containing the <code>plot_id</code>, the metrics and a <code>RasterLayer</code> with the clipped buffers (as a <code>list</code>). Attention: Because several metrics on class- and landscape-level the clipped buffers will be “repeated” several times.</p>
<p>Here we show results for the first four sampling locations:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="WE_2.html#cb423-1" aria-hidden="true" tabindex="-1"></a>unique_plots <span class="ot">&lt;-</span> <span class="fu">unique</span>(nlcd_sampled_plots<span class="sc">$</span>raster_sample_plots)[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]</span>
<span id="cb423-2"><a href="WE_2.html#cb423-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb423-3"><a href="WE_2.html#cb423-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb423-4"><a href="WE_2.html#cb423-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(unique_plots[[<span class="dv">1</span>]], </span>
<span id="cb423-5"><a href="WE_2.html#cb423-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(Sites.sp<span class="sc">$</span>SiteName[<span class="dv">1</span>]), </span>
<span id="cb423-6"><a href="WE_2.html#cb423-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rev</span>(<span class="fu">rainbow</span>(<span class="dv">9</span>)))</span>
<span id="cb423-7"><a href="WE_2.html#cb423-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(unique_plots[[<span class="dv">2</span>]],</span>
<span id="cb423-8"><a href="WE_2.html#cb423-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(Sites.sp<span class="sc">$</span>SiteName[<span class="dv">2</span>]),</span>
<span id="cb423-9"><a href="WE_2.html#cb423-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rev</span>(<span class="fu">rainbow</span>(<span class="dv">9</span>)))</span>
<span id="cb423-10"><a href="WE_2.html#cb423-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(unique_plots[[<span class="dv">3</span>]],</span>
<span id="cb423-11"><a href="WE_2.html#cb423-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(Sites.sp<span class="sc">$</span>SiteName[<span class="dv">3</span>]), </span>
<span id="cb423-12"><a href="WE_2.html#cb423-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rev</span>(<span class="fu">rainbow</span>(<span class="dv">9</span>)))</span>
<span id="cb423-13"><a href="WE_2.html#cb423-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(unique_plots[[<span class="dv">4</span>]],</span>
<span id="cb423-14"><a href="WE_2.html#cb423-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste</span>(Sites.sp<span class="sc">$</span>SiteName[<span class="dv">4</span>]), </span>
<span id="cb423-15"><a href="WE_2.html#cb423-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rev</span>(<span class="fu">rainbow</span>(<span class="dv">9</span>)))</span></code></pre></div>
<p><img src="02-Week02_files/figure-html/unnamed-chunk-48-1.png" width="768" /></p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="WE_2.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<div id="b.-extract-landscape-metric-of-choice-for-a-single-cover-type-as-vector" class="section level4 unnumbered hasAnchor">
<h4>b. Extract landscape metric of choice for a single cover type (as vector)<a href="WE_2.html#b.-extract-landscape-metric-of-choice-for-a-single-cover-type-as-vector" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To extract a metrics you can just <code>dplyr::filter()</code> the resulting <code>tibble</code> and pull the <code>value</code> column.
Here we filter the results for class == 42 (forest) and metric <code>pland</code> (percentage of landscape) and pull the results as a vector:</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="WE_2.html#cb425-1" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_a <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">pull</span>(dplyr<span class="sc">::</span><span class="fu">filter</span>(nlcd_sampled, </span>
<span id="cb425-2"><a href="WE_2.html#cb425-2" aria-hidden="true" tabindex="-1"></a>                                                     class <span class="sc">==</span> <span class="dv">42</span>, </span>
<span id="cb425-3"><a href="WE_2.html#cb425-3" aria-hidden="true" tabindex="-1"></a>                                                     metric <span class="sc">==</span> <span class="st">&quot;pland&quot;</span>), value)</span>
<span id="cb425-4"><a href="WE_2.html#cb425-4" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_a</span></code></pre></div>
<pre><code>##  [1] 77.50230 39.57759 38.01653 31.40138 40.40404 83.30450 69.16221 86.80927
##  [9] 10.19284 72.81910 92.19467 34.04635 34.84848 27.09447 31.37255 56.23886
## [17] 59.77961 58.73440 37.64922 60.12111 46.16756 32.32323 23.35640 50.44563
## [25] 66.93405 30.57851 33.70064 26.53811 45.18717 38.05704 62.47772</code></pre>
<p>As an alternative, here’s the same workflow again, but using a pipe:</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="WE_2.html#cb427-1" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_b <span class="ot">&lt;-</span> nlcd_sampled <span class="sc">%&gt;%</span> </span>
<span id="cb427-2"><a href="WE_2.html#cb427-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(class <span class="sc">==</span> <span class="dv">42</span>, </span>
<span id="cb427-3"><a href="WE_2.html#cb427-3" aria-hidden="true" tabindex="-1"></a>                metric <span class="sc">==</span> <span class="st">&quot;pland&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb427-4"><a href="WE_2.html#cb427-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">pull</span>(value)</span>
<span id="cb427-5"><a href="WE_2.html#cb427-5" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_b</span></code></pre></div>
<pre><code>##  [1] 77.50230 39.57759 38.01653 31.40138 40.40404 83.30450 69.16221 86.80927
##  [9] 10.19284 72.81910 92.19467 34.04635 34.84848 27.09447 31.37255 56.23886
## [17] 59.77961 58.73440 37.64922 60.12111 46.16756 32.32323 23.35640 50.44563
## [25] 66.93405 30.57851 33.70064 26.53811 45.18717 38.05704 62.47772</code></pre>
</div>
<div id="c.-extract-landscape-metric-of-choice-for-all-cover-types-as-data-frame" class="section level4 unnumbered hasAnchor">
<h4>c. Extract landscape metric of choice for all cover types (as data frame)<a href="WE_2.html#c.-extract-landscape-metric-of-choice-for-all-cover-types-as-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To extract the landscape metric ‘prop.landscape’ for all cover types as a <code>tibble</code>, just filter <code>dplyr::filter()</code> the <code>tibble</code> again, but only use the <code>metric</code> as filter.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="WE_2.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="do">## f.lter for percentage of landscape</span></span>
<span id="cb429-2"><a href="WE_2.html#cb429-2" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_df <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(nlcd_sampled,</span>
<span id="cb429-3"><a href="WE_2.html#cb429-3" aria-hidden="true" tabindex="-1"></a>                                          metric <span class="sc">==</span> <span class="st">&quot;pland&quot;</span>)</span>
<span id="cb429-4"><a href="WE_2.html#cb429-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb429-5"><a href="WE_2.html#cb429-5" aria-hidden="true" tabindex="-1"></a>percentage_forest_500_df</span></code></pre></div>
<pre><code>## # A tibble: 154 × 8
##    layer level class    id metric   value plot_id percentage_inside
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt;   &lt;int&gt;             &lt;dbl&gt;
##  1     1 class    11    NA pland   7.25         1              98.0
##  2     1 class    31    NA pland   0.0918       1              98.0
##  3     1 class    42    NA pland  77.5          1              98.0
##  4     1 class    52    NA pland   1.93         1              98.0
##  5     1 class    71    NA pland  13.2          1              98.0
##  6     1 class    11    NA pland   3.49         2              98.0
##  7     1 class    12    NA pland   1.01         2              98.0
##  8     1 class    31    NA pland   0.735        2              98.0
##  9     1 class    42    NA pland  39.6          2              98.0
## 10     1 class    52    NA pland   5.33         2              98.0
## # … with 144 more rows</code></pre>
<p>The percent cover of all cover types should add up to ~ 100% (i.e., 1) for each site. We can check this with the function <code>dplyr::summarize()</code>. First, we need to group the data using the <code>plot_id</code>, then sum all percentages.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="WE_2.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="do">## g.oup by plot_id and sum all percentages</span></span>
<span id="cb431-2"><a href="WE_2.html#cb431-2" aria-hidden="true" tabindex="-1"></a>pland_sum_a <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">summarize</span>(dplyr<span class="sc">::</span><span class="fu">group_by</span>(percentage_forest_500_df, </span>
<span id="cb431-3"><a href="WE_2.html#cb431-3" aria-hidden="true" tabindex="-1"></a>                                                <span class="at">by =</span> plot_id), </span>
<span id="cb431-4"><a href="WE_2.html#cb431-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">sum_pland =</span> <span class="fu">sum</span>(value))</span>
<span id="cb431-5"><a href="WE_2.html#cb431-5" aria-hidden="true" tabindex="-1"></a>pland_sum_a</span></code></pre></div>
<pre><code>## # A tibble: 31 × 2
##       by sum_pland
##    &lt;int&gt;     &lt;dbl&gt;
##  1     1       100
##  2     2       100
##  3     3       100
##  4     4       100
##  5     5       100
##  6     6       100
##  7     7       100
##  8     8       100
##  9     9       100
## 10    10       100
## # … with 21 more rows</code></pre>
<p>Same workflow, but using a pipe:</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="WE_2.html#cb433-1" aria-hidden="true" tabindex="-1"></a>pland_sum_b <span class="ot">&lt;-</span> percentage_forest_500_df <span class="sc">%&gt;%</span> </span>
<span id="cb433-2"><a href="WE_2.html#cb433-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(plot_id) <span class="sc">%&gt;%</span> </span>
<span id="cb433-3"><a href="WE_2.html#cb433-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarize</span>(<span class="at">sum_pland =</span> <span class="fu">sum</span>(value))</span>
<span id="cb433-4"><a href="WE_2.html#cb433-4" aria-hidden="true" tabindex="-1"></a>pland_sum_b</span></code></pre></div>
<pre><code>## # A tibble: 31 × 2
##    plot_id sum_pland
##      &lt;int&gt;     &lt;dbl&gt;
##  1       1       100
##  2       2       100
##  3       3       100
##  4       4       100
##  5       5       100
##  6       6       100
##  7       7       100
##  8       8       100
##  9       9       100
## 10      10       100
## # … with 21 more rows</code></pre>
</div>
<div id="d.-extract-all-landscape-metrics-for-a-single-cover-type-as-data-frame" class="section level4 unnumbered hasAnchor">
<h4>d. Extract all landscape metrics for a single cover type (as data frame)<a href="WE_2.html#d.-extract-all-landscape-metrics-for-a-single-cover-type-as-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Filter<code>dplyr::filter()</code> for <code>class == 42</code> and add the sites names as coloumn to the resulting <code>tibble</code>.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="WE_2.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="do">## f.lter for class == 42 (forest)</span></span>
<span id="cb435-2"><a href="WE_2.html#cb435-2" aria-hidden="true" tabindex="-1"></a>forest_500_df <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(nlcd_sampled,</span>
<span id="cb435-3"><a href="WE_2.html#cb435-3" aria-hidden="true" tabindex="-1"></a>                               class <span class="sc">==</span> <span class="dv">42</span>)</span>
<span id="cb435-4"><a href="WE_2.html#cb435-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb435-5"><a href="WE_2.html#cb435-5" aria-hidden="true" tabindex="-1"></a><span class="do">## d.ta.frame with id and name of site</span></span>
<span id="cb435-6"><a href="WE_2.html#cb435-6" aria-hidden="true" tabindex="-1"></a>SiteName_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Sites.sp<span class="sc">$</span>SiteName), <span class="at">site_name =</span> Sites.sp<span class="sc">$</span>SiteName)</span>
<span id="cb435-7"><a href="WE_2.html#cb435-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb435-8"><a href="WE_2.html#cb435-8" aria-hidden="true" tabindex="-1"></a><span class="do">## a.d site_name to metrics using plot_id and id of sampling sites</span></span>
<span id="cb435-9"><a href="WE_2.html#cb435-9" aria-hidden="true" tabindex="-1"></a>forest_500_df <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">left_join</span>(forest_500_df, SiteName_df, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;plot_id&quot;</span> <span class="ot">=</span> <span class="st">&quot;id&quot;</span>))</span>
<span id="cb435-10"><a href="WE_2.html#cb435-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb435-11"><a href="WE_2.html#cb435-11" aria-hidden="true" tabindex="-1"></a>forest_500_df</span></code></pre></div>
<pre><code>## # A tibble: 93 × 9
##    layer level class    id metric value plot_id percentage_inside site_name     
##    &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;   &lt;int&gt;             &lt;dbl&gt; &lt;chr&gt;         
##  1     1 class    42    NA ai      93.3       1              98.0 AirplaneLake  
##  2     1 class    42    NA np       2         1              98.0 AirplaneLake  
##  3     1 class    42    NA pland   77.5       1              98.0 AirplaneLake  
##  4     1 class    42    NA ai      89.4       2              98.0 BachelorMeadow
##  5     1 class    42    NA np       7         2              98.0 BachelorMeadow
##  6     1 class    42    NA pland   39.6       2              98.0 BachelorMeadow
##  7     1 class    42    NA ai      79.4       3              98.0 BarkingFoxLake
##  8     1 class    42    NA np      10         3              98.0 BarkingFoxLake
##  9     1 class    42    NA pland   38.0       3              98.0 BarkingFoxLake
## 10     1 class    42    NA ai      81.2       4             104.  BirdbillLake  
## # … with 83 more rows</code></pre>
<p>Done!</p>
<p>Check out this week’s bonus material to see:</p>
<ul>
<li>How to convert the site data from an <code>sp</code> object to an <code>sf</code> object, a new standard for geospatial vector data.</li>
<li>How to create static and interactive maps of an <code>sf</code> object with <code>tmap</code>.</li>
<li>How to export an <code>sf</code> object to a, ESRI shapefile.</li>
<li>How to plot a categorical raster map with a predefined color scheme, using <code>tmap</code> and a new standard for raster data (<code>terra</code> package).</li>
</ul>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tutorial_2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="r-exercise-week-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
